namespace Kabic.Zig;

using Kabic;
using System.Text;

/// <summary>
/// kabic's Zig backend: renders a domain as a Zig module — the ABI declared in Zig
/// rather than imported from the header, and a projection over it whose signatures
/// are Zig's own (error unions, optionals, slices, sentinel-terminated strings).
/// </summary>
/// <remarks>
/// <para>
/// Declares the ABI instead of reaching for <c>@cImport</c> on purpose. Importing
/// the header is what makes a Zig consumer feel it is calling a C library: every
/// pointer arrives as <c>[*c]</c>, which is both nullable and many-item, so the
/// compiler stops distinguishing "one value" from "an array" and stops catching a
/// missing null check. A declared ABI says which of the two each pointer is, and
/// the projection above it can then be total rather than defensive.
/// </para>
/// <para>
/// Emits no <c>comptime</c> machinery. The projection is one wrapper struct per
/// vtable with plain methods, which is the shape a C programmer reading Zig would
/// write. Whether a richer rendering is worth it is a question for after the
/// signatures are right, not before.
/// </para>
/// </remarks>
public sealed class ZigBackend
{
    readonly ApiModel model;
    readonly ClassifiedModel classified;
    readonly Convention convention;
    readonly IReadOnlyDictionary<string, ForeignType> foreign;
    readonly SortedDictionary<string, string> imported = [];

    ZigBackend(ApiModel model, ClassifiedModel classified, Convention convention,
        IReadOnlyDictionary<string, ForeignType> foreign)
    {
        this.model = model;
        this.classified = classified;
        this.convention = convention;
        this.foreign = foreign;
    }

    /// <summary>
    /// Renders one domain. <paramref name="foreign"/> says where a type this domain
    /// composes but does not declare is reachable from: the domain that owns a type
    /// emits it, this one imports it. Zig has no ambient namespace for such a name to
    /// resolve in, so a domain rendered without the map spells a symbol its module
    /// never declares.
    /// </summary>
    public static string Render(ApiModel model, ClassifiedModel classified, Convention convention,
        IReadOnlyDictionary<string, ForeignType>? foreign = null) =>
        new ZigBackend(model, classified, convention, foreign ?? new Dictionary<string, ForeignType>())
            .Render();

    string Render()
    {
        var sb = new StringBuilder();

        foreach (var (alias, target) in model.TypeAliases)
        {
            var prim = Idioms.Primitive(target);
            if (prim is not null) sb.AppendLine($"pub const {Idioms.TypeName(alias, convention)} = {prim};");
        }
        sb.AppendLine();

        foreach (var e in model.Enums.Where(e => !e.External)) RenderEnum(sb, e);

        sb.AppendLine(Preamble);

        sb.AppendLine("/// The ABI as the header declares it. Nothing above this line is a C name and");
        sb.AppendLine("/// nothing below it is meant to be called by hand.");
        sb.AppendLine("pub const abi = struct {");
        sb.AppendLine(AbiPreamble);
        foreach (var s in model.Structs.Where(s => !s.External))
        {
            sb.AppendLine($"    pub const {s.Name} = extern struct {{");
            foreach (var f in s.Fields)
                sb.AppendLine($"        {Idioms.Ident(f.Name)}: {AbiType(f.Type, null, "")},");
            foreach (var slot in s.Slots)
                sb.AppendLine($"        {Idioms.Ident(slot.Name)}: *const fn ({SlotAbiParams(s, slot)})"
                    + $" callconv(.c) {AbiReturn(slot, "")},");
            sb.AppendLine("    };");
            sb.AppendLine();
        }
        foreach (var f in model.Functions)
            sb.AppendLine($"    pub extern fn {f.Name}({string.Join(", ", f.Params.Select(p =>
                $"{Idioms.Ident(p.Name ?? "_")}: {AbiType(p.Type, p, "")}"))}) "
                + $"callconv(.c) {AbiType(f.Returns, null, "")};");
        sb.AppendLine("};");
        sb.AppendLine();

        foreach (var v in classified.Providers)
            RenderProvider(sb, v);

        var head = new StringBuilder();
        head.AppendLine("//! <auto-generated/> Derived from ke_api.json. Do not edit; edit the C header instead.");
        head.AppendLine();
        foreach (var (module, path) in imported)
            head.AppendLine($"const {module} = @import(\"{path}\");");
        if (imported.Count > 0) head.AppendLine();
        return head.Append(sb).ToString();
    }

    /// <summary>
    /// One C enum as a Zig enum. A member whose C initialiser names a sibling is not a
    /// case of its own: it is a second name for one that already exists, so it is
    /// rendered as a declaration rather than a field. Zig refuses two fields sharing a
    /// tag value, so the alternative is not a duplicated case but no output at all --
    /// and emitting the C initialiser verbatim would name a symbol the Zig module does
    /// not declare.
    /// </summary>
    void RenderEnum(StringBuilder sb, ApiEnum e)
    {
        if (e.Doc is not null) foreach (var line in DocLines(e.Doc)) sb.AppendLine(line);
        sb.AppendLine($"pub const {Idioms.TypeName(e.Name, convention)} = enum(u32) {{");
        foreach (var v in e.Values.Where(v => v.IsInt))
        {
            if (v.Doc is not null) foreach (var line in DocLines(v.Doc, "    ")) sb.AppendLine(line);
            sb.AppendLine($"    {Idioms.EnumMember(v.Name, e.Name)} = {v.RawValue},");
        }
        foreach (var v in e.Values.Where(v => !v.IsInt))
        {
            if (v.Doc is not null) foreach (var line in DocLines(v.Doc, "    ")) sb.AppendLine(line);
            sb.AppendLine($"    pub const {Idioms.EnumMember(v.Name, e.Name)}: @This() = "
                + $".{Idioms.EnumMember(v.RawValue, e.Name)};");
        }
        sb.AppendLine("};");
        sb.AppendLine();
    }

    const string Preamble = """
        /// The failure a fallible call reported. A Zig error set carries a kind and
        /// nothing else, so the message, the source location and the cause chain the
        /// native side filled in have to be readable somewhere; thread-local for the
        /// same reason the native slot is, which is that two threads failing at once
        /// are two failures.
        pub threadlocal var last_error: ?*const abi.ke_error = null;

        pub const Error = error{
            General,
            NotFound,
            Io,
            OutOfMemory,
            InvalidArgument,
            NotInitialized,
            NotSupported,
            AlreadyExists,
        };

        fn raise(err: ?*const abi.ke_error) Error {
            last_error = err;
            if (abi.ke_error_is(err, &abi.KE_ERROR_NOT_FOUND)) return Error.NotFound;
            if (abi.ke_error_is(err, &abi.KE_ERROR_IO)) return Error.Io;
            if (abi.ke_error_is(err, &abi.KE_ERROR_OUT_OF_MEMORY)) return Error.OutOfMemory;
            if (abi.ke_error_is(err, &abi.KE_ERROR_INVALID_ARGUMENT)) return Error.InvalidArgument;
            if (abi.ke_error_is(err, &abi.KE_ERROR_NOT_INITIALIZED)) return Error.NotInitialized;
            if (abi.ke_error_is(err, &abi.KE_ERROR_NOT_SUPPORTED)) return Error.NotSupported;
            if (abi.ke_error_is(err, &abi.KE_ERROR_ALREADY_EXISTS)) return Error.AlreadyExists;
            return Error.General;
        }

        """;

    const string AbiPreamble = """
            pub const ke_error_type = extern struct {
                name: ?[*:0]const u8,
                parent: ?*const ke_error_type,
            };

            pub const ke_error = extern struct {
                @"type": ?*const ke_error_type,
                message: ?[*:0]const u8,
                file: ?[*:0]const u8,
                line: u32,
                cause: ?*const ke_error,
            };

            pub extern fn ke_error_is(err: ?*const ke_error, @"type": *const ke_error_type) callconv(.c) bool;

            pub extern const KE_ERROR_NOT_FOUND: ke_error_type;
            pub extern const KE_ERROR_IO: ke_error_type;
            pub extern const KE_ERROR_OUT_OF_MEMORY: ke_error_type;
            pub extern const KE_ERROR_INVALID_ARGUMENT: ke_error_type;
            pub extern const KE_ERROR_NOT_INITIALIZED: ke_error_type;
            pub extern const KE_ERROR_NOT_SUPPORTED: ke_error_type;
            pub extern const KE_ERROR_ALREADY_EXISTS: ke_error_type;

        """;

    /// <summary>
    /// The slot's parameters with its receiver put back. The receiver is not always
    /// the struct that declares the slot -- an owner wrapper's <c>destroy</c> takes
    /// the value the wrapper holds -- so it is read from the description rather than
    /// assumed, because a declaration naming the wrong pointer type still compiles.
    /// </summary>
    string SlotAbiParams(ApiStruct owner, ApiSlot slot)
    {
        var receiver = slot.Receiver is { } declared
            ? AbiType(declared, null, "")
            : $"*{owner.Name}";
        return string.Join(", ", new[] { $"self: {receiver}" }
            .Concat(slot.Params.Select(p =>
                $"{Idioms.Ident(p.Name ?? "_")}: {AbiType(p.Type, p, "")}")));
    }

    string AbiReturn(ApiSlot slot, string q) =>
        slot.ReturnTagValue("array_of") is not null
            ? $"?[*]const {AbiType(CTypes.Deref(slot.Returns), null, q)}"
            : AbiType(slot.Returns, null, q);

    /// <summary>
    /// The Zig spelling of a C type. Every pointer answers two questions C leaves
    /// open — may it be null, and does it reach one value or many — and the answers
    /// come from the tags, which is the whole reason this is not <c>@cImport</c>.
    /// A fixed extent moves to the front, where Zig writes it, and the element type
    /// goes on through the same mapping: an extent left as a C declarator suffix
    /// would take the whole spelling off the primitive table with it.
    /// </summary>
    string AbiType(string cType, ApiParam? p, string q)
    {
        if (CTypes.FixedArray(cType) is { } arr)
            return $"[{arr.Extent}]{AbiType(arr.Element, p, q)}";

        var t = Idioms.Base(cType);
        var isConst = cType.Contains("const ");
        var depth = t.Count(ch => ch == '*');
        var bare = t.TrimEnd('*', ' ').Trim();

        if (depth == 0) return Named(bare, q);
        if (bare is "void") return depth == 1 ? "?*anyopaque" : "*?*anyopaque";
        if (bare is "char" && depth == 1) return "[*:0]const u8";

        var inner = Named(bare, q);
        var cv = isConst ? "const " : "";
        if (depth == 2) return $"?*?*{cv}{inner}";
        if (p is not null && p.Has("array_of")) return $"[*]{cv}{inner}";
        return p is not null && p.Has("optional") ? $"?*{cv}{inner}" : $"*{cv}{inner}";
    }

    string Named(string bare, string q)
    {
        if (Idioms.Primitive(bare) is { } prim && !model.TypeAliases.ContainsKey(bare)) return prim;
        if (!DeclaredHere(bare) && foreign.TryGetValue(bare, out var owner))
        {
            imported[owner.Module] = owner.ImportPath;
            return owner.IsStruct
                ? $"{owner.Module}.abi.{bare}"
                : $"{owner.Module}.{Idioms.TypeName(bare, convention)}";
        }
        if (model.TypeAliases.TryGetValue(bare, out var target) && Idioms.Primitive(target) is not null)
            return Idioms.TypeName(bare, convention);
        if (model.Enums.Any(e => e.Name == bare)) return Idioms.TypeName(bare, convention);
        if (model.Structs.Any(s => s.Name == bare)) return q + bare;
        return Idioms.Primitive(bare) ?? q + bare;
    }

    /// <summary>
    /// Whether this domain declares the type itself. A type reaching the model marked
    /// external, or reaching it only as the spelling of a field, is declared by some
    /// other domain -- which is exactly the case an import answers.
    /// </summary>
    bool DeclaredHere(string bare) =>
        model.Structs.Any(s => s.Name == bare && !s.External)
        || model.Enums.Any(e => e.Name == bare && !e.External)
        || model.TypeAliases.ContainsKey(bare);

    /// <summary>The Zig type a projected value reads as, outside the ABI block.</summary>
    string PubType(string cType, ApiParam? p) =>
        AbiType(cType, p, "abi.");

    void RenderProvider(StringBuilder sb, ApiStruct v)
    {
        var name = Idioms.TypeName(v.Name, convention);
        if (v.Doc is not null) foreach (var line in DocLines(v.Doc)) sb.AppendLine(line);
        sb.AppendLine($"pub const {name} = struct {{");
        sb.AppendLine($"    ref: *abi.{v.Name},");
        sb.AppendLine($"    destroy: ?*const fn (self: *abi.{v.Name}) callconv(.c) void,");
        sb.AppendLine();
        sb.AppendLine($"    pub fn init(handle: abi.{convention.HandleTypeFor(v.Name)}) {name} {{");
        sb.AppendLine("        return .{ .ref = handle.ref, .destroy = handle.destroy };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// Wraps a native pointer owned elsewhere. Deinit does not destroy it.");
        sb.AppendLine($"    pub fn borrow(ref: *abi.{v.Name}) {name} {{");
        sb.AppendLine("        return .{ .ref = ref, .destroy = null };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    pub fn deinit(self: *{name}) void {{");
        sb.AppendLine("        if (self.destroy) |d| d(self.ref);");
        sb.AppendLine("        self.destroy = null;");
        sb.AppendLine("    }");

        var declared = classified.SlotsByVtable[v.Name]
            .Select(cs => Idioms.Camel(cs.Slot.Name)).ToHashSet();
        declared.UnionWith(["init", "borrow", "deinit", "ref", "destroy"]);

        foreach (var cs in classified.SlotsByVtable[v.Name])
        {
            sb.AppendLine();
            RenderSlot(sb, cs, name, declared);
        }
        sb.AppendLine("};");
        sb.AppendLine();
    }

    record Reading(string Name, string Type, string Expr);

    /// <summary>
    /// One slot as a method on the projection. <paramref name="declared"/> is what the
    /// projection struct already declares: Zig refuses a parameter that shadows an
    /// outer declaration, and a vtable with both a <c>parent</c> slot and a
    /// <c>parent</c> parameter is not a mistake in the header -- the two names live in
    /// different scopes in C, and only the projection puts them in the same one.
    /// </summary>
    void RenderSlot(StringBuilder sb, ClassifiedSlot cs, string owner, IReadOnlySet<string> declared)
    {
        string Arg(ApiParam p) =>
            Idioms.Ident(declared.Contains(p.Name!) ? p.Name! + "_arg" : p.Name!);

        var slot = cs.Slot;
        if (cs.Blobs.Count > 0 || cs.ExpandedParam is not null
            || slot.Params.Any(p => model.CallbackOf(p.Type) is not null || p.Has("callback")))
            throw new NotSupportedException(
                $"{slot.Name}: this backend renders no callback, no [expand] and no opaque payload yet.");

        var outs = (cs.Shape switch
        {
            SlotShape.Try or SlotShape.TupleOutParams => cs.OutParams,
            SlotShape.ReturnsOutParam => [cs.OutParam!],
            _ => cs.TrailingOuts,
        }).Where(p => !IsWritableSpan(p)).ToList();
        var errParam = cs.Fallible ? slot.Params[^1] : null;
        var counts = cs.Sequences.Select(s => s.Count).ToHashSet();

        var sig = cs.PublicParams.Where(p => !p.Has("out") || IsWritableSpan(p)).ToList();
        var body = new List<string>();
        var args = new List<string> { "self.ref" };

        foreach (var p in slot.Params)
        {
            if (p == errParam) { args.Add("&err"); continue; }
            if (counts.Contains(p)) { args.Add($"@intCast({Arg(cs.Sequences.First(s => s.Count == p).Seq)}.len)"); continue; }
            if (p == cs.ReturnCount) { args.Add("&count"); continue; }
            if (p.Has("array_of")) { args.Add($"{Arg(p)}.ptr"); continue; }
            if (p.Has("out")) { args.Add("&" + Local(p)); continue; }
            if (p.Has("utf8")) { args.Add($"{Arg(p)}.ptr"); continue; }
            args.Add(Arg(p));
        }

        foreach (var p in outs)
            body.Add($"var {Local(p)}: "
                + $"{PubType(CTypes.Deref(p.Type), null)} = undefined;");
        if (cs.ReturnCount is not null) body.Add("var count: u32 = 0;");
        if (cs.Fallible) body.Add("var err: ?*abi.ke_error = null;");

        var call = $"self.ref.{Idioms.Ident(slot.Name)}({string.Join(", ", args)})";

        var readings = outs.Select(p => new Reading(WrittenName(p),
            PubType(CTypes.Deref(p.Type), null),
            Local(p))).ToList();

        var returnIsFailureLane = convention.SignalsFailureByReturn(slot.Returns)
            && (cs.Fallible || cs.Shape is SlotShape.Try);
        var carriesReturn = slot.Returns.Trim() is not "void" && !returnIsFailureLane;
        string? valueType = null;
        if (cs.ReturnCount is not null)
            valueType = $"[]const {PubType(CTypes.Deref(slot.Returns), null)}";
        else if (carriesReturn)
            valueType = PubType(slot.Returns, null);

        var items = (valueType is null ? readings : readings.Prepend(new Reading("value", valueType, "result"))).ToList();
        var inner = items.Count switch
        {
            0 => "void",
            1 => items[0].Type,
            _ => "struct { " + string.Join(", ", items.Select(i => $"{Idioms.Ident(i.Name)}: {i.Type}")) + " }",
        };
        var ret = cs.Shape is SlotShape.Try ? $"?{inner}" : cs.Fallible ? $"Error!{inner}" : inner;

        string Compose() => items.Count switch
        {
            0 => "return;",
            1 => $"return {items[0].Expr};",
            _ => "return .{ " + string.Join(", ", items.Select(i => $".{Idioms.Ident(i.Name)} = {i.Expr}")) + " };",
        };

        if (cs.ReturnCount is not null)
        {
            body.Add($"const front = {call} orelse return &.{{}};");
            body.Add("return front[0..count];");
        }
        else if (cs.Shape is SlotShape.Try)
        {
            body.Add($"if (!{call}) return null;");
            body.Add(Compose());
        }
        else if (cs.Fallible && convention.SignalsFailureByReturn(slot.Returns))
        {
            body.Add($"if (!{call}) return raise(err);");
            body.Add(Compose());
        }
        else if (carriesReturn)
        {
            body.Add($"const result = {call};");
            if (cs.Fallible) body.Add("if (err != null) return raise(err);");
            body.Add(Compose());
        }
        else
        {
            body.Add($"{call};");
            body.Add(Compose());
        }

        if (slot.Doc is not null) foreach (var line in DocLines(slot.Doc, "    ")) sb.AppendLine(line);
        var sigText = string.Join(", ", new[] { $"self: {owner}" }
            .Concat(sig.Select(p => $"{Arg(p)}: {SigType(p)}")));
        sb.AppendLine($"    pub fn {Idioms.Camel(slot.Name)}({sigText}) {ret} {{");
        foreach (var line in body) sb.AppendLine($"        {line}");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// How a supplied parameter is spelled in the projection. A counted pointer is
    /// one slice, a utf8 string is one sentinel-terminated slice, and in both cases
    /// the length the ABI takes separately comes off the value itself.
    /// </summary>
    string SigType(ApiParam p)
    {
        if (p.Has("utf8")) return "[:0]const u8";
        if (p.Has("array_of"))
            return (IsWritableSpan(p) ? "[]" : "[]const ") + PubType(CTypes.Deref(p.Type), null);
        return PubType(p.Type, p);
    }

    /// <summary>
    /// Whether a parameter is a buffer the caller allocates and the callee fills. It
    /// is written back, like any <c>[out]</c>, and it is also counted, which is what
    /// says the count is the caller's -- so there is nothing here to declare a local
    /// for and take the address of: the value already is the memory, and the span
    /// carries the capacity the ABI asks for separately.
    /// </summary>
    static bool IsWritableSpan(ApiParam p) => p.Has("out") && p.Has("array_of");

    /// <summary>The local a written-back parameter's address is taken from.</summary>
    static string Local(ApiParam p) => Idioms.Ident(WrittenName(p) + "_out");

    static string WrittenName(ApiParam p) =>
        p.Name!.StartsWith("out_", StringComparison.Ordinal) && p.Name!.Length > 4
            ? p.Name!["out_".Length..] : p.Name!;

    static IEnumerable<string> DocLines(string doc, string indent = "")
    {
        var words = doc.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var line = new StringBuilder();
        foreach (var w in words)
        {
            if (line.Length > 0 && line.Length + w.Length > 76) { yield return $"{indent}/// {line}"; line.Clear(); }
            if (line.Length > 0) line.Append(' ');
            line.Append(w);
        }
        if (line.Length > 0) yield return $"{indent}/// {line}";
    }
}
