<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Kabic.Core/Kabic.Core.csproj" />
    <ProjectReference Include="../Kabic.Frontend/Kabic.Frontend.csproj" />
    <ProjectReference Include="../Kabic.CSharpBackend/Kabic.CSharpBackend.csproj" />
  </ItemGroup>
</Project>
