<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup Condition="'$(UsePackageReferences)' != 'true'">
    <ProjectReference Include="..\KernelEngine.Core\KernelEngine.Core.csproj" />
    <ProjectReference Include="..\Native\KernelEngine.Glfw.Native\KernelEngine.Glfw.Native.csproj" />
    <ProjectReference Include="..\Native\KernelEngine.Core.Native\KernelEngine.Core.Native.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UsePackageReferences)' == 'true'">
    <PackageReference Include="KernelEngine.Core" Version="$(Version)" />
    <PackageReference Include="KernelEngine.Glfw.Native" Version="$(Version)" />
    <PackageReference Include="KernelEngine.Core.Native" Version="$(Version)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
  </ItemGroup>

</Project>
