namespace Kabic.C;

/// <summary>
/// kabic's C backend: renders a domain's component structs as
/// <c>ke_component_field</c> tables, so the scene loader can apply a TOML block
/// to component memory by reading a description instead of running a callback
/// somebody wrote by hand for that one component.
/// </summary>
/// <remarks>
/// <para>
/// Emits C rather than computing offsets itself. A generator that laid out the
/// struct would be a second, silently divergent authority on the ABI: it would
/// have to model padding and alignment for every target, and would be wrong on
/// the first platform whose rules differ. <c>offsetof</c> and <c>sizeof</c> hand
/// that question back to the compiler that owns it.
/// </para>
/// <para>
/// Field names in the table are the C field names. A scene file addresses a
/// component field by the name the header gives it; <c>[name:]</c> renames the
/// property a language binding exposes, which is a binding concern and does not
/// reach the file format.
/// </para>
/// </remarks>
public static class CBackend
{
    /// <summary>
    /// Renders the field tables for every non-vtable, non-composed struct in
    /// <paramref name="model"/> that carries at least one describable field.
    /// </summary>
    /// <param name="model">The domain's parsed description.</param>
    /// <param name="guard">Include-guard macro, e.g. <c>KE_RENDER_COMPONENT_FIELDS_H_</c>.</param>
    /// <param name="includes">Headers the table references, in include order.</param>
    /// <param name="convention">Names the shape a component's type has in this ABI.</param>
    public static string RenderFieldTables(ApiModel model, string guard, IReadOnlyList<string> includes,
        Convention convention)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("/* <auto-generated/> Derived from ke_api.json. Do not edit; edit the C header instead. */");
        sb.AppendLine($"#ifndef {guard}");
        sb.AppendLine($"#define {guard}");
        sb.AppendLine();
        sb.AppendLine("#include <kernel_engine/ecs/component_field.h>");
        foreach (var inc in includes) sb.AppendLine($"#include <{inc}>");
        sb.AppendLine("#include <stddef.h>");
        sb.AppendLine();

        var named = Named(model, convention).ToList();
        if (named.Count > 0)
        {
            foreach (var s in named)
                sb.AppendLine($"#define {NameMacro(s, convention)} \"{convention.ComponentNameFor(s.Name)}\"");
            sb.AppendLine();
        }

        foreach (var s in Describable(model, convention))
        {
            var fields = s.Fields.Where(f => Describes(model, f)).ToList();
            sb.AppendLine($"static const ke_component_field {s.Name}_fields[] = {{");
            foreach (var f in fields)
                sb.AppendLine($"    {{ \"{f.TagValue("name") ?? f.Name}\", {VariantOf(model, f)}, "
                    + $"offsetof({s.Name}, {f.Name}), sizeof((({s.Name} *)0)->{f.Name}), "
                    + $"{DefaultOf(model, f)} }},");
            sb.AppendLine("};");
            sb.AppendLine();
        }

        sb.AppendLine($"#endif /* {guard} */");
        return sb.ToString();
    }

    /// <summary>
    /// The structs this backend describes: a domain's own component structs, in
    /// declaration order. A vtable is behavior; a composed struct belongs to the
    /// domain that owns it, which emits its table there; and a plain helper
    /// struct a component happens to be built out of is not itself addressable
    /// by a scene file, which is what the component suffix tells them apart by.
    /// </summary>
    /// <summary>
    /// The component structs this domain names. Wider than <see cref="Describable"/>: a
    /// component a scene file cannot author still has to be registered under a name, and
    /// every language reaching it needs the same one. A component with no describable field
    /// would otherwise have its name spelled by hand next to a struct that already implies
    /// it.
    /// </summary>
    public static IEnumerable<ApiStruct> Named(ApiModel model, Convention convention) =>
        model.Structs.Where(s => !s.IsVtable && !s.External && convention.IsComponentType(s.Name));

    /// <summary>The macro a component's registered name is reached by from C and Zig.</summary>
    public static string NameMacro(ApiStruct s, Convention convention) =>
        $"KE_COMPONENT_NAME_{convention.ComponentNameFor(s.Name).ToUpperInvariant()}";

    public static IEnumerable<ApiStruct> Describable(ApiModel model, Convention convention) =>
        model.Structs.Where(s => !s.IsVtable
            && !s.External
            && s.Name.EndsWith(convention.ComponentSuffix, StringComparison.Ordinal)
            && s.Fields.Any(f => Describes(model, f)));

    /// <summary>
    /// Whether a scene file can address this field at all. <c>[output]</c> is a
    /// field a system writes every tick; describing it would invite a scene to
    /// author a value that is overwritten before anything reads it.
    /// </summary>
    /// <summary>
    /// Renders a field's <c>[default:]</c> as an initializer for the table's
    /// ke_variant, or the null variant when the header declares none.
    /// </summary>
    private static string DefaultOf(ApiModel model, ApiField f)
    {
        var d = f.TagValue("default");
        if (d is null) return "{ KE_VARIANT_NULL, { 0 } }";

        var variant = VariantOf(model, f);
        var parts = d.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        var lanes = variant switch
        {
            "KE_VARIANT_VEC2" => 2, "KE_VARIANT_VEC3" => 3,
            "KE_VARIANT_VEC4" or "KE_VARIANT_QUAT" => 4,
            _ => 1,
        };
        if (parts.Length != lanes)
            throw new InvalidOperationException(
                $"{f.Name}: [default:{d}] has {parts.Length} components but {variant} takes {lanes}");

        var lane = variant switch
        {
            "KE_VARIANT_VEC2" => ".v2", "KE_VARIANT_VEC3" => ".v3",
            "KE_VARIANT_VEC4" => ".v4", "KE_VARIANT_QUAT" => ".q",
            "KE_VARIANT_BOOL" => ".b", "KE_VARIANT_INT" => ".i",
            "KE_VARIANT_FLOAT" => ".f", "KE_VARIANT_STRING" => ".s",
            _ => null,
        };
        if (lane is null) return "{ KE_VARIANT_NULL, { 0 } }";

        var value = variant switch
        {
            "KE_VARIANT_STRING" => $"\"{d}\"",
            "KE_VARIANT_BOOL" => d is "1" or "true" ? "true" : "false",
            "KE_VARIANT_INT" => d,
            "KE_VARIANT_FLOAT" => CDouble(parts[0]),
            _ => "{ " + string.Join(", ", parts.Select(p => CDouble(p) + "f")) + " }",
        };
        return $"{{ {variant}, {{ {lane} = {value} }} }}";
    }

    /// <summary>A C floating literal: "5" is not one, "5.0" is.</summary>
    private static string CDouble(string raw) => raw.Contains('.') ? raw : raw + ".0";

    private static bool Describes(ApiModel model, ApiField f) => !f.Has("output") && VariantOf(model, f) is not null;

    /// <summary>
    /// The <c>ke_variant_type</c> a field is addressed as, or null when the field
    /// has no scene-file spelling — a derived matrix or an opaque handle is
    /// produced by a system, never written down.
    /// </summary>
    private static string? VariantOf(ApiModel model, ApiField f)
    {
        if (f.Has("bool")) return "KE_VARIANT_BOOL";
        if (model.Enums.Any(e => e.Name == Base(f.Type))) return "KE_VARIANT_INT";
        return Base(f.Type) switch
        {
            "float" or "double"                        => "KE_VARIANT_FLOAT",
            "ke_vec2"                                  => "KE_VARIANT_VEC2",
            "ke_vec3"                                  => "KE_VARIANT_VEC3",
            "ke_vec4"                                  => "KE_VARIANT_VEC4",
            "ke_quat"                                  => "KE_VARIANT_QUAT",
            "bool" or "_Bool"                          => "KE_VARIANT_BOOL",
            "int8_t" or "int16_t" or "int32_t" or "int64_t" => "KE_VARIANT_INT",
            "uint8_t" or "uint16_t" or "uint32_t" or "uint64_t" => "KE_VARIANT_INT",
            "int" or "unsigned" or "unsigned int"      => "KE_VARIANT_INT",
            var t when t.StartsWith("char[")           => "KE_VARIANT_STRING",
            "float[2]"                                 => "KE_VARIANT_VEC2",
            "float[3]"                                 => "KE_VARIANT_VEC3",
            "float[4]"                                 => "KE_VARIANT_VEC4",
            _                                          => null,
        };
    }

    private static string Base(string cType) =>
        cType.Replace("const ", "").Replace("struct ", "").Trim();
}
