namespace Kabic.C;

/// <summary>
/// kabic's C backend: renders a domain's component structs as
/// <c>ke_component_field</c> tables, so the scene loader can apply a TOML block
/// to component memory by reading a description instead of running a callback
/// somebody wrote by hand for that one component.
/// </summary>
/// <remarks>
/// <para>
/// Emits C rather than computing offsets itself. A generator that laid out the
/// struct would be a second, silently divergent authority on the ABI: it would
/// have to model padding and alignment for every target, and would be wrong on
/// the first platform whose rules differ. <c>offsetof</c> and <c>sizeof</c> hand
/// that question back to the compiler that owns it.
/// </para>
/// <para>
/// Field names in the table are the C field names. A scene file addresses a
/// component field by the name the header gives it; <c>[name:]</c> renames the
/// property a language binding exposes, which is a binding concern and does not
/// reach the file format.
/// </para>
/// </remarks>
public static class CBackend
{
    /// <summary>
    /// Renders the field tables for every non-vtable, non-composed struct in
    /// <paramref name="model"/> that carries at least one describable field.
    /// </summary>
    /// <param name="model">The domain's parsed description.</param>
    /// <param name="guard">Include-guard macro, e.g. <c>KE_RENDER_COMPONENT_FIELDS_H_</c>.</param>
    /// <param name="includes">Headers the table references, in include order.</param>
    /// <param name="convention">Names the shape a component's type has in this ABI.</param>
    public static string RenderFieldTables(ApiModel model, string guard, IReadOnlyList<string> includes,
        Convention convention)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("/* <auto-generated/> Derived from ke_api.json. Do not edit; edit the C header instead. */");
        sb.AppendLine($"#ifndef {guard}");
        sb.AppendLine($"#define {guard}");
        sb.AppendLine();
        sb.AppendLine("#include <kernel_engine/ecs/component_field.h>");
        foreach (var inc in includes) sb.AppendLine($"#include <{inc}>");
        sb.AppendLine("#include <stddef.h>");
        sb.AppendLine();

        foreach (var s in Describable(model, convention))
        {
            var fields = s.Fields.Where(Describes).ToList();
            sb.AppendLine($"static const ke_component_field {s.Name}_fields[] = {{");
            foreach (var f in fields)
                sb.AppendLine($"    {{ \"{f.TagValue("name") ?? f.Name}\", {VariantOf(f)}, "
                    + $"offsetof({s.Name}, {f.Name}), sizeof((({s.Name} *)0)->{f.Name}) }},");
            sb.AppendLine("};");
            sb.AppendLine();
        }

        sb.AppendLine($"#endif /* {guard} */");
        return sb.ToString();
    }

    /// <summary>
    /// The structs this backend describes: a domain's own component structs, in
    /// declaration order. A vtable is behavior; a composed struct belongs to the
    /// domain that owns it, which emits its table there; and a plain helper
    /// struct a component happens to be built out of is not itself addressable
    /// by a scene file, which is what the component suffix tells them apart by.
    /// </summary>
    public static IEnumerable<ApiStruct> Describable(ApiModel model, Convention convention) =>
        model.Structs.Where(s => !s.IsVtable
            && !s.External
            && s.Name.EndsWith(convention.ComponentSuffix, StringComparison.Ordinal)
            && s.Fields.Any(f => Describes(f)));

    /// <summary>
    /// Whether a scene file can address this field at all. <c>[output]</c> is a
    /// field a system writes every tick; describing it would invite a scene to
    /// author a value that is overwritten before anything reads it.
    /// </summary>
    private static bool Describes(ApiField f) => !f.Has("output") && VariantOf(f) is not null;

    /// <summary>
    /// The <c>ke_variant_type</c> a field is addressed as, or null when the field
    /// has no scene-file spelling — a derived matrix or an opaque handle is
    /// produced by a system, never written down.
    /// </summary>
    private static string? VariantOf(ApiField f)
    {
        if (f.Has("bool")) return "KE_VARIANT_BOOL";
        return Base(f.Type) switch
        {
            "float" or "double"                        => "KE_VARIANT_FLOAT",
            "ke_vec2"                                  => "KE_VARIANT_VEC2",
            "ke_vec3"                                  => "KE_VARIANT_VEC3",
            "ke_vec4"                                  => "KE_VARIANT_VEC4",
            "ke_quat"                                  => "KE_VARIANT_QUAT",
            "bool"                                     => "KE_VARIANT_BOOL",
            "int8_t" or "int16_t" or "int32_t" or "int64_t" => "KE_VARIANT_INT",
            "uint8_t" or "uint16_t" or "uint32_t" or "uint64_t" => "KE_VARIANT_INT",
            "int" or "unsigned" or "unsigned int"      => "KE_VARIANT_INT",
            var t when t.StartsWith("char[")           => "KE_VARIANT_STRING",
            // A bare float array is the same vector a ke_vecN names, spelled
            // without the typedef; the C# backend already reads it that way.
            "float[2]"                                 => "KE_VARIANT_VEC2",
            "float[3]"                                 => "KE_VARIANT_VEC3",
            "float[4]"                                 => "KE_VARIANT_VEC4",
            _                                          => null,
        };
    }

    private static string Base(string cType) =>
        cType.Replace("const ", "").Replace("struct ", "").Trim();
}
