#ifndef KERNEL_ENGINE_FRAMEWORK_NODE_TYPE_REGISTRY_EXPORT_H_
#define KERNEL_ENGINE_FRAMEWORK_NODE_TYPE_REGISTRY_EXPORT_H_

#if defined(_WIN32) || defined(__CYGWIN__)
#define KE_NODE_TYPE_REGISTRY_HELPER_EXPORT __declspec(dllexport)
#define KE_NODE_TYPE_REGISTRY_HELPER_IMPORT __declspec(dllimport)
#else
#define KE_NODE_TYPE_REGISTRY_HELPER_EXPORT __attribute__((visibility("default")))
#define KE_NODE_TYPE_REGISTRY_HELPER_IMPORT __attribute__((visibility("default")))
#endif

#ifdef KE_NODE_TYPE_REGISTRY_STATIC
#define KE_NODE_TYPE_REGISTRY_API
#else
#ifdef KE_NODE_TYPE_REGISTRY_EXPORT
#define KE_NODE_TYPE_REGISTRY_API KE_NODE_TYPE_REGISTRY_HELPER_EXPORT
#else
#define KE_NODE_TYPE_REGISTRY_API KE_NODE_TYPE_REGISTRY_HELPER_IMPORT
#endif
#endif

#endif // KERNEL_ENGINE_FRAMEWORK_NODE_TYPE_REGISTRY_EXPORT_H_
