<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NativeTarget>ke_asset_stb_image</NativeTarget>
  </PropertyGroup>

  <Import Project="../../NativeDependencies.targets" />

  <ItemGroup>
    <ProjectReference Include="..\KernelEngine.Asset.Abstractions\KernelEngine.Asset.Abstractions.csproj" />
    <ProjectReference Include="..\KernelEngine.Asset\KernelEngine.Asset.csproj" />
    <ProjectReference Include="..\..\common\KernelEngine.Common\KernelEngine.Common.csproj" />
    <ProjectReference Include="..\..\logger\KernelEngine.Logger\KernelEngine.Logger.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
  </ItemGroup>

</Project>
