<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../KernelEngine.Kernel/KernelEngine.Kernel.csproj" />
    <PackageReference Include="Serilog" Version="4.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.*" />
  </ItemGroup>

</Project>
