<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup Condition="'$(UsePackageReferences)' != 'true'">
    <ProjectReference Include="..\KernelEngine.Core\KernelEngine.Core.csproj" />
    <ProjectReference Include="..\Native\KernelEngine.ShaderCompiler.Native\KernelEngine.ShaderCompiler.Native.csproj" />
    <ProjectReference Include="..\Native\KernelEngine.Core.Native\KernelEngine.Core.Native.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UsePackageReferences)' == 'true'">
    <PackageReference Include="KernelEngine.Core" Version="$(Version)" />
    <PackageReference Include="KernelEngine.ShaderCompiler.Native" Version="$(Version)" />
    <PackageReference Include="KernelEngine.Core.Native" Version="$(Version)" />
  </ItemGroup>

</Project>
