<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KernelEngine.Core\KernelEngine.Core.csproj" />
    <ProjectReference Include="..\Native\KernelEngine.ShaderCompiler.Native\KernelEngine.ShaderCompiler.Native.csproj" />
    <ProjectReference Include="..\Native\KernelEngine.Core.Native\KernelEngine.Core.Native.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
