set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_ENV_PASSTHROUGH_UNTRACKED PATH ZIG_LOCAL_CACHE_DIR)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/zig-mingw-toolchain.cmake")

set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DASSIMP_BUILD_USE_CCACHE=OFF)
