// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using System.Runtime.InteropServices;

namespace KernelEngine.Framework;

/// <summary>Scene-wide ambient light node. First entity with this component wins.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct AmbientLightComponent
{
    /// <summary>The name this component is registered under, which is its only identity across languages. Derived from the struct the ABI declares, so a caller naming the component and the storage holding it cannot come to disagree.</summary>
    public const string Name = "ambient_light";

    public Vector3 Color;

    /// <summary>The value every <c>[default:]</c> field of <c>ke_ambient_light_component</c> declares. A zero-initialized instance is not the same thing: zero is a value the ABI reads as itself, so a field whose neutral value is not zero has to be seeded.</summary>
    public static AmbientLightComponent Default => new()
    {
        Color = new Vector3(0.05f, 0.05f, 0.05f),
    };
}
