// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;

namespace KernelEngine.Framework;

/// <summary>Scene node that drives the per-frame view/projection. The first entity with a Camera in the ECS becomes the active camera.</summary>
[GeneratedNodeComponent(typeof(CameraComponent), "camera")]
public partial class Camera : Node3D
{
    public Camera()
    {
        _generatedState0 = CameraComponent.Default;
    }

    [NativeField("Fov", Component = typeof(CameraComponent))]
    public partial float Fov { get; set; }

    [NativeField("NearPlane", Component = typeof(CameraComponent))]
    public partial float NearPlane { get; set; }

    [NativeField("FarPlane", Component = typeof(CameraComponent))]
    public partial float FarPlane { get; set; }

    [NativeField("OrthographicSize", Component = typeof(CameraComponent))]
    public partial float OrthographicSize { get; set; }

    [NativeField("Orthographic", Component = typeof(CameraComponent))]
    public partial bool Orthographic { get; set; }

    [NativeField("CullMask", Component = typeof(CameraComponent))]
    public partial uint CullMask { get; set; }
}