// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Runtime.InteropServices;

namespace KernelEngine.Framework;

/// <summary>Scene node that drives the per-frame view/projection. The first entity with a Camera in the ECS becomes the active camera.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct CameraComponent
{
    /// <summary>The name this component is registered under, which is its only identity across languages. Derived from the struct the ABI declares, so a caller naming the component and the storage holding it cannot come to disagree.</summary>
    public const string Name = "camera";

    public float Fov;
    public float NearPlane;
    public float FarPlane;
    public float OrthographicSize;
    public byte Orthographic;
    public uint CullMask;

    /// <summary>The value every <c>[default:]</c> field of <c>ke_camera_component</c> declares. A zero-initialized instance is not the same thing: zero is a value the ABI reads as itself, so a field whose neutral value is not zero has to be seeded.</summary>
    public static CameraComponent Default => new()
    {
        Fov = 60f,
        NearPlane = 0.1f,
        FarPlane = 1000f,
        OrthographicSize = 5f,
        CullMask = 4294967295,
    };
}
