// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using System.Runtime.InteropServices;

namespace KernelEngine.Framework;

/// <summary>Directional light node. Init properties feed the per-frame light state the renderer consumes.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct DirectionalLightComponent
{
    /// <summary>The name this component is registered under, which is its only identity across languages. Derived from the struct the ABI declares, so a caller naming the component and the storage holding it cannot come to disagree.</summary>
    public const string Name = "directional_light";

    public Vector3 Direction;
    /// <summary>Linear RGB.</summary>
    public Vector3 Color;
    public float Intensity;
    public Vector3 Ambient;

    /// <summary>The value every <c>[default:]</c> field of <c>ke_directional_light_component</c> declares. A zero-initialized instance is not the same thing: zero is a value the ABI reads as itself, so a field whose neutral value is not zero has to be seeded.</summary>
    public static DirectionalLightComponent Default => new()
    {
        Direction = new Vector3(0.2f, 1f, 0.5f),
        Color = new Vector3(1f, 1f, 1f),
        Intensity = 1f,
        Ambient = new Vector3(0.2f, 0.2f, 0.2f),
    };
}
