// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace KernelEngine.Framework;

/// <summary>A screen-space text label. Text/anchor/offset/color/font are the caller's input; glyph_count and glyphs[] are output, written each KE_PHASE_UPDATE tick by the "render.ui.labels" system and read by "render.ui" (KE_PHASE_RENDER) to draw them — the same sim-writes/render-reads split every other render component uses, so there is no per-glyph entity, no CPU-side accumulator, no pool to grow or reuse.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct LabelComponent
{
    /// <summary>The name this component is registered under, which is its only identity across languages. Derived from the struct the ABI declares, so a caller naming the component and the storage holding it cannot come to disagree.</summary>
    public const string Name = "label";

    /// <summary>Elements <c>Font</c> has room for, as the ABI fixes it. A caller composing the field from a set it does not control checks this first -- there is no element past it to write.</summary>
    public const int FontCapacity = 128;

    /// <summary>Elements <c>Text</c> has room for, as the ABI fixes it. A caller composing the field from a set it does not control checks this first -- there is no element past it to write.</summary>
    public const int TextCapacity = 256;

    /// <summary>Elements <c>Glyphs</c> has room for, as the ABI fixes it. A caller composing the field from a set it does not control checks this first -- there is no element past it to write.</summary>
    public const int GlyphsCapacity = 256;

    /// <summary>Font file to draw with, baked by the "render.label.resolve" system.</summary>
    public FontBuffer Font;
    public float FontSize;
    /// <summary>Resolved from `font`.</summary>
    public KernelEngine.Render.FontHandle FontHandle;
    /// <summary>Anchor in normalized [0..1] of the backbuffer. (0,0) = top-left, (1,1) = bottom-right.</summary>
    public Vector2 Anchor;
    /// <summary>Pixel offset applied AFTER anchor positioning.</summary>
    public Vector2 Offset;
    public Vector4 Color;
    public TextBuffer Text;
    /// <summary>Written by "render.ui.labels"; a node authoring it would have the value overwritten on the next tick.</summary>
    public uint GlyphCount;
    /// <summary>Shaped output, see glyph_count.</summary>
    public GlyphsBuffer Glyphs;

    /// <summary>The value every <c>[default:]</c> field of <c>ke_label_component</c> declares. A zero-initialized instance is not the same thing: zero is a value the ABI reads as itself, so a field whose neutral value is not zero has to be seeded.</summary>
    public static LabelComponent Default => new()
    {
        FontSize = 32f,
        Color = new Vector4(1f, 1f, 1f, 1f),
    };

    /// <summary>The <c>char[128]</c> of <c>Font</c> laid out inline, so the field occupies the bytes the ABI reads it from.</summary>
    [InlineArray(FontCapacity)]
    public partial struct FontBuffer
    {
        public sbyte Element;
    }

    /// <summary>The <c>char[256]</c> of <c>Text</c> laid out inline, so the field occupies the bytes the ABI reads it from.</summary>
    [InlineArray(TextCapacity)]
    public partial struct TextBuffer
    {
        public sbyte Element;
    }

    /// <summary>The <c>ke_label_glyph_quad[256]</c> of <c>Glyphs</c> laid out inline, so the field occupies the bytes the ABI reads it from.</summary>
    [InlineArray(GlyphsCapacity)]
    public partial struct GlyphsBuffer
    {
        public LabelGlyphQuad Element;
    }
}
