// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Runtime.InteropServices;

namespace KernelEngine.Framework;

/// <summary>One shaped glyph: the screen-space rectangle it draws to and the atlas rectangle it samples from.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct LabelGlyphQuad
{
    public float DstX;
    public float DstY;
    public float DstW;
    public float DstH;
    public float U0;
    public float V0;
    public float U1;
    public float V1;
}
