// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace KernelEngine.Framework;

/// <summary>Renders a mesh with a material. `mesh`/`material` double as output: the native "render.mesh.resolve" system (KE_PHASE_UPDATE, src/zig/render/service/src/mesh_resolve.zig) fills them whenever `primitive` names a known shape and/or the surface fields below have not already resolved to a valid handle. A caller holding real handles just writes them and leaves `primitive` empty — the resolve system only acts where a handle is still invalid, so the two paths never conflict.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct MeshComponent
{
    /// <summary>The name this component is registered under, which is its only identity across languages. Derived from the struct the ABI declares, so a caller naming the component and the storage holding it cannot come to disagree.</summary>
    public const string Name = "mesh";

    /// <summary>Elements <c>Primitive</c> has room for, as the ABI fixes it. A caller composing the field from a set it does not control checks this first -- there is no element past it to write.</summary>
    public const int PrimitiveCapacity = 32;

    public KernelEngine.Render.MeshHandle Mesh;
    public KernelEngine.Render.MaterialHandle Material;
    /// <summary>Resolved by the scene loader's property-apply path into `mesh`; a node authoring it directly would have the value overwritten.</summary>
    public PrimitiveBuffer Primitive;
    public Vector4 BaseColor;
    public float Roughness;
    /// <summary>ke_alpha_mode.</summary>
    public uint AlphaMode;
    public float AlphaCutoff;
    public float Ior;
    public float DistortionStrength;
    public uint Layers;

    /// <summary>The value every <c>[default:]</c> field of <c>ke_mesh_component</c> declares. A zero-initialized instance is not the same thing: zero is a value the ABI reads as itself, so a field whose neutral value is not zero has to be seeded.</summary>
    public static MeshComponent Default => new()
    {
        BaseColor = new Vector4(1f, 1f, 1f, 1f),
        Roughness = 1f,
        AlphaMode = 0,
        AlphaCutoff = 0.5f,
        Ior = 1.5f,
        DistortionStrength = 0.05f,
        Layers = 1,
    };

    /// <summary>The <c>char[32]</c> of <c>Primitive</c> laid out inline, so the field occupies the bytes the ABI reads it from.</summary>
    [InlineArray(PrimitiveCapacity)]
    public partial struct PrimitiveBuffer
    {
        public sbyte Element;
    }
}
