// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using System.Runtime.InteropServices;

namespace KernelEngine.Framework;

/// <summary>Point light node — emits light in all directions from this entity's world position.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct PointLightComponent
{
    /// <summary>The name this component is registered under, which is its only identity across languages. Derived from the struct the ABI declares, so a caller naming the component and the storage holding it cannot come to disagree.</summary>
    public const string Name = "point_light";

    /// <summary>Linear RGB.</summary>
    public Vector3 Color;
    public float Intensity;
    public float Radius;

    /// <summary>The value every <c>[default:]</c> field of <c>ke_point_light_component</c> declares. A zero-initialized instance is not the same thing: zero is a value the ABI reads as itself, so a field whose neutral value is not zero has to be seeded.</summary>
    public static PointLightComponent Default => new()
    {
        Color = new Vector3(1f, 1f, 1f),
        Intensity = 1f,
        Radius = 10f,
    };
}
