// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using System.Runtime.InteropServices;

namespace KernelEngine.Framework;

/// <summary>Spot light node — emits a cone of light from this entity's world position.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct SpotLightComponent
{
    /// <summary>The name this component is registered under, which is its only identity across languages. Derived from the struct the ABI declares, so a caller naming the component and the storage holding it cannot come to disagree.</summary>
    public const string Name = "spot_light";

    public Vector3 Direction;
    /// <summary>Linear RGB.</summary>
    public Vector3 Color;
    public float Intensity;
    public float Range;
    public float InnerAngle;
    public float OuterAngle;

    /// <summary>The value every <c>[default:]</c> field of <c>ke_spot_light_component</c> declares. A zero-initialized instance is not the same thing: zero is a value the ABI reads as itself, so a field whose neutral value is not zero has to be seeded.</summary>
    public static SpotLightComponent Default => new()
    {
        Direction = new Vector3(0f, -1f, 0f),
        Color = new Vector3(1f, 1f, 1f),
        Intensity = 1f,
        Range = 20f,
        InnerAngle = 25f,
        OuterAngle = 35f,
    };
}
