// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;

namespace KernelEngine.Framework;

/// <summary>Spot light node — emits a cone of light from this entity's world position.</summary>
[GeneratedNodeComponent(typeof(SpotLightComponent), "spot_light")]
public partial class SpotLight : Node3D
{
    public SpotLight()
    {
        _generatedState0 = SpotLightComponent.Default;
    }

    [NativeField("Direction", Component = typeof(SpotLightComponent))]
    public partial Vector3 Direction { get; set; }

    /// <summary>Linear RGB.</summary>
    [NativeField("Color", Component = typeof(SpotLightComponent))]
    public partial Vector3 Color { get; set; }

    [NativeField("Intensity", Component = typeof(SpotLightComponent))]
    public partial float Intensity { get; set; }

    [NativeField("Range", Component = typeof(SpotLightComponent))]
    public partial float Range { get; set; }

    [NativeField("InnerAngle", Component = typeof(SpotLightComponent))]
    public partial float InnerAngle { get; set; }

    [NativeField("OuterAngle", Component = typeof(SpotLightComponent))]
    public partial float OuterAngle { get; set; }
}