// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;

namespace KernelEngine.Framework;

/// <summary>A textured quad in the plane, resolved into geometry and a material by the "render.sprite2d.resolve" system.</summary>
[GeneratedNodeComponent(typeof(Sprite2dComponent), "sprite2d")]
public partial class Sprite2D : Node2D
{
    public Sprite2D()
    {
        _generatedState0 = Sprite2dComponent.Default;
    }

    /// <summary>Image to sample. Empty draws the plain tinted quad.</summary>
    [NativeField("Texture", Component = typeof(Sprite2dComponent))]
    public partial string Texture { get; set; }

    [NativeField("Region", Component = typeof(Sprite2dComponent))]
    public partial Vector4 Region { get; set; }

    [NativeField("Size", Component = typeof(Sprite2dComponent))]
    public partial Vector2 Size { get; set; }

    [NativeField("Pivot", Component = typeof(Sprite2dComponent))]
    public partial Vector2 Pivot { get; set; }

    [NativeField("FlipH", Component = typeof(Sprite2dComponent))]
    public partial bool FlipH { get; set; }

    [NativeField("FlipV", Component = typeof(Sprite2dComponent))]
    public partial bool FlipV { get; set; }

    [NativeField("Color", Component = typeof(Sprite2dComponent))]
    public partial Vector4 Color { get; set; }

    /// <summary>ke_alpha_mode.</summary>
    [NativeField("AlphaMode", Component = typeof(Sprite2dComponent))]
    public partial uint AlphaMode { get; set; }

    [NativeField("AlphaCutoff", Component = typeof(Sprite2dComponent))]
    public partial float AlphaCutoff { get; set; }

    [NativeField("Attached", Component = typeof(Sprite2dComponent))]
    public partial bool Attached { get; set; }
}