// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using Microsoft.Extensions.DependencyInjection;

namespace KernelEngine.Framework;

/// <summary>Registers every node type generated for this domain.</summary>
public static class UiComponentsNodeTypes
{
    /// <summary>Registers this domain's node types with the scene node registry.</summary>
    public static IServiceCollection AddUiComponentsNodeTypes(this IServiceCollection services)
    {
        services.AddNodeType<Label>();
        return services;
    }
}