#ifndef KERNEL_ENGINE_INPUT_KEY_H_
#define KERNEL_ENGINE_INPUT_KEY_H_

// Keyboard key codes. Values mirror the GLFW key constants — kept identical so
// callers can pass either a ke_key or a raw int through the kernel's input
// snapshot without converting. Indices into ke_input_snapshot.keys_down[8].
//
// The managed-side mirror lives in KernelEngine.Kernel.Abstractions/Input/Key.cs.

#ifdef __cplusplus
extern "C"
{
#endif

    typedef enum ke_key
    {
        KE_KEY_UNKNOWN         = -1,
        KE_KEY_SPACE           = 32,
        KE_KEY_APOSTROPHE      = 39,
        KE_KEY_COMMA           = 44,
        KE_KEY_MINUS           = 45,
        KE_KEY_PERIOD          = 46,
        KE_KEY_SLASH           = 47,
        KE_KEY_NUMBER_0        = 48,
        KE_KEY_NUMBER_1        = 49,
        KE_KEY_NUMBER_2        = 50,
        KE_KEY_NUMBER_3        = 51,
        KE_KEY_NUMBER_4        = 52,
        KE_KEY_NUMBER_5        = 53,
        KE_KEY_NUMBER_6        = 54,
        KE_KEY_NUMBER_7        = 55,
        KE_KEY_NUMBER_8        = 56,
        KE_KEY_NUMBER_9        = 57,
        KE_KEY_SEMICOLON       = 59,
        KE_KEY_EQUAL           = 61,
        KE_KEY_A               = 65,
        KE_KEY_B               = 66,
        KE_KEY_C               = 67,
        KE_KEY_D               = 68,
        KE_KEY_E               = 69,
        KE_KEY_F               = 70,
        KE_KEY_G               = 71,
        KE_KEY_H               = 72,
        KE_KEY_I               = 73,
        KE_KEY_J               = 74,
        KE_KEY_K               = 75,
        KE_KEY_L               = 76,
        KE_KEY_M               = 77,
        KE_KEY_N               = 78,
        KE_KEY_O               = 79,
        KE_KEY_P               = 80,
        KE_KEY_Q               = 81,
        KE_KEY_R               = 82,
        KE_KEY_S               = 83,
        KE_KEY_T               = 84,
        KE_KEY_U               = 85,
        KE_KEY_V               = 86,
        KE_KEY_W               = 87,
        KE_KEY_X               = 88,
        KE_KEY_Y               = 89,
        KE_KEY_Z               = 90,
        KE_KEY_LEFT_BRACKET    = 91,
        KE_KEY_BACKSLASH       = 92,
        KE_KEY_RIGHT_BRACKET   = 93,
        KE_KEY_GRAVE_ACCENT    = 96,
        KE_KEY_WORLD_1         = 161,
        KE_KEY_WORLD_2         = 162,
        KE_KEY_ESCAPE          = 256,
        KE_KEY_ENTER           = 257,
        KE_KEY_TAB             = 258,
        KE_KEY_BACKSPACE       = 259,
        KE_KEY_INSERT          = 260,
        KE_KEY_DELETE          = 261,
        KE_KEY_RIGHT           = 262,
        KE_KEY_LEFT            = 263,
        KE_KEY_DOWN            = 264,
        KE_KEY_UP              = 265,
        KE_KEY_PAGE_UP         = 266,
        KE_KEY_PAGE_DOWN       = 267,
        KE_KEY_HOME            = 268,
        KE_KEY_END             = 269,
        KE_KEY_CAPS_LOCK       = 280,
        KE_KEY_SCROLL_LOCK     = 281,
        KE_KEY_NUM_LOCK        = 282,
        KE_KEY_PRINT_SCREEN    = 283,
        KE_KEY_PAUSE           = 284,
        KE_KEY_F1              = 290,
        KE_KEY_F2              = 291,
        KE_KEY_F3              = 292,
        KE_KEY_F4              = 293,
        KE_KEY_F5              = 294,
        KE_KEY_F6              = 295,
        KE_KEY_F7              = 296,
        KE_KEY_F8              = 297,
        KE_KEY_F9              = 298,
        KE_KEY_F10             = 299,
        KE_KEY_F11             = 300,
        KE_KEY_F12             = 301,
        KE_KEY_F13             = 302,
        KE_KEY_F14             = 303,
        KE_KEY_F15             = 304,
        KE_KEY_F16             = 305,
        KE_KEY_F17             = 306,
        KE_KEY_F18             = 307,
        KE_KEY_F19             = 308,
        KE_KEY_F20             = 309,
        KE_KEY_F21             = 310,
        KE_KEY_F22             = 311,
        KE_KEY_F23             = 312,
        KE_KEY_F24             = 313,
        KE_KEY_F25             = 314,
        KE_KEY_KEYPAD_0        = 320,
        KE_KEY_KEYPAD_1        = 321,
        KE_KEY_KEYPAD_2        = 322,
        KE_KEY_KEYPAD_3        = 323,
        KE_KEY_KEYPAD_4        = 324,
        KE_KEY_KEYPAD_5        = 325,
        KE_KEY_KEYPAD_6        = 326,
        KE_KEY_KEYPAD_7        = 327,
        KE_KEY_KEYPAD_8        = 328,
        KE_KEY_KEYPAD_9        = 329,
        KE_KEY_KEYPAD_DECIMAL  = 330,
        KE_KEY_KEYPAD_DIVIDE   = 331,
        KE_KEY_KEYPAD_MULTIPLY = 332,
        KE_KEY_KEYPAD_SUBTRACT = 333,
        KE_KEY_KEYPAD_ADD      = 334,
        KE_KEY_KEYPAD_ENTER    = 335,
        KE_KEY_KEYPAD_EQUAL    = 336,
        KE_KEY_SHIFT_LEFT      = 340,
        KE_KEY_CONTROL_LEFT    = 341,
        KE_KEY_ALT_LEFT        = 342,
        KE_KEY_SUPER_LEFT      = 343,
        KE_KEY_SHIFT_RIGHT     = 344,
        KE_KEY_CONTROL_RIGHT   = 345,
        KE_KEY_ALT_RIGHT       = 346,
        KE_KEY_SUPER_RIGHT     = 347,
        KE_KEY_MENU            = 348,
    } ke_key;

    typedef enum ke_mouse_button
    {
        KE_MOUSE_BUTTON_LEFT   = 0,
        KE_MOUSE_BUTTON_RIGHT  = 1,
        KE_MOUSE_BUTTON_MIDDLE = 2,
    } ke_mouse_button;

#ifdef __cplusplus
}
#endif

#endif // KERNEL_ENGINE_INPUT_KEY_H_
