// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Common.Native;
using KernelEngine.Ecs;

namespace KernelEngine.Framework;

/// <summary>An entity's authored 3D pose, read and written as one unit.</summary>
[GeneratedNodeComponent(typeof(ke_transform_component), "transform")]
public partial class Node3D : Node
{
    public Node3D()
    {
        _generatedState0 = global::System.Runtime.CompilerServices.Unsafe.BitCast<KernelEngine.Ecs.TransformComponent, ke_transform_component>(KernelEngine.Ecs.TransformComponent.Identity);
    }

    [NativeWhole(Component = typeof(ke_transform_component))]
    public partial KernelEngine.Ecs.TransformComponent LocalTransform { get; set; }
}