// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Ecs;

namespace KernelEngine.Framework;

/// <summary>An entity's authored 2D pose, read and written as one unit.</summary>
[GeneratedNodeComponent(typeof(Transform2dComponent), "transform2d")]
public partial class Node2D : Node
{
    public Node2D()
    {
        _generatedState0 = Transform2dComponent.Default;
    }

    [NativeField("Position", Component = typeof(Transform2dComponent))]
    public partial Vector2 Position { get; set; }

    /// <summary>Radians, CCW positive; a scene authors degrees.</summary>
    [NativeField("Rotation", Component = typeof(Transform2dComponent))]
    public partial float Rotation { get; set; }

    [NativeField("Scale", Component = typeof(Transform2dComponent))]
    public partial Vector2 Scale { get; set; }

    /// <summary>Where the plane sits along Z.</summary>
    [NativeField("Depth", Component = typeof(Transform2dComponent))]
    public partial float Depth { get; set; }
}