// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Common.Native;

namespace KernelEngine.Framework;

/// <summary>Per-entity 3D transform component. Read/written as one atomic unit (position, rotation, and scale are meaningless set independently mid-write) — kabic's [whole:] tag maps the whole struct to a single bit-cast property instead of one property per field. world_matrix is derived output, recomputed from the hierarchy each frame; it rides along in the same atomic struct rather than being a separate field a caller could plausibly author.</summary>
[GeneratedNodeComponent(typeof(ke_transform_component), "transform")]
public partial class Node3D : Node
{
    public Node3D()
    {
        _generatedState0 = global::System.Runtime.CompilerServices.Unsafe.BitCast<KernelEngine.Ecs.TransformComponent, ke_transform_component>(KernelEngine.Ecs.TransformComponent.Identity);
    }

    [NativeWhole]
    public partial KernelEngine.Ecs.TransformComponent LocalTransform { get; set; }
}