// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Common.Native;
using KernelEngine.Ecs;

namespace KernelEngine.Framework;

/// <summary>An entity's authored 2D pose, read and written as one unit.</summary>
[GeneratedNodeComponent(typeof(ke_transform2d_component), "transform2d")]
public partial class Node2D : Node
{
    public Node2D()
    {
        _generatedState0.scale = new ke_vec2 { x = 1f, y = 1f };
    }

    [NativeField("position", Component = typeof(ke_transform2d_component))]
    public partial Vector2 Position { get; set; }

    /// <summary>Radians, CCW positive; a scene authors degrees.</summary>
    [NativeField("rotation", Component = typeof(ke_transform2d_component))]
    public partial float Rotation { get; set; }

    [NativeField("scale", Component = typeof(ke_transform2d_component))]
    public partial Vector2 Scale { get; set; }

    /// <summary>Where the plane sits along Z.</summary>
    [NativeField("depth", Component = typeof(ke_transform2d_component))]
    public partial float Depth { get; set; }
}