// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using System.Runtime.InteropServices;

namespace KernelEngine.Framework;

/// <summary>An entity's authored 2D pose, read and written as one unit.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct Transform2dComponent
{
    /// <summary>The name this component is registered under, which is its only identity across languages. Derived from the struct the ABI declares, so a caller naming the component and the storage holding it cannot come to disagree.</summary>
    public const string Name = "transform2d";

    public Vector2 Position;
    /// <summary>Radians, CCW positive; a scene authors degrees.</summary>
    public float Rotation;
    public Vector2 Scale;
    /// <summary>Where the plane sits along Z.</summary>
    public float Depth;

    /// <summary>The value every <c>[default:]</c> field of <c>ke_transform2d_component</c> declares. A zero-initialized instance is not the same thing: zero is a value the ABI reads as itself, so a field whose neutral value is not zero has to be seeded.</summary>
    public static Transform2dComponent Default => new()
    {
        Scale = new Vector2(1f, 1f),
    };
}
