// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using System.Runtime.InteropServices;

namespace KernelEngine.Framework;

/// <summary>An entity's authored 3D pose.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct TransformComponent
{
    /// <summary>The name this component is registered under, which is its only identity across languages. Derived from the struct the ABI declares, so a caller naming the component and the storage holding it cannot come to disagree.</summary>
    public const string Name = "transform";

    public Vector3 Position;
    public Quaternion Rotation;
    public Vector3 Scale;

    /// <summary>The value every <c>[default:]</c> field of <c>ke_transform_component</c> declares. A zero-initialized instance is not the same thing: zero is a value the ABI reads as itself, so a field whose neutral value is not zero has to be seeded.</summary>
    public static TransformComponent Default => new()
    {
        Rotation = new Quaternion(0f, 0f, 0f, 1f),
        Scale = new Vector3(1f, 1f, 1f),
    };
}
