-- AUTO-GENERATED by scripts/generate_lua_bindings.py. Do not edit by
-- hand: regenerate after changing any C header in the source tree.
--
-- Source headers (preprocessed via `clang -E`, filtered to
-- kernel_engine/... declarations, stripped of __declspec/__attribute__
-- decorations and `static inline` function bodies):
--   kernel_engine/kernel/context/allocator.h
--   kernel_engine/kernel/common/handles.h
--   kernel_engine/kernel/common/math.h
--   kernel_engine/kernel/common/thread_name.h
--   kernel_engine/kernel/logger/logger.h
--   kernel_engine/kernel/input/snapshot.h
--   kernel_engine/kernel/input/input.h
--   kernel_engine/kernel/render/light.h
--   kernel_engine/kernel/render/material.h
--   kernel_engine/kernel/render/mesh.h
--   kernel_engine/kernel/render/texture.h
--   kernel_engine/kernel/render/render.h
--   kernel_engine/kernel/engine/frame.h
--   kernel_engine/kernel/engine/frame_packet.h
--   kernel_engine/kernel/world/ecs.h
--   kernel_engine/kernel/world/components.h
--   kernel_engine/kernel/world/system.h
--   kernel_engine/kernel/world/world.h
--   kernel_engine/framework/scene_tree.h
--   kernel_engine/framework/input_actions.h
--   kernel_engine/framework/mesh_shape.h
--   kernel_engine/framework/camera_render_system.h
--   kernel_engine/framework/mesh_render_system.h
--   kernel_engine/framework/light_render_system.h
--   kernel_engine/framework/mesh_asset_system.h
--   kernel_engine/kernel/world/variant.h
--   kernel_engine/framework/scene_loader.h
--   kernel_engine/render/bgfx/bgfx_render.h
--   kernel_engine/window/glfw/glfw_window.h

local ffi = require("ffi")

ffi.cdef[[
typedef enum ke_result
    {
        KE_OK = 0,

        KE_ERROR = 1,
        KE_ERROR_OUT_OF_MEMORY = 2,
        KE_ERROR_INVALID_ARGUMENT = 3,
        KE_ERROR_NOT_FOUND = 4,
        KE_ERROR_ALREADY_EXISTS = 5,
        KE_ERROR_NOT_INITIALIZED = 6,
        KE_ERROR_NOT_SUPPORTED = 7,

        KE_ERROR_IO = 100,
        KE_ERROR_WINDOW = 200,
        KE_ERROR_RENDER = 300,
        KE_ERROR_GPU_FATAL = 301,

    } ke_result;
    typedef uint8_t ke_bool;

    struct ke_logger;

    typedef struct ke_allocator
    {
        void *handle;
        void (*destroy)(struct ke_allocator *self);

        void *(*alloc)(struct ke_allocator *self, size_t size, size_t alignment);
        void (*free)(struct ke_allocator *self, void *ptr);
        void *(*realloc)(struct ke_allocator *self, void *ptr, size_t new_size);
        void (*reset)(struct ke_allocator *self);
    } ke_allocator;

           ke_allocator *ke_allocator_malloc_create(void);

           ke_allocator *ke_allocator_arena_create(size_t fixed_capacity);

    typedef struct ke_allocator_stats
    {
        size_t total_allocated;
        size_t total_freed;
        size_t active_bytes;
        uint32_t active_allocs;
    } ke_allocator_stats;

           ke_allocator *ke_allocator_proxy_create(ke_allocator *inner, const char *name);

           ke_result ke_allocator_proxy_get_stats(ke_allocator *proxy, ke_allocator_stats *out_stats);

           void ke_allocator_proxy_report(ke_allocator *proxy, struct ke_logger *logger);
    typedef struct ke_mesh_handle
    {
        uint32_t idx;
    } ke_mesh_handle;

    typedef struct ke_texture_handle
    {
        uint32_t idx;
    } ke_texture_handle;

    typedef struct ke_material_handle
    {
        uint32_t idx;
    } ke_material_handle;

    typedef struct ke_cubemap_handle
    {
        uint32_t idx;
    } ke_cubemap_handle;

    typedef struct ke_shadow_map_handle
    {
        uint32_t idx;
    } ke_shadow_map_handle;
    

    

    

    

    

    typedef struct ke_vec2
    {
        float x, y;
    } ke_vec2;

    typedef struct ke_vec3
    {
        float x, y, z;
    } ke_vec3;

    typedef struct ke_vec4
    {
        float x, y, z, w;
    } ke_vec4;

    typedef struct ke_quat
    {
        float x, y, z, w;
    } ke_quat;

    typedef struct ke_mat4
    {
        float m[16];
    } ke_mat4;

    typedef struct ke_transform
    {
        ke_vec3 position;
        ke_quat rotation;
        ke_vec3 scale;
    } ke_transform;

    

    
           void ke_thread_set_current_name(const char *name);

           const char *ke_thread_get_current_name(void);

           void ke_thread_assert_current(const char *expected_name);

    typedef enum ke_log_level
    {
        KE_LOG_LEVEL_TRACE = 0,
        KE_LOG_LEVEL_DEBUG = 1,
        KE_LOG_LEVEL_INFO = 2,
        KE_LOG_LEVEL_WARNING = 3,
        KE_LOG_LEVEL_ERROR = 4,
        KE_LOG_LEVEL_CRITICAL = 5
    } ke_log_level;

           const char *ke_log_level_to_string(int32_t level);

typedef struct ke_logger ke_logger;

    typedef struct ke_log_event
    {
        int32_t level;
        const char *tag;
        const char *message;
    } ke_log_event;

    typedef struct ke_logger_sink
    {
        void *handle;
        int32_t min_level;
        void (*log)(struct ke_logger_sink *self, const ke_log_event *event);
        void (*flush)(struct ke_logger_sink *self);
        void (*destroy)(struct ke_logger_sink *self);
    } ke_logger_sink;

    typedef struct ke_logger
    {
        void *handle;
        int32_t runtime_limit;

        struct ke_allocator *allocator;

        void (*destroy)(struct ke_logger *self);

        void (*log)(struct ke_logger *self, const ke_log_event *event);

        void (*flush)(struct ke_logger *self);

        ke_result (*add_sink)(struct ke_logger *self, ke_logger_sink sink);

    } ke_logger;

           ke_result ke_logger_create(ke_allocator *allocator, ke_logger **out_logger);
    typedef struct ke_input_snapshot
    {

        uint64_t keys_down[8];

        uint64_t keys_pressed[8];

        uint64_t keys_released[8];

        float mouse_x;
        float mouse_y;
        float mouse_dx;
        float mouse_dy;
        float scroll_dx;
        float scroll_dy;

        uint32_t mouse_buttons_down;
        uint32_t mouse_buttons_pressed;
        uint32_t mouse_buttons_released;

    } ke_input_snapshot;

    typedef enum ke_input_event_kind
    {
        KE_INPUT_EVENT_NONE = 0,
        KE_INPUT_EVENT_KEY_DOWN = 1,
        KE_INPUT_EVENT_KEY_UP = 2,
        KE_INPUT_EVENT_MOUSE_BUTTON_DOWN = 3,
        KE_INPUT_EVENT_MOUSE_BUTTON_UP = 4,
        KE_INPUT_EVENT_MOUSE_MOVE = 5,
        KE_INPUT_EVENT_MOUSE_SCROLL = 6,
    } ke_input_event_kind;
    typedef struct ke_input_event
    {
        ke_input_event_kind kind;
        int32_t code;
        float x;
        float y;
    } ke_input_event;
    typedef struct ke_input
    {
        void *handle;

        struct ke_allocator *allocator;
        struct ke_logger *logger;

        void (*destroy)(struct ke_input *self);

        ke_result (*update)(struct ke_input *self);

        ke_bool (*is_key_pressed)(struct ke_input *self, int32_t key);
        ke_bool (*is_key_released)(struct ke_input *self, int32_t key);
        ke_bool (*is_key_down)(struct ke_input *self, int32_t key);

        void (*get_snapshot)(struct ke_input *self, ke_input_snapshot *out_snapshot);

        uint32_t (*drain_events)(struct ke_input *self, ke_input_event *out_buf, uint32_t capacity);

        void (*on_key)(struct ke_input *self, int32_t key, int32_t action);
        void (*on_mouse_move)(struct ke_input *self, float x, float y);
        void (*on_mouse_button)(struct ke_input *self, int32_t button, int32_t action);
        void (*on_mouse_scroll)(struct ke_input *self, float dx, float dy);

    } ke_input;

           ke_result ke_input_create(struct ke_allocator *allocator, struct ke_logger *logger, ke_input **out_input);
    typedef struct ke_directional_light
    {
        float dir_x, dir_y, dir_z;
        float r, g, b;
        float intensity;
    } ke_directional_light;

    typedef struct ke_point_light
    {
        float pos_x, pos_y, pos_z;
        float radius;
        float r, g, b;
        float intensity;
    } ke_point_light;

    typedef struct ke_spot_light
    {
        float pos_x, pos_y, pos_z;
        float range;
        float dir_x, dir_y, dir_z;
        float inner_angle;
        float r, g, b;
        float intensity;
        float outer_angle;
    } ke_spot_light;

    typedef struct ke_material
    {
        float r, g, b, a;
        ke_texture_handle albedo;
        float metallic;
        float roughness;
        ke_texture_handle normal_map;
    } ke_material;
    typedef struct ke_vertex
    {
        float x, y, z;
        float nx, ny, nz;
        float u, v;
        float tx, ty, tz;
        float tw;
    } ke_vertex;
    struct ke_frame_packet;
    struct ke_render_graph;
    struct ke_allocator;

    typedef struct ke_ndc_convention
    {
        ke_bool z_zero_to_one;
        ke_bool y_flip;
        ke_bool left_handed;
    } ke_ndc_convention;

    typedef struct ke_cluster_config
    {
        uint32_t grid_x;
        uint32_t grid_y;
        uint32_t grid_z;
        uint32_t max_lights_per_cluster;
        uint32_t max_total_lights;
    } ke_cluster_config;

    typedef struct ke_render
    {
        void *handle;
        void (*destroy)(struct ke_render *self);

        ke_result (*on_initialize)(struct ke_render *self);
        ke_result (*on_shutdown)(struct ke_render *self);

        ke_result (*set_orthographic)(struct ke_render *self, ke_bool enabled);
        ke_result (*clear_color)(struct ke_render *self, float r, float g, float b, float a);

        ke_result (*frame)(struct ke_render *self);
        ke_result (*set_view_transform)(struct ke_render *self, const ke_mat4 *view, const ke_mat4 *proj);

        ke_ndc_convention (*get_ndc_convention)(struct ke_render *self);

        ke_result (*create_mesh)(struct ke_render *self,
                                 const ke_vertex *vertices, uint32_t vertex_count,
                                 const uint16_t *indices, uint32_t index_count,
                                 ke_mesh_handle *out_handle);

        ke_result (*destroy_mesh)(struct ke_render *self, ke_mesh_handle handle);

        ke_result (*create_material)(struct ke_render *self,
                                     const ke_material *mat,
                                     ke_material_handle *out_handle);

        ke_result (*destroy_material)(struct ke_render *self, ke_material_handle handle);

        ke_result (*submit_mesh)(struct ke_render *self,
                                 ke_mesh_handle mesh, ke_material_handle material,
                                 const ke_mat4 *transform);

        ke_result (*create_texture_rgba)(struct ke_render *self,
                                         uint32_t width, uint32_t height,
                                         const uint8_t *pixels,
                                         ke_texture_handle *out_handle);

        ke_result (*destroy_texture)(struct ke_render *self, ke_texture_handle handle);

        ke_result (*set_directional_light)(struct ke_render *self, const ke_directional_light *light);
        ke_result (*set_ambient_light)(struct ke_render *self, float r, float g, float b);
        ke_result (*set_camera_pos)(struct ke_render *self, float x, float y, float z);

        ke_result (*create_cubemap_rgba)(struct ke_render *self,
                                         uint32_t size,
                                         const uint8_t *data,
                                         ke_texture_handle *out_handle);

        ke_result (*submit_skybox)(struct ke_render *self, ke_texture_handle cubemap_handle);

        ke_result (*create_shadow_map)(struct ke_render *self, uint32_t width, uint32_t height,
                                       ke_shadow_map_handle *out_handle);

        ke_result (*destroy_shadow_map)(struct ke_render *self, ke_shadow_map_handle handle);

        ke_result (*begin_shadow_pass)(struct ke_render *self, ke_shadow_map_handle handle,
                                      const ke_mat4 *light_view, const ke_mat4 *light_proj);

        ke_result (*submit_mesh_shadow)(struct ke_render *self, ke_mesh_handle mesh,
                                        const ke_mat4 *transform);

        ke_result (*end_shadow_pass)(struct ke_render *self);

        ke_result (*set_shadow_map)(struct ke_render *self, ke_shadow_map_handle handle);

        ke_result (*set_tonemapping)(struct ke_render *self, ke_bool enabled,
                                     float exposure, float gamma);

        ke_result (*set_bloom)(struct ke_render *self, ke_bool enabled,
                               float threshold, float intensity);

        ke_result (*set_point_lights)(struct ke_render *self,
                                      const ke_point_light *lights, uint32_t count);

        ke_result (*set_spot_lights)(struct ke_render *self,
                                     const ke_spot_light *lights, uint32_t count);

        ke_result (*set_ssao)(struct ke_render *self, ke_bool enabled,
                              float radius, float bias, float strength);

        ke_result (*set_cluster_config)(struct ke_render *self, const ke_cluster_config *config);

        ke_result (*submit_ui_quad)(struct ke_render *self,
                                    ke_texture_handle texture,
                                    float dst_x, float dst_y, float dst_w, float dst_h,
                                    float src_u0, float src_v0, float src_u1, float src_v1,
                                    float r, float g, float b, float a);

        ke_result (*submit_packet)(struct ke_render *self, const struct ke_frame_packet *packet);

        const char *(*get_last_fatal_error)(struct ke_render *self);

        struct ke_render_graph *(*create_render_graph)(struct ke_render *self, struct ke_allocator *allocator);

        struct ke_render_graph *(*get_render_graph)(struct ke_render *self);

    } ke_render;
    typedef struct ke_frame
    {
        uint64_t frame_index;
        double delta_time;
        double total_time;
        const ke_input_snapshot *input;
    } ke_frame;
    typedef struct ke_draw_command {
        ke_mesh_handle mesh_handle;
        ke_material_handle material_handle;
        ke_mat4 transform;
    } ke_draw_command;

    typedef struct ke_ui_draw_command {
        ke_texture_handle texture;
        float dst_x, dst_y;
        float dst_w, dst_h;
        float src_u0, src_v0;
        float src_u1, src_v1;
        float color[4];
    } ke_ui_draw_command;

    typedef struct ke_frame_camera {
        ke_mat4 view;
        ke_mat4 proj;
        float pos_x, pos_y, pos_z;
    } ke_frame_camera;

    typedef struct ke_frame_shadow {
        ke_shadow_map_handle map_handle;
        ke_mat4 light_view;
        ke_mat4 light_proj;
    } ke_frame_shadow;

    typedef struct ke_frame_packet {
        uint64_t frame_number;

        ke_draw_command* draw_commands;
        uint32_t draw_count;
        uint32_t draw_capacity;

        float clear_color[4];
        float ambient_light[3];
        ke_shadow_map_handle active_shadow_map;

        ke_frame_shadow shadow;
        ke_draw_command* shadow_draw_commands;
        uint32_t shadow_draw_count;
        uint32_t shadow_draw_capacity;

        ke_directional_light dir_light;
        _Bool has_dir_light;

        ke_point_light* point_lights;
        uint32_t point_light_count;
        uint32_t point_light_capacity;

        ke_spot_light* spot_lights;
        uint32_t spot_light_count;
        uint32_t spot_light_capacity;

        ke_frame_camera camera;

        ke_texture_handle skybox_handle;
        _Bool has_skybox;

        _Bool ssao_enabled;
        float ssao_radius;
        float ssao_bias;
        float ssao_strength;

        _Bool tonemapping_enabled;
        float exposure;
        float gamma;

        _Bool bloom_enabled;
        float bloom_threshold;
        float bloom_intensity;

        ke_ui_draw_command* ui_draw_commands;
        uint32_t ui_draw_count;
        uint32_t ui_draw_capacity;

    } ke_frame_packet;
    typedef struct ke_frame_packet_params
    {
        struct ke_allocator *allocator;
        uint32_t draw_capacity;
        uint32_t shadow_draw_capacity;
        uint32_t point_light_capacity;
        uint32_t spot_light_capacity;
        uint32_t ui_draw_capacity;
    } ke_frame_packet_params;

           ke_result ke_frame_packet_create(const ke_frame_packet_params *params,
                                            ke_frame_packet **out_packet);
           void ke_frame_packet_destroy(struct ke_allocator *allocator,
                                             ke_frame_packet *packet);

           void ke_frame_packet_reset(ke_frame_packet *packet);

    typedef enum ke_variant_type
    {
        KE_VARIANT_NULL = 0,
        KE_VARIANT_BOOL = 1,
        KE_VARIANT_INT = 2,
        KE_VARIANT_FLOAT = 3,
        KE_VARIANT_STRING = 4,
        KE_VARIANT_VEC2 = 5,
        KE_VARIANT_VEC3 = 6,
        KE_VARIANT_VEC4 = 7,
        KE_VARIANT_QUAT = 8,
        KE_VARIANT_TABLE = 9,
    } ke_variant_type;

    struct ke_variant_table;
    typedef struct ke_variant
    {
        ke_variant_type type;
        union
        {
            _Bool b;
            int64_t i;
            double f;
            const char *s;
            ke_vec2 v2;
            ke_vec3 v3;
            ke_vec4 v4;
            ke_quat q;
            const struct ke_variant_table *t;
        };
    } ke_variant;
    typedef struct ke_variant_table_entry
    {
        const char *key;
        ke_variant value;
    } ke_variant_table_entry;

    typedef struct ke_variant_table
    {
        uint32_t count;
        const ke_variant_table_entry *entries;
    } ke_variant_table;

    

    

    

    

    

    

    

    

    

    

    typedef struct ke_component_field
    {
        const char *name;
        ke_variant_type type;
        uint32_t offset;
        uint32_t size;

    } ke_component_field;

    typedef uint64_t ke_entity;

    typedef uint32_t ke_component_id;

    typedef struct ke_ecs_registry
    {
        struct ke_allocator *allocator;
        ke_entity next_entity;
        void *internal_data;
    } ke_ecs_registry;

           ke_result ke_ecs_registry_create(struct ke_allocator *alloc, ke_ecs_registry **out_registry);

           void ke_ecs_registry_destroy(ke_ecs_registry *registry);

           ke_entity ke_ecs_entity_create(ke_ecs_registry *registry);

           void ke_ecs_entity_destroy(ke_ecs_registry *registry, ke_entity entity);

           ke_component_id ke_ecs_component_register(ke_ecs_registry *registry, const char *name, size_t size);

           ke_component_id ke_ecs_component_register_v2(
        ke_ecs_registry *registry,
        const char *name,
        size_t size,
        const ke_component_field *fields,
        uint32_t field_count);

    typedef struct ke_component_meta
    {
        ke_component_id cid;
        size_t size;
        const ke_component_field *fields;
        uint32_t field_count;
    } ke_component_meta;

           ke_result ke_ecs_component_lookup(
        ke_ecs_registry *registry,
        const char *name,
        ke_component_meta *out_meta);
           ke_result ke_ecs_component_apply_variant(
        ke_ecs_registry *registry,
        ke_entity entity,
        ke_component_id cid,
        const char *field_name,
        const ke_variant *value);

           void *ke_ecs_component_add(ke_ecs_registry *registry, ke_entity entity, ke_component_id component);

           void ke_ecs_component_remove(ke_ecs_registry *registry, ke_entity entity, ke_component_id component);

           void *ke_ecs_component_get(ke_ecs_registry *registry, ke_entity entity, ke_component_id component);

           void ke_ecs_registry_query(ke_ecs_registry *registry, ke_component_id component,
                               ke_entity **out_entities, void **out_data, size_t *out_count);
    typedef uint64_t ke_entity;
    typedef struct ke_transform_component
    {
        ke_vec3 position;
        ke_quat rotation;
        ke_vec3 scale;
        ke_mat4 world_matrix;
    } ke_transform_component;

    typedef struct ke_hierarchy_component
    {
        ke_entity parent;
        ke_entity first_child;
        ke_entity next_sibling;
        ke_entity prev_sibling;
    } ke_hierarchy_component;

    typedef struct ke_name_component
    {
        char name[64];
    } ke_name_component;

    typedef ke_result (*ke_script_func)(ke_entity entity);
    typedef ke_result (*ke_script_update_func)(ke_entity entity, float dt);
    typedef ke_result (*ke_script_input_func)(ke_entity entity, const ke_input_snapshot *input);

    typedef struct ke_script_component
    {
        uint8_t state;
        ke_script_func on_awake;
        ke_script_func on_start;
        ke_script_update_func on_update;
        ke_script_update_func on_late_update;
        ke_script_func on_destroy;
        ke_script_input_func on_input;
    } ke_script_component;
    struct ke_world;
    struct ke_frame_packet;
    typedef void (*ke_system_update_func)(void* handle, struct ke_world* world, float dt, struct ke_frame_packet* packet);

    typedef struct ke_system_params {
        const char* name;
        ke_system_update_func update;
        void* handle;

        const uint32_t* reads;
        uint32_t read_count;
        const uint32_t* writes;
        uint32_t write_count;
    } ke_system_params;
    struct ke_task_scheduler;
    struct ke_frame;

    typedef struct ke_world_params {
        struct ke_allocator *allocator;
    } ke_world_params;

    typedef struct ke_world
    {
        void *handle;
        struct ke_allocator *allocator;
        struct ke_ecs_registry *registry;
        void *internal_data;

        void (*destroy)(struct ke_world *self);
        ke_result (*update)(struct ke_world *self, const struct ke_frame *frame);

        struct ke_ecs_registry *(*get_registry)(struct ke_world *self);

        ke_result (*add_system)(struct ke_world *self, const ke_system_params *params);

        uint32_t (*transform_id)(struct ke_world *self);
        uint32_t (*hierarchy_id)(struct ke_world *self);
        uint32_t (*name_id)(struct ke_world *self);
        uint32_t (*script_id)(struct ke_world *self);

        struct ke_task_scheduler* (*get_task_scheduler)(struct ke_world* self);
    } ke_world;

           ke_result ke_world_create(const ke_world_params *params, ke_world **out_world);

           ke_result ke_world_notify_destroy(ke_world *world, ke_entity entity);

struct ke_world;

    typedef struct ke_scene_tree
    {
        void *handle;

        ke_entity (*root)(struct ke_scene_tree *self);

        ke_entity (*create_node)(struct ke_scene_tree *self, const char *name, ke_entity parent);

        ke_result (*destroy_node)(struct ke_scene_tree *self, ke_entity entity);

        void (*destroy_all)(struct ke_scene_tree *self);

        ke_entity (*find_node)(struct ke_scene_tree *self, const char *name_or_path);

        void (*destroy)(struct ke_scene_tree *self);

    } ke_scene_tree;

                     ke_result ke_scene_tree_create(
        struct ke_world *world,
        ke_allocator *alloc,
        ke_scene_tree **out_tree);

    typedef enum ke_key
    {
        KE_KEY_UNKNOWN = -1,
        KE_KEY_SPACE = 32,
        KE_KEY_APOSTROPHE = 39,
        KE_KEY_COMMA = 44,
        KE_KEY_MINUS = 45,
        KE_KEY_PERIOD = 46,
        KE_KEY_SLASH = 47,
        KE_KEY_NUMBER_0 = 48,
        KE_KEY_NUMBER_1 = 49,
        KE_KEY_NUMBER_2 = 50,
        KE_KEY_NUMBER_3 = 51,
        KE_KEY_NUMBER_4 = 52,
        KE_KEY_NUMBER_5 = 53,
        KE_KEY_NUMBER_6 = 54,
        KE_KEY_NUMBER_7 = 55,
        KE_KEY_NUMBER_8 = 56,
        KE_KEY_NUMBER_9 = 57,
        KE_KEY_SEMICOLON = 59,
        KE_KEY_EQUAL = 61,
        KE_KEY_A = 65,
        KE_KEY_B = 66,
        KE_KEY_C = 67,
        KE_KEY_D = 68,
        KE_KEY_E = 69,
        KE_KEY_F = 70,
        KE_KEY_G = 71,
        KE_KEY_H = 72,
        KE_KEY_I = 73,
        KE_KEY_J = 74,
        KE_KEY_K = 75,
        KE_KEY_L = 76,
        KE_KEY_M = 77,
        KE_KEY_N = 78,
        KE_KEY_O = 79,
        KE_KEY_P = 80,
        KE_KEY_Q = 81,
        KE_KEY_R = 82,
        KE_KEY_S = 83,
        KE_KEY_T = 84,
        KE_KEY_U = 85,
        KE_KEY_V = 86,
        KE_KEY_W = 87,
        KE_KEY_X = 88,
        KE_KEY_Y = 89,
        KE_KEY_Z = 90,
        KE_KEY_LEFT_BRACKET = 91,
        KE_KEY_BACKSLASH = 92,
        KE_KEY_RIGHT_BRACKET = 93,
        KE_KEY_GRAVE_ACCENT = 96,
        KE_KEY_WORLD_1 = 161,
        KE_KEY_WORLD_2 = 162,
        KE_KEY_ESCAPE = 256,
        KE_KEY_ENTER = 257,
        KE_KEY_TAB = 258,
        KE_KEY_BACKSPACE = 259,
        KE_KEY_INSERT = 260,
        KE_KEY_DELETE = 261,
        KE_KEY_RIGHT = 262,
        KE_KEY_LEFT = 263,
        KE_KEY_DOWN = 264,
        KE_KEY_UP = 265,
        KE_KEY_PAGE_UP = 266,
        KE_KEY_PAGE_DOWN = 267,
        KE_KEY_HOME = 268,
        KE_KEY_END = 269,
        KE_KEY_CAPS_LOCK = 280,
        KE_KEY_SCROLL_LOCK = 281,
        KE_KEY_NUM_LOCK = 282,
        KE_KEY_PRINT_SCREEN = 283,
        KE_KEY_PAUSE = 284,
        KE_KEY_F1 = 290,
        KE_KEY_F2 = 291,
        KE_KEY_F3 = 292,
        KE_KEY_F4 = 293,
        KE_KEY_F5 = 294,
        KE_KEY_F6 = 295,
        KE_KEY_F7 = 296,
        KE_KEY_F8 = 297,
        KE_KEY_F9 = 298,
        KE_KEY_F10 = 299,
        KE_KEY_F11 = 300,
        KE_KEY_F12 = 301,
        KE_KEY_F13 = 302,
        KE_KEY_F14 = 303,
        KE_KEY_F15 = 304,
        KE_KEY_F16 = 305,
        KE_KEY_F17 = 306,
        KE_KEY_F18 = 307,
        KE_KEY_F19 = 308,
        KE_KEY_F20 = 309,
        KE_KEY_F21 = 310,
        KE_KEY_F22 = 311,
        KE_KEY_F23 = 312,
        KE_KEY_F24 = 313,
        KE_KEY_F25 = 314,
        KE_KEY_KEYPAD_0 = 320,
        KE_KEY_KEYPAD_1 = 321,
        KE_KEY_KEYPAD_2 = 322,
        KE_KEY_KEYPAD_3 = 323,
        KE_KEY_KEYPAD_4 = 324,
        KE_KEY_KEYPAD_5 = 325,
        KE_KEY_KEYPAD_6 = 326,
        KE_KEY_KEYPAD_7 = 327,
        KE_KEY_KEYPAD_8 = 328,
        KE_KEY_KEYPAD_9 = 329,
        KE_KEY_KEYPAD_DECIMAL = 330,
        KE_KEY_KEYPAD_DIVIDE = 331,
        KE_KEY_KEYPAD_MULTIPLY = 332,
        KE_KEY_KEYPAD_SUBTRACT = 333,
        KE_KEY_KEYPAD_ADD = 334,
        KE_KEY_KEYPAD_ENTER = 335,
        KE_KEY_KEYPAD_EQUAL = 336,
        KE_KEY_SHIFT_LEFT = 340,
        KE_KEY_CONTROL_LEFT = 341,
        KE_KEY_ALT_LEFT = 342,
        KE_KEY_SUPER_LEFT = 343,
        KE_KEY_SHIFT_RIGHT = 344,
        KE_KEY_CONTROL_RIGHT = 345,
        KE_KEY_ALT_RIGHT = 346,
        KE_KEY_SUPER_RIGHT = 347,
        KE_KEY_MENU = 348,
    } ke_key;

    typedef enum ke_mouse_button
    {
        KE_MOUSE_BUTTON_LEFT = 0,
        KE_MOUSE_BUTTON_RIGHT = 1,
        KE_MOUSE_BUTTON_MIDDLE = 2,
    } ke_mouse_button;
    typedef enum ke_action_type
    {
        KE_ACTION_TYPE_BUTTON = 0,
        KE_ACTION_TYPE_AXIS1D = 1,
        KE_ACTION_TYPE_AXIS2D = 2,
        KE_ACTION_TYPE_AXIS3D = 3,
    } ke_action_type;

    typedef enum ke_action_phase
    {
        KE_ACTION_PHASE_STARTED = 1,
        KE_ACTION_PHASE_PERFORMED = 2,
        KE_ACTION_PHASE_CANCELED = 3,
    } ke_action_phase;

    typedef struct ke_input_action_event
    {
        int32_t action_id;
        ke_action_type type;
        ke_action_phase phase;
        float x, y, z;
    } ke_input_action_event;

    typedef void (*ke_input_action_event_func)(void *ctx, ke_input_action_event event);
    typedef struct ke_input_actions
    {
        void *handle;

        ke_result (*load)(struct ke_input_actions *self, const char *path);

        int32_t (*get_action_id)(struct ke_input_actions *self, const char *name);
        int32_t (*add_action)(struct ke_input_actions *self,
                              const char *name,
                              ke_action_type type);

        ke_result (*bind_key)(struct ke_input_actions *self,
                              int32_t action_id,
                              ke_key key);

        ke_result (*bind_mouse_button)(struct ke_input_actions *self,
                                       int32_t action_id,
                                       ke_mouse_button button);

        ke_result (*bind_key_pair)(struct ke_input_actions *self,
                                   int32_t action_id,
                                   ke_key negative,
                                   ke_key positive);

        ke_result (*bind_key_quad)(struct ke_input_actions *self,
                                   int32_t action_id,
                                   ke_key up,
                                   ke_key down,
                                   ke_key left,
                                   ke_key right);

        ke_result (*evaluate)(struct ke_input_actions *self,
                              const ke_input_snapshot *snapshot,
                              ke_input_action_event_func on_event,
                              void *event_ctx);

        _Bool (*is_action_down)(struct ke_input_actions *self, int32_t action_id);

        _Bool (*was_action_pressed)(struct ke_input_actions *self, int32_t action_id);

        _Bool (*was_action_released)(struct ke_input_actions *self, int32_t action_id);

        float (*get_axis1d)(struct ke_input_actions *self, int32_t action_id);

        void (*get_axis2d)(struct ke_input_actions *self, int32_t action_id,
                            float *out_x, float *out_y);

        void (*get_axis3d)(struct ke_input_actions *self, int32_t action_id,
                            float *out_x, float *out_y, float *out_z);

        void (*destroy)(struct ke_input_actions *self);
    } ke_input_actions;

                     ke_result ke_input_actions_create(
        ke_allocator *alloc,
        ke_input_actions **out_actions);
    typedef enum ke_mesh_primitive
    {
        KE_MESH_PRIMITIVE_QUAD = 0,
        KE_MESH_PRIMITIVE_PLANE = 1,
        KE_MESH_PRIMITIVE_CUBE = 2,
        KE_MESH_PRIMITIVE_SPHERE = 3,
    } ke_mesh_primitive;

    typedef struct ke_mesh_shape_data
    {
        ke_vertex *vertices;
        uint32_t vertex_count;
        uint16_t *indices;
        uint32_t index_count;
    } ke_mesh_shape_data;
                     ke_result ke_mesh_shape_bake(
        ke_allocator *alloc,
        ke_mesh_primitive prim,
        uint32_t segments,
        ke_mesh_shape_data *out_data);

                     void ke_mesh_shape_free(
        ke_allocator *alloc,
        ke_mesh_shape_data *data);
struct ke_world;
    typedef struct ke_camera_component
    {
        float fov;
        float near_plane;
        float far_plane;
        float orthographic_size;
        uint8_t orthographic;
    } ke_camera_component;

    typedef struct ke_camera_render_system_params
    {
        struct ke_world *world;
        ke_allocator *allocator;

        int ndc_y_flip;
        int ndc_zero_to_one_depth;

        float aspect;
    } ke_camera_render_system_params;

    typedef struct ke_camera_render_system ke_camera_render_system;

                     ke_result ke_camera_render_system_create(
        const ke_camera_render_system_params *params,
        ke_camera_render_system **out_system);

                     void ke_camera_render_system_destroy(ke_camera_render_system *system);

                     ke_component_id ke_camera_render_system_component_id(
        const ke_camera_render_system *system);

                     void ke_camera_render_system_get_system_params(
        ke_camera_render_system *system,
        ke_system_params *out_params);
struct ke_world;
    typedef struct ke_mesh_component
    {
        ke_mesh_handle mesh;
        ke_material_handle material;
        char primitive[32];
        float color[4];
    } ke_mesh_component;

    typedef struct ke_mesh_render_system_params
    {
        struct ke_world *world;
        ke_allocator *allocator;
    } ke_mesh_render_system_params;

    typedef struct ke_mesh_render_system ke_mesh_render_system;

                     ke_result ke_mesh_render_system_create(
        const ke_mesh_render_system_params *params,
        ke_mesh_render_system **out_system);

                     void ke_mesh_render_system_destroy(ke_mesh_render_system *system);

                     ke_component_id ke_mesh_render_system_component_id(
        const ke_mesh_render_system *system);

                     void ke_mesh_render_system_get_system_params(
        ke_mesh_render_system *system, ke_system_params *out_params);
struct ke_world;

    typedef struct ke_directional_light_component
    {
        float dir_x, dir_y, dir_z;
        float r, g, b;
        float intensity;
    } ke_directional_light_component;

    typedef struct ke_point_light_component
    {
        float radius;
        float r, g, b;
        float intensity;
    } ke_point_light_component;

    typedef struct ke_spot_light_component
    {
        float dir_x, dir_y, dir_z;
        float inner_angle;
        float outer_angle;
        float range;
        float r, g, b;
        float intensity;
    } ke_spot_light_component;

    typedef struct ke_light_render_system_params
    {
        struct ke_world *world;
        ke_allocator *allocator;
    } ke_light_render_system_params;

    typedef struct ke_light_render_system ke_light_render_system;

                     ke_result ke_light_render_system_create(
        const ke_light_render_system_params *params,
        ke_light_render_system **out_system);

                     void ke_light_render_system_destroy(ke_light_render_system *system);

                     ke_component_id ke_light_render_system_directional_id(const ke_light_render_system *system);
                     ke_component_id ke_light_render_system_point_id(const ke_light_render_system *system);
                     ke_component_id ke_light_render_system_spot_id(const ke_light_render_system *system);

                     void ke_light_render_system_get_system_params(
        ke_light_render_system *system, ke_system_params *out_params);
struct ke_world;
struct ke_render;
struct ke_mesh_render_system;

    typedef struct ke_mesh_asset_system_params
    {
        struct ke_world *world;
        ke_allocator *allocator;
        struct ke_render *render;
        struct ke_mesh_render_system *mesh_system;
    } ke_mesh_asset_system_params;

    typedef struct ke_mesh_asset_system ke_mesh_asset_system;

                     ke_result ke_mesh_asset_system_create(
        const ke_mesh_asset_system_params *params,
        ke_mesh_asset_system **out_system);

                     void ke_mesh_asset_system_destroy(ke_mesh_asset_system *system);

                     void ke_mesh_asset_system_get_system_params(
        ke_mesh_asset_system *system, ke_system_params *out_params);

struct ke_world;
    typedef ke_result (*ke_script_factory_func)(
        void *ctx, ke_entity entity, const char *type_name);
    typedef struct ke_scene_properties
    {
        const ke_variant_table_entry *entries;
        uint32_t count;
    } ke_scene_properties;

    typedef struct ke_scene_loader
    {
        void *handle;

        ke_result (*load)(struct ke_scene_loader *self, const char *path);

        ke_result (*register_script_language)(struct ke_scene_loader *self,
                                              const char *language,
                                              ke_script_factory_func factory,
                                              void *ctx);

        void (*destroy)(struct ke_scene_loader *self);
    } ke_scene_loader;
                     ke_result ke_scene_loader_create(
        ke_allocator *alloc,
        struct ke_world *world,
        ke_scene_tree *tree,
        const char *project_root,
        ke_scene_loader **out_loader);
struct ke_window;

typedef struct ke_render_bgfx_params
{
    struct ke_allocator *allocator;
    struct ke_logger *logger;
    struct ke_window *window;
    const char *shader_path;
    uint32_t renderer_type;
    ke_bool vsync;
} ke_render_bgfx_params;

 ke_result ke_render_bgfx_create(const ke_render_bgfx_params* params, ke_render** out_render);

    typedef struct ke_window
    {
        void *handle;
        void (*destroy)(struct ke_window *self);

        ke_result (*on_initialize)(struct ke_window *self);
        ke_result (*on_shutdown)(struct ke_window *self);

        ke_bool (*should_close)(struct ke_window *self);
        ke_result (*poll_events)(struct ke_window *self);
        ke_result (*swap_buffers)(struct ke_window *self);
        ke_result (*get_size)(struct ke_window *self, int32_t *width, int32_t *height);
        void *(*get_native_handle)(struct ke_window *self);
    } ke_window;

typedef struct ke_window_glfw_params {
    struct ke_allocator* allocator;
    struct ke_logger* logger;
    struct ke_input* input;
    const char* title;
    int32_t width;
    int32_t height;
    ke_bool fullscreen;
} ke_window_glfw_params;

 ke_result ke_window_glfw_create(const ke_window_glfw_params* params, ke_window** out_window);
]]
