[scene]
name    = "Paddle"
version = 2

[[entity]]
name = "Root"
type = "Pong.Paddle"

[[entity]]
name   = "Shape"
parent = "Root"
type   = "CollisionShape2D"
[entity.collider2d]
half_extents = [0.15, 0.9]
restitution  = 1.0

[[entity]]
name   = "Visual"
parent = "Root"
type   = "Sprite2D"
[entity.transform2d]
scale = [0.3, 1.8]
[entity.mesh]
mesh      = "quad"
color     = [0.95, 0.95, 0.95, 1.0]
roughness = 1.0
