[scene]
name    = "Wall"
version = 2

[[entity]]
name = "Root"
type = "Pong.Wall"

[[entity]]
name   = "Shape"
parent = "Root"
type   = "CollisionShape2D"
[entity.collider2d]
half_extents = [8.0, 0.25]
restitution  = 1.0

[[entity]]
name   = "Visual"
parent = "Root"
type   = "Sprite2D"
[entity.transform]
scale = [16.0, 0.5, 1.0]
[entity.mesh]
mesh      = "quad"
color     = [0.15, 0.15, 0.20, 1.0]
roughness = 1.0
