[scene]
name    = "Wall"
version = 2

[[entity]]
name = "Root"
type = "pong.wall"

[[entity]]
name   = "Shape"
parent = "Root"
type   = "collider2d"
[entity.collider2d]
half_extents = [8.0, 0.25]
restitution  = 1.0

[[entity]]
name   = "Visual"
parent = "Root"
type   = "sprite2d"
[entity.sprite2d]
size  = [16.0, 0.5]
color = [0.15, 0.15, 0.20, 1.0]
