// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Render.Native;

namespace KernelEngine.Framework;

/// <summary>Scene-wide ambient light node. First entity with this component wins.</summary>
[GeneratedNodeComponent(typeof(ke_ambient_light_component), "ambient_light")]
public partial class AmbientLight : Node3D
{
    public AmbientLight()
    {
        _generatedState.color[0] = 0.05f;
        _generatedState.color[1] = 0.05f;
        _generatedState.color[2] = 0.05f;
    }

    [NativeField("color")]
    public partial Vector3 Color { get; set; }
}