// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Common.Native;
using KernelEngine.Render.Native;

namespace KernelEngine.Framework;

/// <summary>Directional light node. Init properties feed the per-frame light state the renderer consumes.</summary>
[GeneratedNodeComponent(typeof(ke_directional_light_component), "directional_light")]
public partial class DirectionalLight : Node3D
{
    public DirectionalLight()
    {
        _generatedState0.direction = new ke_vec3 { x = 0.2f, y = 1f, z = 0.5f };
        _generatedState0.color = new ke_vec3 { x = 1f, y = 1f, z = 1f };
        _generatedState0.intensity = 1f;
        _generatedState0.ambient = new ke_vec3 { x = 0.2f, y = 0.2f, z = 0.2f };
    }

    [NativeField("direction")]
    public partial Vector3 Direction { get; set; }

    /// <summary>Linear RGB.</summary>
    [NativeField("color")]
    public partial Vector3 Color { get; set; }

    [NativeField("intensity")]
    public partial float Intensity { get; set; }

    [NativeField("ambient")]
    public partial Vector3 Ambient { get; set; }
}