// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Common.Native;
using KernelEngine.Render.Native;

namespace KernelEngine.Framework;

/// <summary>Point light node — emits light in all directions from this entity's world position.</summary>
[GeneratedNodeComponent(typeof(ke_point_light_component), "point_light")]
public partial class PointLight : Node3D
{
    public PointLight()
    {
        _generatedState.color = new ke_vec3 { x = 1f, y = 1f, z = 1f };
        _generatedState.intensity = 1f;
        _generatedState.radius = 10f;
    }

    /// <summary>Linear RGB.</summary>
    [NativeField("color")]
    public partial Vector3 Color { get; set; }

    [NativeField("intensity")]
    public partial float Intensity { get; set; }

    [NativeField("radius")]
    public partial float Radius { get; set; }
}