// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Common.Native;
using KernelEngine.Render.Native;

namespace KernelEngine.Framework;

/// <summary>Point light node — emits light in all directions from this entity's world position.</summary>
[GeneratedNodeComponent(typeof(ke_transform_component), "transform")]
[GeneratedNodeComponent(typeof(ke_point_light_component), "point_light")]
public partial class PointLight : Node
{
    public PointLight()
    {
        _generatedState0 = global::System.Runtime.CompilerServices.Unsafe.BitCast<KernelEngine.Ecs.TransformComponent, ke_transform_component>(KernelEngine.Ecs.TransformComponent.Identity);
        _generatedState1.color = new ke_vec3 { x = 1f, y = 1f, z = 1f };
        _generatedState1.intensity = 1f;
        _generatedState1.radius = 10f;
    }

    [NativeWhole(Component = typeof(ke_transform_component))]
    public partial KernelEngine.Ecs.TransformComponent LocalTransform { get; set; }

    /// <summary>Linear RGB.</summary>
    [NativeField("color", Component = typeof(ke_point_light_component))]
    public partial Vector3 Color { get; set; }

    [NativeField("intensity", Component = typeof(ke_point_light_component))]
    public partial float Intensity { get; set; }

    [NativeField("radius", Component = typeof(ke_point_light_component))]
    public partial float Radius { get; set; }
}