// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Render.Native;

namespace KernelEngine.Framework;

/// <summary>Spot light node — emits a cone of light from this entity's world position.</summary>
[GeneratedNodeComponent(typeof(ke_spot_light_component), "spot_light")]
public partial class SpotLight : Node3D
{
    public SpotLight()
    {
        _generatedState.direction[0] = 0f;
        _generatedState.direction[1] = -1f;
        _generatedState.direction[2] = 0f;
        _generatedState.color[0] = 1f;
        _generatedState.color[1] = 1f;
        _generatedState.color[2] = 1f;
        _generatedState.intensity = 1f;
        _generatedState.range = 20f;
        _generatedState.inner_angle = 25f;
        _generatedState.outer_angle = 35f;
    }

    [NativeField("direction")]
    public partial Vector3 Direction { get; set; }

    /// <summary>Linear RGB.</summary>
    [NativeField("color")]
    public partial Vector3 Color { get; set; }

    [NativeField("intensity")]
    public partial float Intensity { get; set; }

    [NativeField("range")]
    public partial float Range { get; set; }

    [NativeField("inner_angle")]
    public partial float InnerAngleDeg { get; set; }

    [NativeField("outer_angle")]
    public partial float OuterAngleDeg { get; set; }
}