// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Common.Native;
using KernelEngine.Render.Native;

namespace KernelEngine.Framework;

/// <summary>A textured quad in the plane. Everything that makes one sprite differ from another lives here rather than in a mesh a scene happened to author beside it: which image, which rectangle of it, how big, around what point, and mirrored on which axis. The native "render.sprite2d.resolve" system turns that into the geometry and material the render passes already consume, so a sprite is a node with data in every language instead of a name for a quad.</summary>
[GeneratedNodeComponent(typeof(ke_sprite2d_component), "sprite2d")]
public partial class Sprite2D : Node2D
{
    public Sprite2D()
    {
        _generatedState0.region = new ke_vec4 { x = 0f, y = 0f, z = 1f, w = 1f };
        _generatedState0.size = new ke_vec2 { x = 1f, y = 1f };
        _generatedState0.pivot = new ke_vec2 { x = 0.5f, y = 0.5f };
        _generatedState0.color = new ke_vec4 { x = 1f, y = 1f, z = 1f, w = 1f };
        _generatedState0.alpha_cutoff = 0.5f;
    }

    /// <summary>Image to sample. Empty draws the plain tinted quad.</summary>
    [NativeField("texture", Component = typeof(ke_sprite2d_component))]
    public partial string Texture { get; set; }

    [NativeField("region", Component = typeof(ke_sprite2d_component))]
    public partial Vector4 Region { get; set; }

    [NativeField("size", Component = typeof(ke_sprite2d_component))]
    public partial Vector2 Size { get; set; }

    [NativeField("pivot", Component = typeof(ke_sprite2d_component))]
    public partial Vector2 Pivot { get; set; }

    [NativeField("flip_h", Component = typeof(ke_sprite2d_component))]
    public partial bool FlipH { get; set; }

    [NativeField("flip_v", Component = typeof(ke_sprite2d_component))]
    public partial bool FlipV { get; set; }

    [NativeField("color", Component = typeof(ke_sprite2d_component))]
    public partial Vector4 Color { get; set; }

    /// <summary>ke_alpha_mode. [default:0]</summary>
    [NativeField("alpha_mode", Component = typeof(ke_sprite2d_component))]
    public partial uint AlphaMode { get; set; }

    [NativeField("alpha_cutoff", Component = typeof(ke_sprite2d_component))]
    public partial float AlphaCutoff { get; set; }

    [NativeField("attached", Component = typeof(ke_sprite2d_component))]
    public partial bool Attached { get; set; }
}