using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace KernelEngine.SourceGenerators;

[Generator]
public sealed class NodePropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is PropertyDeclarationSyntax { Parent: ClassDeclarationSyntax } p && IsPartialAutoProperty(p),
            static (ctx, _) => (PropertyDeclarationSyntax)ctx.Node);

        var classes = candidates
            .Select(static (p, _) => (ClassDeclarationSyntax)p.Parent!)
            .Collect()
            .SelectMany(static (list, _) => list.Distinct());

        context.RegisterSourceOutput(classes.Combine(context.CompilationProvider),
            static (spc, pair) => Generate(spc, pair.Left, pair.Right));
    }

    static bool IsPartialAutoProperty(PropertyDeclarationSyntax p)
    {
        if (!p.Modifiers.Any(SyntaxKind.PartialKeyword)) return false;
        if (p.AccessorList is null) return false;
        foreach (var a in p.AccessorList.Accessors)
            if (a.Body is not null || a.ExpressionBody is not null) return false;
        return true;
    }

    static void Generate(SourceProductionContext spc, ClassDeclarationSyntax classDecl, Compilation compilation)
    {
        var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
        if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol) return;
        if (!DerivesFromNode(classSymbol)) return;

        var properties = classSymbol.GetMembers().OfType<IPropertySymbol>()
            .Where(p => p.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is PropertyDeclarationSyntax pd && IsPartialAutoProperty(pd)))
            .ToImmutableArray();
        if (properties.IsEmpty) return;

        var markers = classSymbol.GetAttributes()
            .Where(a => a.AttributeClass?.Name == "GeneratedNodeComponentAttribute")
            .ToImmutableArray();

        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace ? null : classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;

        // protected internal members (OnBind, HasBehavior) keep protected internal
        // when overridden from Node's own assembly (Framework) — only a CROSS-assembly
        // override is required to narrow to plain protected. Node3D is the first
        // generated type to live in the same assembly as Node itself; every other
        // generated/hand-written node type lives in a domain assembly (Render.Webgpu,
        // Physics, ...), where narrowing is mandatory, not optional.
        INamedTypeSymbol? nodeType = classSymbol.BaseType;
        while (nodeType is not null && nodeType.Name != "Node") nodeType = nodeType.BaseType;
        var overrideModifier = nodeType is not null && SymbolEqualityComparer.Default.Equals(nodeType.ContainingAssembly, classSymbol.ContainingAssembly)
            ? "protected internal"
            : "protected";

        // A node type is a component SET: one slot per declared component, each with its
        // own backing state and cid. A game-authored type declares none, and gets a single
        // synthesized slot instead — the same shape, so nothing below branches on it twice.
        var isNative = markers.Length > 0;
        var slots = isNative
            ? markers.Select((m, i) => new Slot(
                    (INamedTypeSymbol)m.ConstructorArguments[0].Value!,
                    ((INamedTypeSymbol)m.ConstructorArguments[0].Value!).ToDisplayString(),
                    (string)m.ConstructorArguments[1].Value!,
                    i))
                .ToImmutableArray()
            : [new Slot(null, $"{className}_Data", $"{ns}.{className}_Data", 0)];

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        if (ns is not null) sb.AppendLine($"namespace {ns};").AppendLine();

        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");

        if (!isNative)
        {
            sb.AppendLine($"    private struct {slots[0].TypeName}");
            sb.AppendLine("    {");
            foreach (var p in properties)
                sb.AppendLine($"        public {p.Type.ToDisplayString()} {p.Name};");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        foreach (var slot in slots)
        {
            sb.AppendLine($"    private {slot.TypeName} {slot.State};");
            sb.AppendLine($"    private uint {slot.Cid};");
        }
        sb.AppendLine();

        // Node.HasBehavior used to be discovered by reflecting on the instance at
        // bind time; it is now a compile-time decision. The user's own partial
        // declares OnUpdate (or doesn't) — that's a fact this generator can see
        // in the same syntax pass, so it emits the override here instead of the
        // runtime ever asking "does this type have OnUpdate" again.
        var hasOnUpdate = classSymbol.GetMembers("OnUpdate").OfType<IMethodSymbol>()
            .Any(m => SymbolEqualityComparer.Default.Equals(m.ContainingType, classSymbol) && m.IsOverride);
        if (hasOnUpdate)
        {
            sb.AppendLine($"    {overrideModifier} override bool HasBehavior => true;");
            sb.AppendLine();
        }

        var needsUtf8Helpers = false;

        foreach (var p in properties)
        {
            var wholeAttr = p.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "NativeWholeAttribute");
            var fieldAttr = p.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "NativeFieldAttribute");
            var declaredFieldName = fieldAttr is not null ? (string)fieldAttr.ConstructorArguments[0].Value! : p.Name;
            var pinned = NamedComponentOf(wholeAttr) ?? NamedComponentOf(fieldAttr);

            var slot = ResolveSlot(spc, p, slots, isNative, declaredFieldName, wholeAttr is not null, pinned);
            if (slot is null) continue;

            var backingType = slot.TypeName;
            var backingTypeSymbol = slot.Symbol;

            if (wholeAttr is not null)
            {
                // The whole backing struct, bit-cast — not a per-field read/write.
                // Same shape as a hand-written whole-struct property (Node3D's
                // LocalTransform before this became generatable), except the cast
                // replaces field-by-field assignment so the write stays atomic.
                var propType = p.Type.ToDisplayString();
                sb.AppendLine($"    public partial {propType} {p.Name}");
                sb.AppendLine("    {");
                sb.AppendLine($"        get => global::System.Runtime.CompilerServices.Unsafe.BitCast<{backingType}, {propType}>({slot.Current}());");
                sb.AppendLine("        set");
                sb.AppendLine("        {");
                sb.AppendLine($"            var s = global::System.Runtime.CompilerServices.Unsafe.BitCast<{propType}, {backingType}>(value);");
                sb.AppendLine($"            if (IsBound) NodeWorld!.SetByCid(Entity, {slot.Cid}, s); else {slot.State} = s;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                continue;
            }

            var fieldName = isNative ? declaredFieldName : p.Name;
            var fieldSymbol = backingTypeSymbol?.GetMembers(fieldName).OfType<IFieldSymbol>().FirstOrDefault();
            // ClangSharp backs a C `float x[N]` with a generated `_x_e__FixedBuffer` type —
            // only THAT shape indexes by [i]; a named ke_vecN/ke_quat field (below) is a
            // bit-cast coercion instead, even though its C# property is also Vector2/3/4.
            var isFixedBuffer = fieldSymbol is not null && fieldSymbol.Type.Name.EndsWith("_e__FixedBuffer");

            // A `char[N]` component field projected as a string. The buffer's own
            // capacity is the truncation point — it is the component's ABI, so the
            // property cannot widen it, only refuse to overflow it.
            if (p.Type.SpecialType == SpecialType.System_String && isFixedBuffer)
            {
                needsUtf8Helpers = true;
                sb.AppendLine($"    public partial string {p.Name}");
                sb.AppendLine("    {");
                sb.AppendLine("        get");
                sb.AppendLine("        {");
                sb.AppendLine($"            var s = {slot.Current}();");
                sb.AppendLine($"            return GeneratedUtf8Get(ref s.{fieldName});");
                sb.AppendLine("        }");
                sb.AppendLine("        set");
                sb.AppendLine("        {");
                sb.AppendLine($"            var s = {slot.Current}();");
                sb.AppendLine($"            GeneratedUtf8Set(ref s.{fieldName}, value);");
                sb.AppendLine($"            if (IsBound) NodeWorld!.SetByCid(Entity, {slot.Cid}, s); else {slot.State} = s;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                continue;
            }

            var arity = isNative && isFixedBuffer ? VectorArity(p.Type) : null;
            var coercion = arity is null && fieldSymbol is not null ? CoercionFor(p.Type, fieldSymbol.Type) : null;

            if (arity is null && fieldSymbol is not null && coercion is null
                && !SymbolEqualityComparer.Default.Equals(p.Type, fieldSymbol.Type))
            {
                spc.ReportDiagnostic(Diagnostic.Create(NoCoercionRule, p.Locations.FirstOrDefault(),
                    p.Name, p.Type.ToDisplayString(), fieldSymbol.Type.ToDisplayString()));
                continue;
            }

            sb.AppendLine($"    public partial {p.Type.ToDisplayString()} {p.Name}");
            sb.AppendLine("    {");
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine($"            var s = {slot.Current}();");
            sb.AppendLine(arity is int rn
                ? $"            return new(" + string.Join(", ", Enumerable.Range(0, rn).Select(i => $"s.{fieldName}[{i}]")) + ");"
                : coercion is not null
                    ? $"            return {coercion.Value.read("s." + fieldName)};"
                    : $"            return s.{fieldName};");
            sb.AppendLine("        }");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine($"            var s = {slot.Current}();");
            if (arity is int wn)
                foreach (var i in Enumerable.Range(0, wn))
                    sb.AppendLine($"            s.{fieldName}[{i}] = value.{VectorLanes[i]};");
            else if (coercion is not null)
                sb.AppendLine($"            s.{fieldName} = {coercion.Value.write("value")};");
            else
                sb.AppendLine($"            s.{fieldName} = value;");
            sb.AppendLine($"            if (IsBound) NodeWorld!.SetByCid(Entity, {slot.Cid}, s); else {slot.State} = s;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        if (needsUtf8Helpers)
        {
            // Generic over the inline-array type so one pair serves every char[N]
            // field regardless of its capacity: CreateSpan(ref buf, 1) + AsBytes
            // yields exactly sizeof(TBuf) bytes, which IS N for a char buffer.
            sb.AppendLine();
            sb.AppendLine("    private static string GeneratedUtf8Get<TBuf>(ref TBuf buffer) where TBuf : struct");
            sb.AppendLine("    {");
            sb.AppendLine("        var bytes = global::System.Runtime.InteropServices.MemoryMarshal.AsBytes(");
            sb.AppendLine("            global::System.Runtime.InteropServices.MemoryMarshal.CreateSpan(ref buffer, 1));");
            sb.AppendLine("        var nul = bytes.IndexOf((byte)0);");
            sb.AppendLine("        return global::System.Text.Encoding.UTF8.GetString(nul < 0 ? bytes : bytes.Slice(0, nul));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private static void GeneratedUtf8Set<TBuf>(ref TBuf buffer, string value) where TBuf : struct");
            sb.AppendLine("    {");
            sb.AppendLine("        var bytes = global::System.Runtime.InteropServices.MemoryMarshal.AsBytes(");
            sb.AppendLine("            global::System.Runtime.InteropServices.MemoryMarshal.CreateSpan(ref buffer, 1));");
            sb.AppendLine("        bytes.Clear();");
            // Encoder.Convert truncates at a character boundary instead of throwing
            // or splitting a multi-byte sequence; the cleared tail leaves the NUL.
            sb.AppendLine("        global::System.Text.Encoding.UTF8.GetEncoder().Convert(");
            sb.AppendLine("            (value ?? string.Empty).AsSpan(), bytes.Slice(0, bytes.Length - 1), true, out _, out _, out _);");
            sb.AppendLine("    }");
        }

        sb.AppendLine();
        foreach (var slot in slots)
        {
            sb.AppendLine($"    private {slot.TypeName} {slot.Current}() =>");
            sb.AppendLine($"        IsBound && NodeWorld!.TryGetByCid<{slot.TypeName}>(Entity, {slot.Cid}, out var s) ? s : {slot.State};");
        }
        sb.AppendLine();

        sb.AppendLine($"    {overrideModifier} override void OnBind(global::KernelEngine.Framework.NodeWorld nodeWorld)");
        sb.AppendLine("    {");
        // A node type deriving from another generated node (MeshRenderer : Node3D)
        // binds TWO components, one per class in the chain, each with its own
        // _generatedCid. Overriding without chaining would leave every base
        // class's component unbound — its cid stays 0 and every write to its
        // properties is silently dropped. Node's own OnBind is abstract, so the
        // chain stops one level above it.
        if (nodeType is not null && !SymbolEqualityComparer.Default.Equals(classSymbol.BaseType, nodeType))
            sb.AppendLine("        base.OnBind(nodeWorld);");
        foreach (var slot in slots)
        {
            var resolveCid = isNative
                ? $"nodeWorld.CidOfName(\"{slot.ComponentName}\")"
                : $"nodeWorld.RegisterComponent<{slot.TypeName}>(\"{slot.ComponentName}\")";
            sb.AppendLine($"        {slot.Cid} = {resolveCid};");
            sb.AppendLine($"        GeneratedSeed({slot.Cid}, in {slot.State});");
        }
        sb.AppendLine("    }");

        sb.AppendLine("}");

        spc.AddSource($"{className}.NodeProperties.g.cs", sb.ToString());
    }

    /// <summary>
    /// One component of a node type's set: the native struct backing it, the name it is
    /// registered under, and the members generated for it. The index suffix is what keeps
    /// two components on the same node from colliding on a single state/cid pair.
    /// </summary>
    sealed class Slot(INamedTypeSymbol? symbol, string typeName, string componentName, int index)
    {
        public INamedTypeSymbol? Symbol { get; } = symbol;
        public string TypeName { get; } = typeName;
        public string ComponentName { get; } = componentName;
        public int Index { get; } = index;

        public string State => $"_generatedState{Index}";
        public string Cid => $"_generatedCid{Index}";
        public string Current => $"GeneratedCurrent{Index}";
    }

    static INamedTypeSymbol? NamedComponentOf(AttributeData? attr) =>
        attr?.NamedArguments.FirstOrDefault(kv => kv.Key == "Component").Value.Value as INamedTypeSymbol;

    static Slot? ResolveSlot(SourceProductionContext spc, IPropertySymbol property, ImmutableArray<Slot> slots,
        bool isNative, string fieldName, bool isWhole, INamedTypeSymbol? pinned)
    {
        if (slots.Length == 1) return slots[0];

        if (pinned is not null)
        {
            var named = slots.FirstOrDefault(s => SymbolEqualityComparer.Default.Equals(s.Symbol, pinned));
            if (named is not null) return named;
            spc.ReportDiagnostic(Diagnostic.Create(UnknownComponentRule, property.Locations.FirstOrDefault(),
                property.Name, pinned.ToDisplayString()));
            return null;
        }

        // A whole-struct property names no field, so nothing but an explicit Component can
        // say which of several structs it IS.
        if (isWhole)
        {
            spc.ReportDiagnostic(Diagnostic.Create(UnnamedWholeRule, property.Locations.FirstOrDefault(), property.Name));
            return null;
        }

        var matches = slots.Where(s => s.Symbol?.GetMembers(fieldName).OfType<IFieldSymbol>().Any() == true)
            .ToImmutableArray();
        if (matches.Length == 1) return matches[0];

        spc.ReportDiagnostic(Diagnostic.Create(AmbiguousComponentRule, property.Locations.FirstOrDefault(),
            property.Name, matches.IsEmpty ? "none" : matches.Length.ToString(), fieldName));
        return null;
    }

    static bool DerivesFromNode(INamedTypeSymbol symbol)
    {
        for (var t = symbol.BaseType; t is not null; t = t.BaseType)
            if (t.Name == "Node") return true;
        return false;
    }

    static readonly string[] VectorLanes = ["X", "Y", "Z", "W"];

    static int? VectorArity(ITypeSymbol type)
    {
        if (type.ContainingNamespace?.ToDisplayString() != "System.Numerics") return null;
        return type.Name switch { "Vector2" => 2, "Vector3" => 3, "Vector4" => 4, _ => null };
    }

    // ke_vec2/ke_vec3/ke_vec4/ke_quat (KernelEngine.Common.Native) are layout-identical
    // to their System.Numerics counterparts by construction (see kabic's NamedVectorTypes),
    // so the coercion is a bit-cast, not a field-by-field copy.
    static readonly Dictionary<string, string> NativeVectorNames = new()
    {
        ["Vector2"] = "ke_vec2", ["Vector3"] = "ke_vec3", ["Vector4"] = "ke_vec4", ["Quaternion"] = "ke_quat",
    };

    // ke_mesh_handle / ke_material_handle are { uint32_t bits; }; their managed
    // counterparts are readonly record struct H(uint Value). Same size, same single
    // field, so the coercion is a bit-cast like the vector one above.
    static readonly Dictionary<string, string> NativeHandleNames = new()
    {
        ["MeshHandle"] = "ke_mesh_handle", ["MaterialHandle"] = "ke_material_handle",
        ["TextureHandle"] = "ke_texture_handle", ["FontHandle"] = "ke_ui_font_handle",
    };

    static (Func<string, string> read, Func<string, string> write)? CoercionFor(ITypeSymbol propertyType, ITypeSymbol fieldType)
    {
        if (propertyType.SpecialType == SpecialType.System_Boolean && fieldType.SpecialType == SpecialType.System_Byte)
            return (expr => $"{expr} != 0", expr => $"(byte)({expr} ? 1 : 0)");
        // A domain's managed enum and the ClangSharp binding of the same C enum are two
        // declarations of one set of named integers, generated from one header. Their
        // underlying types need not match — kabic picks int, ClangSharp mirrors C's
        // unsigned — but the members and their values do, so the conversion is a cast.
        if (propertyType.TypeKind == TypeKind.Enum && fieldType.TypeKind == TypeKind.Enum)
        {
            var pn = propertyType.ToDisplayString();
            var fn = fieldType.ToDisplayString();
            return (expr => $"({pn}){expr}", expr => $"({fn}){expr}");
        }
        if (NativeHandleNames.TryGetValue(propertyType.Name, out var nativeHandle) && fieldType.Name == nativeHandle)
        {
            var pn = propertyType.ToDisplayString();
            var fn = fieldType.ToDisplayString();
            return (expr => $"global::System.Runtime.CompilerServices.Unsafe.BitCast<{fn}, {pn}>({expr})",
                    expr => $"global::System.Runtime.CompilerServices.Unsafe.BitCast<{pn}, {fn}>({expr})");
        }
        if (propertyType.ContainingNamespace?.ToDisplayString() == "System.Numerics"
            && NativeVectorNames.TryGetValue(propertyType.Name, out var nativeName)
            && fieldType.Name == nativeName)
        {
            var propName = propertyType.ToDisplayString();
            var fieldName = fieldType.ToDisplayString();
            return (expr => $"global::System.Runtime.CompilerServices.Unsafe.BitCast<{fieldName}, {propName}>({expr})",
                    expr => $"global::System.Runtime.CompilerServices.Unsafe.BitCast<{propName}, {fieldName}>({expr})");
        }
        return null;
    }

    static readonly DiagnosticDescriptor AmbiguousComponentRule = new(
        id: "KESG002",
        title: "Node property does not resolve to exactly one of the node's components",
        messageFormat: "Property '{0}' matches {1} of this node's components on field '{2}'; name the intended one with [NativeField(..., Component = typeof(...))]",
        category: "KernelEngine.SourceGenerators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    static readonly DiagnosticDescriptor UnnamedWholeRule = new(
        id: "KESG004",
        title: "Whole-struct node property does not say which component it is",
        messageFormat: "Property '{0}' is [NativeWhole] on a node declaring several components, and a whole-struct property names no field to resolve it by; add Component = typeof(...)",
        category: "KernelEngine.SourceGenerators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    static readonly DiagnosticDescriptor UnknownComponentRule = new(
        id: "KESG003",
        title: "Node property names a component the node does not declare",
        messageFormat: "Property '{0}' names component '{1}', which this node does not declare with [GeneratedNodeComponent]",
        category: "KernelEngine.SourceGenerators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    static readonly DiagnosticDescriptor NoCoercionRule = new(
        id: "KESG001",
        title: "No coercion rule for node property/native field type mismatch",
        messageFormat: "Property '{0}' is {1} but its backing field is {2}, and no coercion rule connects them",
        category: "KernelEngine.SourceGenerators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);
}
