using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace KernelEngine.SourceGenerators;

[Generator]
public sealed class NodePropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is PropertyDeclarationSyntax { Parent: ClassDeclarationSyntax } p && IsPartialAutoProperty(p),
            static (ctx, _) => (PropertyDeclarationSyntax)ctx.Node);

        var classes = candidates
            .Select(static (p, _) => (ClassDeclarationSyntax)p.Parent!)
            .Collect()
            .SelectMany(static (list, _) => list.Distinct());

        context.RegisterSourceOutput(classes.Combine(context.CompilationProvider),
            static (spc, pair) => Generate(spc, pair.Left, pair.Right));
    }

    static bool IsPartialAutoProperty(PropertyDeclarationSyntax p)
    {
        if (!p.Modifiers.Any(SyntaxKind.PartialKeyword)) return false;
        if (p.AccessorList is null) return false;
        foreach (var a in p.AccessorList.Accessors)
            if (a.Body is not null || a.ExpressionBody is not null) return false;
        return true;
    }

    static void Generate(SourceProductionContext spc, ClassDeclarationSyntax classDecl, Compilation compilation)
    {
        var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
        if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol) return;
        if (!DerivesFromNode(classSymbol)) return;

        var properties = classSymbol.GetMembers().OfType<IPropertySymbol>()
            .Where(p => p.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is PropertyDeclarationSyntax pd && IsPartialAutoProperty(pd)))
            .ToImmutableArray();
        if (properties.IsEmpty) return;

        var marker = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "GeneratedNodeComponentAttribute");

        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace ? null : classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;

        var backingTypeSymbol = marker is not null ? (INamedTypeSymbol)marker.ConstructorArguments[0].Value! : null;
        var backingType = backingTypeSymbol?.ToDisplayString() ?? $"{className}_Data";
        var componentName = marker is not null
            ? (string)marker.ConstructorArguments[1].Value!
            : $"{ns}.{className}_Data";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        if (ns is not null) sb.AppendLine($"namespace {ns};").AppendLine();

        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");

        if (marker is null)
        {
            sb.AppendLine($"    private struct {backingType}");
            sb.AppendLine("    {");
            foreach (var p in properties)
                sb.AppendLine($"        public {p.Type.ToDisplayString()} {p.Name};");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine($"    private {backingType} _generatedState;");
        sb.AppendLine("    private uint _generatedCid;");
        sb.AppendLine();

        foreach (var p in properties)
        {
            var fieldName = marker is not null ? NativeFieldNameOf(p) : p.Name;
            var fieldSymbol = backingTypeSymbol?.GetMembers(fieldName).OfType<IFieldSymbol>().FirstOrDefault();
            // ClangSharp backs a C `float x[N]` with a generated `_x_e__FixedBuffer` type —
            // only THAT shape indexes by [i]; a named ke_vecN/ke_quat field (below) is a
            // bit-cast coercion instead, even though its C# property is also Vector2/3/4.
            var isFixedBuffer = fieldSymbol is not null && fieldSymbol.Type.Name.EndsWith("_e__FixedBuffer");
            var arity = marker is not null && isFixedBuffer ? VectorArity(p.Type) : null;
            var coercion = arity is null && fieldSymbol is not null ? CoercionFor(p.Type, fieldSymbol.Type) : null;

            if (arity is null && fieldSymbol is not null && coercion is null
                && !SymbolEqualityComparer.Default.Equals(p.Type, fieldSymbol.Type))
            {
                spc.ReportDiagnostic(Diagnostic.Create(NoCoercionRule, p.Locations.FirstOrDefault(),
                    p.Name, p.Type.ToDisplayString(), fieldSymbol.Type.ToDisplayString()));
                continue;
            }

            sb.AppendLine($"    public partial {p.Type.ToDisplayString()} {p.Name}");
            sb.AppendLine("    {");
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine("            var s = GeneratedCurrent();");
            sb.AppendLine(arity is int rn
                ? $"            return new(" + string.Join(", ", Enumerable.Range(0, rn).Select(i => $"s.{fieldName}[{i}]")) + ");"
                : coercion is not null
                    ? $"            return {coercion.Value.read("s." + fieldName)};"
                    : $"            return s.{fieldName};");
            sb.AppendLine("        }");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine("            var s = GeneratedCurrent();");
            if (arity is int wn)
                foreach (var i in Enumerable.Range(0, wn))
                    sb.AppendLine($"            s.{fieldName}[{i}] = value.{VectorLanes[i]};");
            else if (coercion is not null)
                sb.AppendLine($"            s.{fieldName} = {coercion.Value.write("value")};");
            else
                sb.AppendLine($"            s.{fieldName} = value;");
            sb.AppendLine("            if (IsBound) NodeWorld!.SetByCid(Entity, _generatedCid, s); else _generatedState = s;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        sb.AppendLine();
        sb.AppendLine($"    private {backingType} GeneratedCurrent() =>");
        sb.AppendLine($"        IsBound && NodeWorld!.TryGetByCid<{backingType}>(Entity, _generatedCid, out var s) ? s : _generatedState;");
        sb.AppendLine();

        var resolveCid = marker is not null
            ? $"nodeWorld.CidOfName(\"{componentName}\")"
            : $"nodeWorld.RegisterComponent<{backingType}>(\"{componentName}\")";

        // `protected` only, not `protected internal`: a generated node type's
        // assembly (e.g. Render.Webgpu) is never the same assembly as Node's
        // (Framework), so `internal` would fail to satisfy the base member's
        // accessibility — same fix applied by hand to every other builtin node.
        sb.AppendLine("    protected override void OnBind(global::KernelEngine.Framework.NodeWorld nodeWorld)");
        sb.AppendLine("    {");
        sb.AppendLine($"        _generatedCid = {resolveCid};");
        sb.AppendLine("        nodeWorld.SetByCid(Entity, _generatedCid, _generatedState);");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        spc.AddSource($"{className}.NodeProperties.g.cs", sb.ToString());
    }

    static bool DerivesFromNode(INamedTypeSymbol symbol)
    {
        for (var t = symbol.BaseType; t is not null; t = t.BaseType)
            if (t.Name == "Node") return true;
        return false;
    }

    static readonly string[] VectorLanes = ["X", "Y", "Z", "W"];

    static string NativeFieldNameOf(IPropertySymbol property)
    {
        var attr = property.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "NativeFieldAttribute");
        return attr is not null ? (string)attr.ConstructorArguments[0].Value! : property.Name;
    }

    static int? VectorArity(ITypeSymbol type)
    {
        if (type.ContainingNamespace?.ToDisplayString() != "System.Numerics") return null;
        return type.Name switch { "Vector2" => 2, "Vector3" => 3, "Vector4" => 4, _ => null };
    }

    // ke_vec2/ke_vec3/ke_vec4/ke_quat (KernelEngine.Common.Native) are layout-identical
    // to their System.Numerics counterparts by construction (see kabic's NamedVectorTypes),
    // so the coercion is a bit-cast, not a field-by-field copy.
    static readonly Dictionary<string, string> NativeVectorNames = new()
    {
        ["Vector2"] = "ke_vec2", ["Vector3"] = "ke_vec3", ["Vector4"] = "ke_vec4", ["Quaternion"] = "ke_quat",
    };

    static (Func<string, string> read, Func<string, string> write)? CoercionFor(ITypeSymbol propertyType, ITypeSymbol fieldType)
    {
        if (propertyType.SpecialType == SpecialType.System_Boolean && fieldType.SpecialType == SpecialType.System_Byte)
            return (expr => $"{expr} != 0", expr => $"(byte)({expr} ? 1 : 0)");
        if (propertyType.ContainingNamespace?.ToDisplayString() == "System.Numerics"
            && NativeVectorNames.TryGetValue(propertyType.Name, out var nativeName)
            && fieldType.Name == nativeName)
        {
            var propName = propertyType.ToDisplayString();
            var fieldName = fieldType.ToDisplayString();
            return (expr => $"global::System.Runtime.CompilerServices.Unsafe.BitCast<{fieldName}, {propName}>({expr})",
                    expr => $"global::System.Runtime.CompilerServices.Unsafe.BitCast<{propName}, {fieldName}>({expr})");
        }
        return null;
    }

    static readonly DiagnosticDescriptor NoCoercionRule = new(
        id: "KESG001",
        title: "No coercion rule for node property/native field type mismatch",
        messageFormat: "Property '{0}' is {1} but its backing field is {2}, and no coercion rule connects them",
        category: "KernelEngine.SourceGenerators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);
}
