using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace KernelEngine.SourceGenerators;

/// <summary>
/// Emits one type per <c>.scene.toml</c> file in the project, so a scene can be named
/// to <c>ISceneRouter.LoadScene&lt;T&gt;()</c> by type instead of by string.
/// </summary>
/// <remarks>
/// <para>
/// A scene file is a prefab with an identity, and the compiler can only help with
/// an identity it knows the name of. Spelled as a string, a typo is a scene that
/// silently fails to load at runtime, and renaming the file leaves every caller
/// compiling happily against a name that no longer exists.
/// </para>
/// <para>
/// Scene types land in a <c>.Scenes</c> child namespace rather than the project's
/// own: a scene very often shares its name with the node it is built around
/// (<c>Ball.scene.toml</c> next to <c>class Ball</c>), and putting both in one
/// namespace would make the collision the caller's problem.
/// </para>
/// <para>
/// The project opts in by listing its scenes as additional files:
/// <c>&lt;AdditionalFiles Include="scenes/**/*.scene.toml" /&gt;</c>.
/// </para>
/// </remarks>
[Generator]
public sealed class SceneNameGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor SceneNameNotAnIdentifierRule = new(
        id: "KESG007",
        title: "Scene file cannot be named by type",
        messageFormat: "Scene file '{0}' has a name that is not a valid C# identifier, so no type is generated for it and LoadScene<T> cannot name it",
        category: "KernelEngine",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    /// <summary>
    /// The double extension is deliberate: the file is TOML, so declaring it lets
    /// any editor and any host validate and highlight the scene with no per-editor
    /// setup, while <c>.scene</c> keeps saying what the file is.
    /// </summary>
    private const string SceneSuffix = ".scene.toml";

    /// <summary>
    /// The scene's name: the file name with both extensions removed.
    /// <c>GetFileNameWithoutExtension</c> alone would leave <c>Main.scene</c>,
    /// which is not a type name.
    /// </summary>
    private static string SceneNameOf(string path)
    {
        var file = Path.GetFileName(path);
        return file.EndsWith(SceneSuffix, StringComparison.OrdinalIgnoreCase)
            ? file.Substring(0, file.Length - SceneSuffix.Length)
            : Path.GetFileNameWithoutExtension(file);
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var scenes = context.AdditionalTextsProvider
            .Where(static t => t.Path.EndsWith(SceneSuffix, StringComparison.OrdinalIgnoreCase))
            .Select(static (t, _) => SceneNameOf(t.Path))
            .Collect();

        var rootNamespace = context.AnalyzerConfigOptionsProvider.Select(static (p, _) =>
            p.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns) && !string.IsNullOrEmpty(ns)
                ? ns
                : null);

        context.RegisterSourceOutput(scenes.Combine(rootNamespace), static (spc, pair) =>
        {
            var (names, ns) = pair;
            if (names.IsDefaultOrEmpty || ns is null) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// One type per .scene.toml file. Do not edit; add or rename a scene file instead.");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}.Scenes;");

            // Distinct: the same scene name reaching the generator twice (a file
            // listed by two globs) would otherwise emit the type twice.
            foreach (var name in names.Distinct().OrderBy(n => n, StringComparer.Ordinal))
            {
                if (!IsIdentifier(name))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(SceneNameNotAnIdentifierRule, Location.None, name));
                    continue;
                }
                sb.AppendLine();
                sb.AppendLine($"/// <summary>The <c>{name}.scene.toml</c> file.</summary>");
                sb.AppendLine($"public sealed class {name} : global::KernelEngine.Framework.IScene");
                sb.AppendLine("{");
                sb.AppendLine($"    public static string SceneName => \"{name}\";");
                sb.AppendLine("}");
            }

            spc.AddSource("Scenes.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static bool IsIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name)) return false;
        if (!char.IsLetter(name[0]) && name[0] != '_') return false;
        for (var i = 1; i < name.Length; i++)
            if (!char.IsLetterOrDigit(name[i]) && name[i] != '_') return false;
        return true;
    }
}
