<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NativeTarget>ke_render_bgfx</NativeTarget>
  </PropertyGroup>

  <Import Project="../../NativeDependencies.targets" />

  <ItemGroup>
    <ProjectReference Include="..\..\common\KernelEngine.Common\KernelEngine.Common.csproj" />
    <ProjectReference Include="..\..\render\KernelEngine.Render\KernelEngine.Render.csproj" />
    <ProjectReference Include="..\..\configuration\KernelEngine.Configuration\KernelEngine.Configuration.csproj" />
    <ProjectReference Include="..\..\framework\KernelEngine.Framework\KernelEngine.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
  </ItemGroup>

</Project>
