// kabic's C# backend (ScriptingArchitectureV3 §6.2): renders the
// language-independent ClassifiedModel (Kabic.Core's Classifier) into
// idiomatic C# — throw, IDisposable, Span<T>, GCHandle +
// [UnmanagedCallersOnly]. Everything here decides how to SAY a slot's
// already-decided meaning; nothing here re-derives what a slot means from
// raw ApiFunction/ApiStruct shapes. A Lua/Python/Zig backend would be a
// sibling project referencing Kabic.Core the same way this one does, writing
// only its own version of this file.

namespace Kabic.CSharp;

using Kabic;

// =============================================================================
// -- §6.2 the C# backend: rendering the shared classification into C# idiom -
// =============================================================================

public static class CSharpBackend
{
    const string Header = "// <auto-generated/>\n// Derived from ke_api.json. Do not edit; edit the C header instead.\n";

    static string XmlDoc(string indent, string? summary, IEnumerable<(string Name, string? Doc)>? pars = null,
        string? ret = null, bool throwsOnFail = false)
    {
        var lines = new List<string>();
        if (!string.IsNullOrEmpty(summary)) lines.Add($"{indent}/// <summary>{Escape(summary)}</summary>");
        foreach (var (n, d) in pars ?? [])
            if (!string.IsNullOrEmpty(d)) lines.Add($"{indent}/// <param name=\"{n}\">{Escape(d)}</param>");
        if (!string.IsNullOrEmpty(ret)) lines.Add($"{indent}/// <returns>{Escape(ret)}</returns>");
        if (throwsOnFail) lines.Add($"{indent}/// <exception cref=\"KernelError\">The native call failed.</exception>");
        return lines.Count > 0 ? string.Join('\n', lines) + '\n' : "";
    }

    static string Escape(string s) => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    static string CsParamType(ApiModel model, ApiParam p, Convention convention)
    {
        var tagEnum = p.TagValue("enum");
        if (tagEnum is not null) return Idioms.TypeName(tagEnum, convention);
        // A pointer to a struct this same ke_api.json declares renders as a C#
        // pointer to that (already in-namespace) struct; anything else falls
        // back to CsForeignType's normalization (still needs a --using if it's
        // cross-domain — same rule as the factory-parameter case).
        if (CTypes.IsPointer(p.Type))
            return CTypes.Deref(p.Type) + "*";
        return Idioms.CsPrimitive(p.Type);
    }

    // -------------------------------------------------------------- enums

    public static string RenderEnums(ApiModel model, string ns, Convention convention)
    {
        var o = new List<string> { Header, $"namespace {ns};\n" };
        foreach (var e in model.Enums)
        {
            o.Add(e.Doc is not null
                ? XmlDoc("", e.Doc).TrimEnd()
                : $"/// <summary>Mirrors <c>{e.Name}</c>.</summary>");
            o.Add($"public enum {Idioms.TypeName(e.Name, convention)}");
            o.Add("{");
            foreach (var v in e.Values)
            {
                if (!string.IsNullOrEmpty(v.Doc)) o.Add($"    /// <summary>{Escape(v.Doc)}</summary>");
                var name = Idioms.EnumMember(v.Name, e.Name);
                var val = v.IsInt ? v.RawValue : Idioms.EnumMember(v.RawValue, e.Name);
                o.Add($"    {name} = {val},");
            }
            o.Add("}");
            o.Add("");
        }
        return string.Join('\n', o);
    }

    // ------------------------------------------------------------ provider

    public static string RenderProvider(ApiModel model, ApiStruct vtable, ClassifiedModel classified,
        string ns, string nativeNs, IReadOnlyList<string> extraUsings, Convention convention)
    {
        var typeName = Idioms.TypeName(vtable.Name, convention);
        var slots = classified.SlotsByVtable[vtable.Name];
        var plan = classified.Constructors[vtable.Name];

        var o = new List<string>
        {
            Header,
            "using System.Runtime.CompilerServices;", // CallConvCdecl, needed whenever a slot has a [callback] param
            "using System.Runtime.InteropServices;",
            "using KernelEngine.Common;",
            "using KernelEngine.Common.Native;",
            $"using {nativeNs};",
        };
        foreach (var u in extraUsings) o.Add($"using {u};");
        o.Add("");
        o.Add($"namespace {ns};");
        o.Add("");

        // The INativeX{ ke_x* Native } accessor is this project's sanctioned
        // cross-domain composition mechanism (see ScriptingArchitectureV3.md
        // Appendix A.1's second correction): InternalsVisibleTo is banned
        // because it forces the producer to enumerate every consumer, the
        // inversion of the inversion this project's DI doctrine forbids. A
        // public Native accessor lets any consumer opt in without the producer
        // knowing who they are. Already load-bearing, hand-written, and
        // identical in shape across a dozen domains (INativeLogger,
        // INativeWindow, ...) before kabic existed — generating it here just
        // stops it being copy-pasted per domain.
        var nativeIface = "INative" + typeName;
        o.Add($"/// <summary>Exposes the raw native {typeName.ToLowerInvariant()} pointer for cross-domain composition wiring.</summary>");
        o.Add($"public unsafe interface {nativeIface}");
        o.Add("{");
        o.Add($"    {vtable.Name}* Native {{ get; }}");
        o.Add("}");
        o.Add("");

        o.Add(XmlDoc("", vtable.Doc).TrimEnd());
        // Not sealed: at least one provider (EnkiScheduler : Scheduler) is
        // legitimately subclassed by a backend layering its own native
        // construction on top of the generic wrapper. Sealing by default
        // would have been a restriction kabic imposed with no ABI basis for
        // it — the C type says nothing about whether the managed wrapper
        // should be inheritable.
        o.Add($"public unsafe partial class {typeName} : IDisposable, {nativeIface}");
        o.Add("{");
        o.Add($"    private {vtable.Name}* _native;");
        o.Add($"    private readonly delegate* unmanaged[Cdecl]<{vtable.Name}*, void> _destroy;");
        o.Add("");
        o.Add($"    private {vtable.Name}* Handle => _native != null ? _native");
        o.Add($"        : throw new ObjectDisposedException(nameof({typeName}));");
        o.Add("");
        o.Add($"    {vtable.Name}* {nativeIface}.Native => Handle;");
        o.Add("");

        classified.LifecycleInit.TryGetValue(vtable.Name, out var initSlot);
        classified.LifecycleShutdown.TryGetValue(vtable.Name, out var shutdownSlot);
        var initCall = initSlot is not null
            ? $"        {{ ke_error* err2 = null; KernelError.ThrowIfFailed(_native->{initSlot}(_native, &err2), err2, \"{initSlot}\"); }}"
            : null;

        if (plan.Kind == ConstructorKind.FromFactory)
        {
            var factory = plan.Factory!;
            var fparams = factory.Params.Where(p => !convention.IsErrorOutParam(p)).ToList();
            var sig = string.Join(", ", fparams.Select(p => $"{Idioms.CsForeignType(p.Type)} {Idioms.Ident(p.Name!)}"));
            var call = string.Join(", ", fparams.Select(p => Idioms.Ident(p.Name!)));
            o.Add(XmlDoc("    ", factory.Doc, fparams.Select(p => (Idioms.Ident(p.Name!), p.Doc)),
                throwsOnFail: true).TrimEnd());
            // internal only when a param is a raw pointer from a sibling native
            // layer that a managed caller cannot supply without an unsafe
            // context (the hand-written idiom partial then exposes a public
            // constructor form instead). Decided once in Classifier
            // (plan.NeedsWrapper), not re-derived here.
            o.Add($"    {(plan.NeedsWrapper ? "internal" : "public")} {typeName}({sig})");
            o.Add("    {");
            o.Add("        ke_error* err = null;");
            o.Add($"        var handle = {nativeNs}.NativeMethods.{convention.StripPrefix(factory.Name)}({(call.Length > 0 ? call + ", " : "")}&err);");
            o.Add($"        if (handle.@ref == null) throw KernelError.FromNative(err, \"{factory.Name}\");");
            o.Add("        _native = handle.@ref;");
            o.Add("        _destroy = handle.destroy;");
            if (initCall is not null) o.Add(initCall);
            o.Add("    }");
            o.Add("");
        }
        else if (plan.Kind == ConstructorKind.FromHandle)
        {
            var handleType = plan.HandleTypeName!;
            // ke_window's shape: no factory of its own — any backend (GLFW, ...)
            // hands back a ke_window_handle, and construction is generic over
            // that handle rather than tied to one specific creator function.
            // Public, unlike the factory ctor above: a ke_X_handle is a plain
            // managed-visible value type this wrapper itself owns the shape of,
            // not a raw pointer into a sibling native namespace — any assembly
            // holding a valid handle (from calling a backend's own factory) can
            // legitimately construct the wrapper directly.
            o.Add($"    /// <summary>Wraps an owner <c>{handleType}</c> and runs {typeName.ToLowerInvariant()}'s startup lifecycle hook.</summary>");
            if (initCall is not null) o.Add("    /// <exception cref=\"KernelError\">The native call failed.</exception>");
            o.Add($"    public {typeName}({handleType} handle)");
            o.Add("    {");
            o.Add("        _native = handle.@ref;");
            o.Add("        _destroy = handle.destroy;");
            if (initCall is not null) o.Add(initCall);
            o.Add("    }");
            o.Add("");
        }

        foreach (var cs in slots)
        {
            // [sink]: a backend-facing event callback (e.g. ke_input.on_key), not
            // game-facing API. [lifecycle:*]: invoked automatically below, not
            // meant to be called again by the consumer. [raw_callback]: a bare
            // C function-pointer parameter (not a [callback] vtable-by-value
            // struct) — trampolining it generically buys nothing, since the
            // value surface a caller actually wants (Task/async, a coroutine,
            // whatever this language's idiom is) can't be inferred from the
            // ABI either way; left to the idiom layer entirely.
            if (cs.Slot.Has("sink") || cs.Slot.Has("lifecycle")
                || cs.PublicParams.Any(p => p.Has("raw_callback")))
                continue;
            if (cs.PublicParams.Any(p => classified.Callbacks.Any(c => c.Name == p.Type.Trim())))
            {
                RenderCallbackMethod(o, vtable, cs, classified, typeName, convention);
                continue;
            }
            RenderSlotMethod(model, o, cs, convention);
        }

        o.Add($"    /// <summary>Releases the native {typeName.ToLowerInvariant()}.</summary>");
        o.Add("    public void Dispose()");
        o.Add("    {");
        o.Add("        if (_native == null) return;");
        if (shutdownSlot is not null)
            o.Add($"        _native->{shutdownSlot}(_native, null);");
        o.Add("        _destroy(_native);");
        o.Add("        _native = null;");
        o.Add("    }");
        o.Add("}");
        o.Add("");
        return string.Join('\n', o);
    }

    static void RenderSlotMethod(ApiModel model, List<string> o, ClassifiedSlot cs, Convention convention)
    {
        var slot = cs.Slot;
        var name = Idioms.Pascal(slot.Name);

        switch (cs.Shape)
        {
            case SlotShape.ReturnsOutParam:
            {
                var ret = CTypes.Deref(cs.OutParam!.Type);
                o.Add(XmlDoc("    ", slot.Doc, ret: slot.ReturnDoc, throwsOnFail: cs.Fallible).TrimEnd());
                o.Add($"    public {ret} {name}()");
                o.Add("    {");
                o.Add($"        {ret} result;");
                if (cs.Fallible)
                {
                    o.Add("        ke_error* err = null;");
                    o.Add($"        KernelError.ThrowIfFailed(Handle->{slot.Name}(Handle, &result, &err), err, \"{slot.Name}\");");
                }
                else
                {
                    o.Add($"        Handle->{slot.Name}(Handle, &result);");
                }
                o.Add("        return result;");
                o.Add("    }");
                o.Add("");
                return;
            }
            case SlotShape.TupleOutParams:
            {
                // e.g. ke_window.get_size(int32_t *width, int32_t *height, ke_error**)
                // -> (int Width, int Height) GetSize() — a tuple return, not a Span
                // (the values are independent scalars, not a homogeneous sequence).
                var names = cs.OutParams.Select(p => Idioms.Pascal(p.Name!)).ToList();
                var types = cs.OutParams.Select(p => Idioms.CsPrimitive(CTypes.Deref(p.Type))).ToList();
                var retTuple = string.Join(", ", types.Zip(names, (t, n) => $"{t} {n}"));
                var locals = cs.OutParams.Select(p => Idioms.Ident(p.Name!)).ToList();
                var callArgs = string.Concat(locals.Select(n => $", &{n}"));

                o.Add(XmlDoc("    ", slot.Doc, throwsOnFail: cs.Fallible).TrimEnd());
                o.Add($"    public ({retTuple}) {name}()");
                o.Add("    {");
                foreach (var (t, n) in types.Zip(locals)) o.Add($"        {t} {n};");
                if (cs.Fallible)
                {
                    o.Add("        ke_error* err = null;");
                    o.Add($"        KernelError.ThrowIfFailed(Handle->{slot.Name}(Handle{callArgs}, &err), err, \"{slot.Name}\");");
                }
                else
                {
                    o.Add($"        Handle->{slot.Name}(Handle{callArgs});");
                }
                o.Add($"        return ({string.Join(", ", locals)});");
                o.Add("    }");
                o.Add("");
                return;
            }
            case SlotShape.Sequence:
            {
                var elem = CTypes.Deref(cs.SequenceParam!.Type);
                var pname = Idioms.Ident(cs.SequenceParam!.Name!);
                var otherArgs = cs.PublicParams.Where(p => p != cs.SequenceParam).ToList();
                var extra = string.Concat(otherArgs.Select(p => $", (uint){pname}.Length"));
                o.Add(XmlDoc("    ", slot.Doc, [(pname, cs.SequenceParam.Doc)], slot.ReturnDoc).TrimEnd());
                o.Add($"    public int {name}Raw(Span<{elem}> {pname})");
                o.Add("    {");
                o.Add($"        fixed ({elem}* p = {pname})");
                o.Add($"            return (int)Handle->{slot.Name}(Handle, p{extra});");
                o.Add("    }");
                o.Add("");
                return;
            }
            case SlotShape.Fallible:
            {
                var args = cs.PublicParams;
                var sig = string.Join(", ", args.Select(p => $"{CsParamType(model, p, convention)} {Idioms.Ident(p.Name!)}"));
                var call = string.Concat(args.Select(p => ", " + CallArg(p)));
                o.Add(XmlDoc("    ", slot.Doc, args.Select(p => (Idioms.Ident(p.Name!), p.Doc)),
                    slot.ReturnDoc, throwsOnFail: true).TrimEnd());
                o.Add($"    public void {name}({sig})");
                o.Add("    {");
                o.Add("        ke_error* err = null;");
                o.Add($"        KernelError.ThrowIfFailed(Handle->{slot.Name}(Handle{call}, &err), err, \"{slot.Name}\");");
                o.Add("    }");
                o.Add("");
                return;
            }
            default:
            {
                var args = cs.PublicParams;
                var sig = string.Join(", ", args.Select(p => $"{CsParamType(model, p, convention)} {Idioms.Ident(p.Name!)}"));
                var call = string.Concat(args.Select(p => ", " + CallArg(p)));
                var retType = slot.Returns == "ke_bool" ? "bool" : Idioms.CsPrimitive(slot.Returns);
                var needsCast = retType == "nint"; // CsPrimitive maps `void *` -> nint; the raw call still returns void*
                o.Add(XmlDoc("    ", slot.Doc, args.Select(p => (Idioms.Ident(p.Name!), p.Doc)), slot.ReturnDoc).TrimEnd());
                o.Add($"    public {retType} {name}({sig})");
                o.Add("    {");
                if (slot.Returns == "ke_bool")
                    o.Add($"        return Handle->{slot.Name}(Handle{call}) != 0;");
                else if (retType == "void")
                    o.Add($"        Handle->{slot.Name}(Handle{call});");
                else if (needsCast)
                    o.Add($"        return (nint)Handle->{slot.Name}(Handle{call});");
                else
                    o.Add($"        return Handle->{slot.Name}(Handle{call});");
                o.Add("    }");
                o.Add("");
                return;
            }
        }

        string CallArg(ApiParam p) => p.Has("enum") ? $"({Idioms.CsPrimitive(p.Type)}){Idioms.Ident(p.Name!)}" : Idioms.Ident(p.Name!);
    }

    // ----------------------------------------------------- callback slot

    static void RenderCallbackMethod(List<string> o, ApiStruct vtable, ClassifiedSlot cs,
        ClassifiedModel classified, string ownerType, Convention convention)
    {
        var slot = cs.Slot;
        var cbParam = cs.PublicParams.First(p => classified.Callbacks.Any(c => c.Name == p.Type.Trim()));
        var cbType = classified.Callbacks.First(c => c.Name == cbParam.Type.Trim());
        var ifaceName = "I" + Idioms.TypeName(cbType.Name, convention) + "Native";
        var hasLevel = classified.CallbackHasLevel.GetValueOrDefault(cbType.Name);
        var handlesField = $"_{Idioms.Camel(slot.Name)}Handles";
        var otherParams = cs.PublicParams.Where(p => p != cbParam).ToList();

        o.Add(XmlDoc("    ", slot.Doc, [(Idioms.Ident(cbParam.Name!), cbParam.Doc)], throwsOnFail: true).TrimEnd());
        o.Add($"    // Roots each managed callback implementation for as long as native code");
        o.Add($"    // holds a pointer to it; released by the destroy trampoline below.");
        o.Add($"    private readonly List<GCHandle> {handlesField} = [];");
        o.Add("");
        var lvlArg = hasLevel ? ", int minLevel = 0" : "";
        var otherArgs = string.Concat(otherParams.Select(p => $", {CsParamType2(p)} {Idioms.Ident(p.Name!)}"));
        o.Add($"    public void {Idioms.Pascal(slot.Name)}({ifaceName} {Idioms.Ident(cbParam.Name!)}{otherArgs}{lvlArg})");
        o.Add("    {");
        o.Add($"        var gch = GCHandle.Alloc({Idioms.Ident(cbParam.Name!)});");
        o.Add($"        {handlesField}.Add(gch);");
        o.Add($"        var native = new {cbType.Name}");
        o.Add("        {");
        o.Add("            handle = GCHandle.ToIntPtr(gch).ToPointer(),");
        if (hasLevel) o.Add("            min_level = minLevel,");
        foreach (var s in cbType.Slots)
            o.Add($"            {s.Name} = &{Idioms.Pascal(s.Name)}Trampoline,");
        o.Add("        };");
        o.Add("        ke_error* err = null;");
        var extraCall = string.Concat(otherParams.Select(p => ", " + Idioms.Ident(p.Name!)));
        o.Add($"        KernelError.ThrowIfFailed(Handle->{slot.Name}(Handle, native{extraCall}, &err), err, \"{slot.Name}\");");
        o.Add("    }");
        o.Add("");

        // A second overload, forwarding an already-built value straight through
        // with no GCHandle/trampoline wrapping: for a callback-vtable VALUE that
        // came from a native value-factory (e.g. ke_console_sink_create(), see
        // ClassifiedModel.FreeFunctionGroups) rather than a managed
        // implementation of the interface above.
        var cbParamCsType = CTypes.Deref(cbParam.Type);
        o.Add($"    /// <summary>{slot.Doc} Takes an already-built <c>{cbType.Name}</c> value directly — for one produced by a native factory, not a managed <see cref=\"{ifaceName}\"/>.</summary>");
        o.Add(XmlDoc("    ", null, otherParams.Select(p => (Idioms.Ident(p.Name!), p.Doc)), throwsOnFail: true).TrimEnd());
        o.Add($"    public void {Idioms.Pascal(slot.Name)}Raw({cbParamCsType} {Idioms.Ident(cbParam.Name!)}{otherArgs})");
        o.Add("    {");
        o.Add("        ke_error* err = null;");
        o.Add($"        KernelError.ThrowIfFailed(Handle->{slot.Name}(Handle, {Idioms.Ident(cbParam.Name!)}{extraCall}, &err), err, \"{slot.Name}\");");
        o.Add("    }");
        o.Add("");

        foreach (var s in cbType.Slots)
        {
            var trampParams = s.Params.Select(p =>
                (CTypes.IsPointer(p.Type) ? $"{CTypes.Deref(p.Type)}*" : Idioms.CsPrimitive(p.Type)) + " " + Idioms.Ident(p.Name!));
            var sig = string.Join(", ", new[] { $"{cbType.Name}* self" }.Concat(trampParams));
            o.Add("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]");
            o.Add($"    private static {Idioms.CsPrimitive(s.Returns)} {Idioms.Pascal(s.Name)}Trampoline({sig})");
            o.Add("    {");
            if (s.Name == "destroy")
            {
                o.Add("        GCHandle.FromIntPtr((nint)self->handle).Free();");
            }
            else
            {
                var callArgs = string.Concat(s.Params.Select(p =>
                    ", " + (CTypes.IsPointer(p.Type) ? $"in *{Idioms.Ident(p.Name!)}" : Idioms.Ident(p.Name!))));
                o.Add($"        var target = ({ifaceName})GCHandle.FromIntPtr((nint)self->handle).Target!;");
                o.Add($"        target.{Idioms.Pascal(s.Name)}({callArgs.TrimStart(',', ' ')});");
            }
            o.Add("    }");
            o.Add("");
        }

        string CsParamType2(ApiParam p) => p.Has("enum") ? Idioms.TypeName(p.TagValue("enum")!, convention) : Idioms.CsPrimitive(p.Type);
    }

    public static string RenderCallbackInterface(ApiStruct cbType, string ns, string nativeNs, Convention convention)
    {
        var ifaceName = "I" + Idioms.TypeName(cbType.Name, convention) + "Native";
        var owned = cbType.Slots.Where(s => s.Name != "destroy").ToList();

        var o = new List<string>
        {
            Header,
            $"using {nativeNs};",
            "",
            $"namespace {ns};",
            "",
        };
        o.Add(XmlDoc("", cbType.Doc).TrimEnd());
        o.Add($"public unsafe interface {ifaceName}");
        o.Add("{");
        foreach (var s in owned)
        {
            o.Add(XmlDoc("    ", s.Doc).TrimEnd());
            var ps = string.Join(", ", s.Params.Select(p =>
                (CTypes.IsPointer(p.Type) ? $"in {CTypes.Deref(p.Type)}" : Idioms.CsPrimitive(p.Type)) + " " + Idioms.Ident(p.Name!)));
            o.Add($"    {Idioms.CsPrimitive(s.Returns)} {Idioms.Pascal(s.Name)}({ps});");
        }
        o.Add("}");
        o.Add("");
        return string.Join('\n', o);
    }

    // -------------------------------------------------------- free functions

    public static string RenderFreeFunctions(string owner, List<GroupedFunction> fns, string ns, string nativeNs,
        string libraryName, Convention convention)
    {
        var ownerCs = Idioms.TypeName(owner, convention);
        var prefix = owner + "_";

        var o = new List<string>
        {
            Header,
            "using System.Runtime.InteropServices;",
            "",
            $"namespace {ns};",
            "",
            $"/// <summary>Free-function operations on <see cref=\"{owner}\"/>.</summary>",
            $"public static unsafe class {ownerCs}",
            "{",
        };

        // Two shapes share this file: an operation ON a value type (self is the
        // group's own owner, taken `in`/by-ref — ke_input_snapshot_is_key_down),
        // and a plain factory producing one BY VALUE with no owner param at all
        // (ke_console_sink_create() -> ke_logger_sink). Which one, per function,
        // was already decided once in Classifier (GroupedFunction.SelfParam).
        foreach (var g in fns)
        {
            var f = g.Fn;
            var self = g.SelfParam;
            var rest = self is not null ? f.Params.Skip(1).ToList() : f.Params;
            // Not every value-factory function follows the {owner}_{verb} naming
            // convention (ke_console_sink_create doesn't start with ke_logger_sink_);
            // fall back to stripping the generic ke_ prefix so it still reads as a
            // method name instead of repeating the whole C symbol.
            var strippedName = f.Name.StartsWith(prefix) ? f.Name[prefix.Length..]
                : convention.StripPrefix(f.Name);
            var methodName = Idioms.Pascal(strippedName);
            var sig = string.Join(", ", rest.Select(p =>
                (p.Has("enum") ? Idioms.TypeName(p.TagValue("enum")!, convention) : Idioms.CsPrimitive(p.Type)) + " " + Idioms.Ident(p.Name!)));
            var call = string.Concat(rest.Select(p => ", " + (p.Has("enum") ? $"(int){Idioms.Ident(p.Name!)}" : Idioms.Ident(p.Name!))));
            var retType = f.Returns == "ke_bool" ? "bool" : Idioms.CsPrimitive(f.Returns);
            var selfSig = self is not null ? $"in {CTypes.Deref(self.Type)} {Idioms.Ident(self.Name!)}" : null;
            var fullSig = string.Join(", ", new[] { selfSig }.Where(s => s is not null).Append(sig).Where(s => s!.Length > 0));

            o.Add(XmlDoc("    ", f.Doc, rest.Select(p => (Idioms.Ident(p.Name!), p.Doc))).TrimEnd());
            o.Add($"    public static {retType} {methodName}({fullSig})");
            o.Add("    {");
            if (self is not null)
            {
                o.Add($"        fixed ({CTypes.Deref(self.Type)}* p = &{Idioms.Ident(self.Name!)})");
                o.Add((f.Returns == "ke_bool" ? $"            return Native.{f.Name}(p{call}) != 0;"
                                               : $"            return Native.{f.Name}(p{call});"));
            }
            else
            {
                var call2 = string.Join(", ", rest.Select(p => p.Has("enum") ? $"(int){Idioms.Ident(p.Name!)}" : Idioms.Ident(p.Name!)));
                o.Add((f.Returns == "ke_bool" ? $"        return Native.{f.Name}({call2}) != 0;"
                                               : $"        return Native.{f.Name}({call2});"));
            }
            o.Add("    }");
            o.Add("");
        }

        // Declared directly here (not via the ClangSharp-generated NativeMethods,
        // which only covers what the .rsp knew about at its last regen) so these
        // stay in sync with ke_api.json without waiting on a separate binding run.
        o.Add("    private static unsafe class Native");
        o.Add("    {");
        foreach (var g in fns)
        {
            var f = g.Fn;
            var rest = (g.SelfParam is not null ? f.Params.Skip(1) : f.Params)
                .Select(p => $"{(p.Has("enum") ? "int" : Idioms.CsPrimitive(p.Type))} {Idioms.Ident(p.Name!)}").ToList();
            var selfParamSig = g.SelfParam is not null ? $"{CTypes.Deref(f.Params[0].Type)}* {Idioms.Ident(f.Params[0].Name!)}" : null;
            var nativeSig = string.Join(", ", (selfParamSig is not null ? [selfParamSig] : Array.Empty<string>()).Concat(rest));
            o.Add($"        [DllImport(\"{libraryName}\", CallingConvention = CallingConvention.Cdecl,");
            o.Add($"                   EntryPoint = \"{f.Name}\", ExactSpelling = true)]");
            o.Add($"        public static extern {(f.Returns == "ke_bool" ? "byte" : Idioms.CsPrimitive(f.Returns))} {f.Name}({nativeSig});");
            o.Add("");
        }
        o.Add("    }");
        o.Add("}");
        o.Add("");
        return string.Join('\n', o);
    }


}

