
namespace Kabic.CSharp;

using System.Text.RegularExpressions;
using Kabic;

public static class CSharpBackend
{
    const string Header = "// <auto-generated/>\n// Derived from ke_api.json. Do not edit; edit the C header instead.\n";

    static string XmlDoc(string indent, string? summary, IEnumerable<(string Name, string? Doc)>? pars = null,
        string? ret = null, bool throwsOnFail = false)
    {
        var lines = new List<string>();
        if (!string.IsNullOrEmpty(summary)) lines.Add($"{indent}/// <summary>{Escape(summary)}</summary>");
        foreach (var (n, d) in pars ?? [])
            if (!string.IsNullOrEmpty(d)) lines.Add($"{indent}/// <param name=\"{n}\">{Escape(d)}</param>");
        if (!string.IsNullOrEmpty(ret)) lines.Add($"{indent}/// <returns>{Escape(ret)}</returns>");
        if (throwsOnFail) lines.Add($"{indent}/// <exception cref=\"KernelError\">The native call failed.</exception>");
        return lines.Count > 0 ? string.Join('\n', lines) + '\n' : "";
    }

    static string Escape(string s) => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    /// Emits the `fixed` pinning prologue encoding every [utf8] parameter as a
    /// NUL-terminated byte buffer, returning the lines and the number of braces
    /// the caller must close.
    static (List<string> Lines, int Depth) Utf8Prologue(IEnumerable<ApiParam> ps, string indent)
    {
        var lines = new List<string>();
        var depth = 0;
        foreach (var p in ps.Where(x => x.Has("utf8")))
        {
            var n = Idioms.Ident(p.Name!);
            lines.Add($"{indent}var {n}Bytes = System.Text.Encoding.UTF8.GetBytes({n} + '\\0');");
            lines.Add($"{indent}fixed (byte* {n}Ptr = {n}Bytes)");
            lines.Add($"{indent}{{");
            depth++;
        }
        return (lines, depth);
    }

    /// Emits the `fixed` pinning prologue for every pointer+count pair, returning the
    /// lines and the number of braces the caller must close. Composes with the [utf8]
    /// prologue: both only open blocks, in whatever order the caller emits them.
    static (List<string> Lines, int Depth) SequencePrologue(ApiModel model,
        IEnumerable<SequencePair> seqs, string indent, Convention convention)
    {
        var lines = new List<string>();
        var depth = 0;
        foreach (var s in seqs)
        {
            var n = Idioms.Ident(s.Seq.Name!);
            var at = indent + new string(' ', depth * 4);
            lines.Add($"{at}fixed ({SequenceElement(model, s, convention)}* {n}Ptr = {n})");
            lines.Add($"{at}{{");
            depth++;
        }
        return (lines, depth);
    }

    /// The element type a sequence parameter is spelled with. A <c>[value]</c> element
    /// takes its managed mirror, so a caller composes the span out of the projection it
    /// already holds rather than the native spelling of the same bytes.
    static string SequenceElement(ApiModel model, SequencePair s, Convention convention) =>
        ValueTypeName(model, StripQualifiers(CTypes.Deref(s.Seq.Type)), convention);

    /// The pinned pointer a sequence parameter hands the vtable. A <c>[value]</c> element is
    /// pinned as its managed mirror, which the slot takes under the native spelling of the
    /// same bytes -- so the cast is between two projections of one declaration, not between
    /// a generated type and a hand-written guess at its layout.
    static string SequenceArg(ApiModel model, SequencePair s, Convention convention)
    {
        var n = Idioms.Ident(s.Seq.Name!);
        var native = CsType(model, CTypes.Deref(s.Seq.Type));
        return SequenceElement(model, s, convention) == native ? $"{n}Ptr" : $"({native}*){n}Ptr";
    }

    static string StripQualifiers(string cType)
    {
        var t = cType.Trim();
        if (t.StartsWith("const ", StringComparison.Ordinal)) t = t["const ".Length..];
        if (t.StartsWith("struct ", StringComparison.Ordinal)) t = t["struct ".Length..];
        return t.Trim();
    }

    /// A C type mapped to C#. Typedef aliases resolve first; pointers recurse so
    /// `const`/`struct` qualifiers are dropped and the pointee receives the same
    /// mapping as any other type. An opaque `void *` maps to `nint`.
    static string CsType(ApiModel model, string cType)
    {
        var t = cType.Trim();
        if (t is "void *" or "void*") return "nint";
        if (CTypes.IsPointer(t))
        {
            var inner = CTypes.Deref(t).Trim();
            if (inner.StartsWith("const ")) inner = inner["const ".Length..];
            if (inner.StartsWith("struct ")) inner = inner["struct ".Length..];
            return CsType(model, inner) + "*";
        }
        var resolved = model.ResolveAlias(t);
        return FunctionPointerType(model, resolved) ?? Idioms.CsPrimitive(resolved);
    }

    /// A C function-pointer type (`void (*)(ke_ecs *, void *)`) as a C# function
    /// pointer. The C name is only ever an alias, so leaving it verbatim emits an
    /// identifier that resolves to nothing; the callable type has to be spelled out.
    static string? FunctionPointerType(ApiModel model, string cType)
    {
        var m = Regex.Match(cType.Trim(), @"^(.+?)\s*\(\s*\*\s*\)\s*\((.*)\)$");
        if (!m.Success) return null;

        var returns = CsType(model, m.Groups[1].Value);
        var paramList = m.Groups[2].Value.Trim();
        var parameters = paramList is "" or "void"
            ? []
            : paramList.Split(',').Select(p => CsType(model, p)).ToList();

        return $"delegate* unmanaged[Cdecl]<{string.Join(", ", parameters.Append(returns))}>";
    }

    static string CsParamType(ApiModel model, ApiParam p, Convention convention)
    {
        var tagEnum = p.TagValue("enum");
        if (tagEnum is not null)
        {
            var named = Idioms.TypeName(tagEnum, convention);
            return CTypes.IsPointer(p.Type) ? named + "*" : named;
        }
        if (p.Has("utf8")) return "string";
        if (p.Has("rooted")) return "object";
        if (p.Has("opaque")) return "void*";
        if (p.Has("ctx")) return "nint";
        if (model.Enums.Any(e => e.Name == p.Type.Trim()))
            return Idioms.TypeName(p.Type.Trim(), convention);
        return CsType(model, p.Type);
    }

    /// <summary>
    /// Emits only the declaration a game-facing node type needs: the
    /// <see cref="GeneratedNodeComponentAttribute"/> marker, the partial property
    /// signatures, and the constructor seeding <c>[default:]</c> values. Accessor bodies,
    /// the backing field, and <c>OnBind</c> are <c>KernelEngine.SourceGenerators</c>'s job —
    /// the same generator a game-authored node type with no header uses, so this type and
    /// a hand-written one are indistinguishable to it once both compile down to a
    /// <c>partial</c> class with <c>partial</c> properties.
    /// </summary>
    public static string RenderNodeType(ApiModel model, ApiStruct component, string ns, string nativeNs,
        IEnumerable<string> extraUsings, Convention convention)
    {
        var nodeName = component.TagValue("node") ?? throw new InvalidOperationException($"{component.Name} has no [node:] tag");
        var nativeType = component.Name;
        var componentName = convention.ComponentNameFor(component.Name);

        var baseName = BaseNodeOf(model, component) ?? "Node";

        var o = new List<string> { Header, "using System.Numerics;", "using KernelEngine.Common.Native;" };
        if (nativeNs != "KernelEngine.Common.Native") o.Add($"using {nativeNs};");
        foreach (var u in extraUsings) o.Add($"using {u};");
        o.Add("");
        o.Add($"namespace {ns};\n");
        o.Add(component.Doc is not null ? XmlDoc("", component.Doc).TrimEnd()
            : $"/// <summary>Mirrors <c>{nativeType}</c>.</summary>");
        o.Add($"[GeneratedNodeComponent(typeof({nativeType}), \"{componentName}\")]");
        o.Add($"public partial class {nodeName} : {baseName}");
        o.Add("{");

        var slots = new List<ApiStruct> { component };

        o.Add($"    public {nodeName}()");
        o.Add("    {");
        for (var i = 0; i < slots.Count; i++)
            foreach (var line in ComponentInit(model, slots[i], i)) o.Add($"        {line}");
        o.Add("    }");

        foreach (var c in slots)
            foreach (var line in ComponentSurface(model, c, convention)) o.Add(line);

        o.Add("}");
        return string.Join('\n', o);
    }

    /// <summary>
    /// Emits the one call that registers every node type this domain renders, so a
    /// scene naming any of them resolves without a hand-kept list.
    /// </summary>
    /// <remarks>
    /// The registration and the type it registers now come from the same input: adding
    /// a <c>[node:]</c>-tagged struct to a header registers it. The hand-maintained
    /// alternative fails silently in the worst possible place — the scene loader,
    /// at runtime, on a name it cannot resolve, long after the header was written.
    /// </remarks>
    public static string RenderNodeTypeRegistrar(string registrarName, IEnumerable<string> nodeNames, string ns)
    {
        var o = new List<string>
        {
            Header,
            "using Microsoft.Extensions.DependencyInjection;",
            "",
            $"namespace {ns};",
            "",
            $"/// <summary>Registers every node type generated for this domain.</summary>",
            $"public static class {registrarName}",
            "{",
            $"    /// <summary>Registers this domain's node types with the scene node registry.</summary>",
            $"    public static IServiceCollection Add{registrarName}(this IServiceCollection services)",
            "    {",
        };
        foreach (var n in nodeNames) o.Add($"        services.AddNodeType<{n}>();");
        o.Add("        return services;");
        o.Add("    }");
        o.Add("}");
        return string.Join('\n', o);
    }

    /// <summary>
    /// The node type this one extends, or null when it extends <c>Node</c> itself.
    /// </summary>
    static string? BaseNodeOf(ApiModel model, ApiStruct component)
    {
        var spec = component.TagValue("base");
        if (spec is null) return null;
        if (spec.Contains('+'))
            throw new InvalidOperationException($"{component.Name}: [base:] names one node type, not '{spec}'");
        _ = model.Structs.FirstOrDefault(x => x.TagValue("node") == spec)
            ?? throw new InvalidOperationException(
                $"{component.Name} extends '{spec}', which no [node:] struct in this domain declares; "
                + "add its header to the domain's composeHeaders");
        return spec;
    }

    /// <summary>The <c>[default:]</c> seeding for one component, targeting its own backing slot.</summary>
    static IEnumerable<string> ComponentInit(ApiModel model, ApiStruct c, int index)
    {
        foreach (var f in c.Fields)
            foreach (var line in FieldInit(model, f, index)) yield return line;
    }

    /// <summary>
    /// One component's contribution to the node's flat property surface. Every property
    /// names the component it belongs to, so the Roslyn generator routes it without having
    /// to resolve a field name that two composed components could both declare.
    /// </summary>
    static IEnumerable<string> ComponentSurface(ApiModel model, ApiStruct c, Convention convention)
    {
        foreach (var f in c.Fields)
        {
            if (f.Has("idiom")) continue;

            var propName = Idioms.Pascal(f.TagValue("name") ?? f.Name);
            var propType = NodePropertyType(model, f, convention);
            yield return "";
            if (!string.IsNullOrEmpty(f.Doc)) yield return $"    /// <summary>{Escape(f.Doc)}</summary>";
            yield return $"    [NativeField(\"{f.Name}\", Component = typeof({c.Name}))]";
            yield return $"    public partial {propType} {propName} {{ get; set; }}";
        }
    }

    static int? VectorArity(string cType)
    {
        var m = System.Text.RegularExpressions.Regex.Match(cType.Trim(), @"^float\s*\[(\d+)\]$");
        return m.Success && int.Parse(m.Groups[1].Value) is >= 2 and <= 4 ? int.Parse(m.Groups[1].Value) : null;
    }

    static readonly Dictionary<string, (string CsType, string[] Lanes)> NamedVectorTypes = new()
    {
        ["ke_vec2"] = ("Vector2", ["x", "y"]),
        ["ke_vec3"] = ("Vector3", ["x", "y", "z"]),
        ["ke_vec4"] = ("Vector4", ["x", "y", "z", "w"]),
        ["ke_quat"] = ("Quaternion", ["x", "y", "z", "w"]),
    };

    static readonly Dictionary<string, string> NamedHandleTypes = new()
    {
        ["ke_mesh_handle"] = "KernelEngine.Render.MeshHandle",
        ["ke_material_handle"] = "KernelEngine.Render.MaterialHandle",
        ["ke_texture_handle"] = "KernelEngine.Render.TextureHandle",
        ["ke_ui_font_handle"] = "KernelEngine.Render.FontHandle",
    };

    static bool IsCharArray(string cType) =>
        System.Text.RegularExpressions.Regex.IsMatch(cType.Trim(), @"^(const\s+)?char\s*\[\d+\]$");

    static string NodePropertyType(ApiModel model, ApiField f, Convention convention) =>
        IsCharArray(f.Type) ? "string" :
        NamedHandleTypes.TryGetValue(f.Type.Trim(), out var h) ? h :
        VectorArity(f.Type) is int n ? $"Vector{n}"
        : NamedVectorTypes.TryGetValue(f.Type.Trim(), out var v) ? v.CsType
        : model.Enums.Any(e => e.Name == f.Type.Trim()) ? Idioms.TypeName(f.Type.Trim(), convention)
        : f.Has("bool") ? "bool" : CsType(model, f.Type);

    static IEnumerable<string> FieldInit(ApiModel model, ApiField f, int index)
    {
        var d = f.TagValue("default");
        if (d is null) return [];
        if (VectorArity(f.Type) is int n)
        {
            var parts = d.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            if (parts.Length != n)
                throw new InvalidOperationException(
                    $"{f.Name}: [default:{d}] has {parts.Length} components but the field is float[{n}]");
            return parts.Select((p, i) => $"_generatedState{index}.{f.Name}[{i}] = {p}f;");
        }
        if (NamedVectorTypes.TryGetValue(f.Type.Trim(), out var v))
        {
            var parts = d.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            if (parts.Length != v.Lanes.Length)
                throw new InvalidOperationException(
                    $"{f.Name}: [default:{d}] has {parts.Length} components but the field is {f.Type.Trim()}");
            var inits = string.Join(", ", v.Lanes.Zip(parts, (lane, p) => $"{lane} = {p}f"));
            return [$"_generatedState{index}.{f.Name} = new {f.Type.Trim()} {{ {inits} }};"];
        }
        return [$"_generatedState{index}.{f.Name} = {(CsType(model, f.Type) is "float" ? d + "f" : d)};"];
    }

    public static string RenderEnums(ApiModel model, string ns, Convention convention)
    {
        var o = new List<string> { Header, $"namespace {ns};\n" };
        foreach (var e in model.Enums.Where(e => !e.External))
        {
            o.Add(e.Doc is not null
                ? XmlDoc("", e.Doc).TrimEnd()
                : $"/// <summary>Mirrors <c>{e.Name}</c>.</summary>");
            o.Add($"public enum {Idioms.TypeName(e.Name, convention)}");
            o.Add("{");
            foreach (var v in e.Values)
            {
                if (!string.IsNullOrEmpty(v.Doc)) o.Add($"    /// <summary>{Escape(v.Doc)}</summary>");
                var name = Idioms.EnumMember(v.Name, e.Name);
                var val = v.IsInt ? v.RawValue : Idioms.EnumMember(v.RawValue, e.Name);
                o.Add($"    {name} = {val},");
            }
            o.Add("}");
            o.Add("");
        }
        return string.Join('\n', o);
    }

    /// <summary>
    /// Emits the structs a header marked <c>[value]</c>: plain data a caller holds and hands
    /// back, as opposed to the handles, parameter bags and vtables that are the ABI's own
    /// plumbing. The alternative in this codebase has been a second hand-written spelling
    /// plus a reinterpret cast between the two, where the only thing asserting the layouts
    /// agree is the sentence next to the cast.
    /// </summary>
    public static string RenderStruct(ApiModel model, ApiStruct s, string ns, Convention convention)
    {
        var needsNumerics = s.Fields.Any(f => ValueFieldType(model, s, f, convention).StartsWith("Vector", StringComparison.Ordinal)
            || ValueFieldType(model, s, f, convention) == "Quaternion");
        var inlineArrays = s.Fields
            .Select(f => (Field: f, Array: ValueArray(model, s, f, convention)))
            .Where(x => x.Array is not null)
            .Select(x => (x.Field, Array: x.Array!.Value))
            .ToList();

        var o = new List<string> { Header };
        if (needsNumerics) o.Add("using System.Numerics;");
        if (inlineArrays.Count > 0) o.Add("using System.Runtime.CompilerServices;");
        o.Add("using System.Runtime.InteropServices;\n");
        o.Add($"namespace {ns};\n");
        o.Add(s.Doc is not null
            ? XmlDoc("", s.Doc).TrimEnd()
            : $"/// <summary>Mirrors <c>{s.Name}</c>.</summary>");
        o.Add("[StructLayout(LayoutKind.Sequential)]");
        o.Add($"public partial struct {Idioms.TypeName(s.Name, convention)}");
        o.Add("{");
        foreach (var (f, array) in inlineArrays)
        {
            o.Add($"    /// <summary>Elements <c>{Idioms.Pascal(f.Name)}</c> has room for, as the ABI"
                + " fixes it. A caller composing the field from a set it does not control checks this"
                + " first -- there is no element past it to write.</summary>");
            o.Add($"    public const int {Idioms.Pascal(f.Name)}Capacity = {array.Arity};");
            o.Add("");
        }
        foreach (var f in s.Fields)
        {
            if (!string.IsNullOrEmpty(f.Doc)) o.Add($"    /// <summary>{Escape(f.Doc)}</summary>");
            o.Add($"    public {ValueFieldType(model, s, f, convention)} {Idioms.Pascal(f.Name)};");
        }
        foreach (var (f, array) in inlineArrays)
        {
            o.Add("");
            o.Add($"    /// <summary>The <c>{f.Type.Trim()}</c> of <c>{Idioms.Pascal(f.Name)}</c> laid"
                + " out inline, so the field occupies the bytes the ABI reads it from.</summary>");
            o.Add($"    [InlineArray({Idioms.Pascal(f.Name)}Capacity)]");
            o.Add($"    public partial struct {array.Buffer}");
            o.Add("    {");
            o.Add($"        public {array.Element} Element;");
            o.Add("    }");
        }
        o.Add("}");
        o.Add("");
        return string.Join('\n', o);
    }

    /// <summary>
    /// The fixed-size array a <c>[value]</c> field describes, or null when it describes a
    /// single element. A managed struct cannot spell <c>T[8]</c> inline for a <c>T</c> that
    /// is itself a struct, so the arity moves into an <c>[InlineArray]</c> wrapper that
    /// occupies the same bytes -- the alternative being a field that silently stands for
    /// one element where the ABI reads several.
    /// </summary>
    static (string Buffer, string Element, int Arity)? ValueArray(ApiModel model, ApiStruct s, ApiField f,
        Convention convention)
    {
        var m = Regex.Match(f.Type.Trim(), @"^(.+?)\s*\[(\d+)\]$");
        if (!m.Success || IsCharArray(f.Type) || VectorArity(f.Type) is not null) return null;

        var element = m.Groups[1].Value.Trim();
        if (CTypes.IsPointer(element))
            throw new InvalidOperationException(
                $"{s.Name}.{f.Name}: [value] describes data a caller holds, and an array of"
                + " pointers makes the lifetime of what they reach someone else's question.");

        return ($"{Idioms.Pascal(f.Name)}Buffer", ValueTypeName(model, element, convention),
            int.Parse(m.Groups[2].Value));
    }

    /// <summary>
    /// A C type named inside a <c>[value]</c> struct or handed out as a sequence of one.
    /// Another <c>[value]</c> struct resolves to its own managed mirror rather than the
    /// native spelling, so the two projections compose instead of a caller holding one
    /// type whose fields are the other.
    /// </summary>
    static string ValueTypeName(ApiModel model, string cType, Convention convention) =>
        model.Structs.Any(v => v.Name == cType.Trim() && v.Has("value") && !v.External)
            ? Idioms.TypeName(cType.Trim(), convention)
            : CsType(model, cType);

    /// <summary>
    /// The type one field of a <c>[value]</c> struct takes. Every answer here has to occupy
    /// the same bytes as the field it stands for, because the struct is handed to native code
    /// as itself rather than marshalled field by field. That rules out the conveniences a
    /// node property affords — a fixed char array reads far better as a string, and is a
    /// different size — so those are refused rather than quietly changing the layout.
    /// </summary>
    static string ValueFieldType(ApiModel model, ApiStruct s, ApiField f, Convention convention)
    {
        if (CTypes.IsPointer(f.Type))
            throw new InvalidOperationException(
                $"{s.Name}.{f.Name}: [value] describes data a caller holds, and a pointer"
                + " field makes the lifetime of that data someone else's question. Describe"
                + " the pointer as a sequence on the slot that hands it out instead.");

        if (IsCharArray(f.Type))
            throw new InvalidOperationException(
                $"{s.Name}.{f.Name}: [value] copies the struct as it stands, and a fixed char"
                + " array has no managed type of the same size -- a string is a reference."
                + " Hand the text out through a slot that can encode it.");

        if (VectorArity(f.Type) is int n) return $"Vector{n}";
        if (NamedVectorTypes.TryGetValue(f.Type.Trim(), out var v)) return v.CsType;
        if (ValueArray(model, s, f, convention) is { } array) return array.Buffer;
        return ValueTypeName(model, f.Type, convention);
    }

    /// <summary>
    /// Emits one borrow wrapper per value of an enum that names where a borrow looks.
    /// The engine asks one question with the region as a parameter, so a projection
    /// that hands borrows to a script body needs one type per region and nothing else
    /// varying between them; writing them out by hand is copying the same struct once
    /// per enum value and letting the copies drift.
    /// </summary>
    public static string RenderBorrowWrappers(ApiEnum kinds, string ns, Convention convention)
    {
        var enumType = Idioms.TypeName(kinds.Name, convention);
        var o = new List<string> { Header, $"namespace {ns};\n" };

        o.Add("/// <summary>");
        o.Add($"/// Marks a borrow wrapper with the <c>{enumType}</c> it resolves with, so a");
        o.Add("/// projection recognises a borrow parameter by what it means rather than by a list");
        o.Add("/// of type names kept in step by hand.");
        o.Add("/// </summary>");
        o.Add("[AttributeUsage(AttributeTargets.Struct)]");
        o.Add("public sealed class NodeBorrowAttribute : Attribute");
        o.Add("{");
        o.Add("    /// <summary>Where this wrapper's borrow looks for the node it names.</summary>");
        o.Add($"    public {enumType} Reach {{ get; }}");
        o.Add("");
        o.Add("    /// <param name=\"reach\">Where this wrapper's borrow looks for the node it names.</param>");
        o.Add($"    public NodeBorrowAttribute({enumType} reach) => Reach = reach;");
        o.Add("}");
        o.Add("");

        foreach (var v in kinds.Values)
        {
            var member = Idioms.EnumMember(v.Name, kinds.Name);
            o.Add("/// <summary>");
            o.Add($"/// {Escape(v.Doc ?? $"A borrow resolved with {member}.")} Obtained as a parameter rather");
            o.Add("/// than stored in a field: re-resolved each time it is handed over, so it can never");
            o.Add("/// dangle, and its type is what puts <typeparamref name=\"T\"/>'s components into the");
            o.Add("/// borrowing body's access list.");
            o.Add("/// </summary>");
            o.Add($"[NodeBorrow({enumType}.{member})]");
            o.Add($"public readonly ref struct {member}<T> where T : class");
            o.Add("{");
            o.Add("    private readonly T? _node;");
            o.Add("");
            o.Add("    /// <summary>The borrowed node, or null when none matched.</summary>");
            o.Add("    public T? Node => _node;");
            o.Add("");
            o.Add("    /// <summary>True when a node matched this borrow.</summary>");
            o.Add("    public bool IsBound => _node is not null;");
            o.Add("");
            o.Add("    /// <param name=\"node\">The node this borrow resolved to, or null when none matched.</param>");
            o.Add($"    public {member}(T? node) => _node = node;");
            o.Add("");
            o.Add("    /// <summary>Unwraps the borrow, throwing when nothing matched.</summary>");
            o.Add("    public T Value => _node ?? throw new InvalidOperationException(");
            o.Add($"        $\"No node of type {{typeof(T).Name}} is bound for this {member.ToLowerInvariant()} borrow.\");");
            o.Add("}");
            o.Add("");
        }
        return string.Join('\n', o);
    }

    /// <summary>
    /// Emits the type-to-id cache for a slot that interns a type under its name and
    /// payload size. The engine identifies the thing by those two values precisely so
    /// that two languages agree on it; what a language then needs is the trip back to
    /// its own type system, and every binding runtime would otherwise write the same
    /// pair of dictionaries by hand.
    /// </summary>
    static void RenderInterning(List<string> o, ApiSlot slot, ApiModel model, Convention convention)
    {
        var name = Idioms.Pascal(slot.Name);
        var nameParam = slot.Params.FirstOrDefault(p => p.Has("type_name"));
        var sizeParam = slot.Params.FirstOrDefault(p => p.Has("type_size"));
        if (nameParam is null || sizeParam is null) return;

        var ids = $"_{Idioms.Ident(slot.Name)}Ids";
        var types = $"_{Idioms.Ident(slot.Name)}Types";

        o.Add($"    private readonly Dictionary<Type, uint> {ids} = new();");
        o.Add($"    private readonly Dictionary<uint, Type> {types} = new();");
        o.Add("");
        o.Add($"    /// <summary>The id <typeparamref name=\"T\"/> interns to, registering it on first use.</summary>");
        o.Add($"    public uint {name}Of<T>() where T : unmanaged");
        o.Add("    {");
        o.Add($"        if ({ids}.TryGetValue(typeof(T), out var cached)) return cached;");
        o.Add("        uint resolved = 0;");
        o.Add($"        {name}(typeof(T).Name, (uint)sizeof(T), &resolved);");
        o.Add($"        {ids}[typeof(T)] = resolved;");
        o.Add($"        {types}[resolved] = typeof(T);");
        o.Add("        return resolved;");
        o.Add("    }");
        o.Add("");
        o.Add("    /// <summary>");
        o.Add($"    /// The type <paramref name=\"id\"/> was interned for, or null when this runtime never");
        o.Add("    /// interned one. Null is a normal answer rather than a failure: an id another");
        o.Add("    /// language registered is real, and simply has no type here to name it.");
        o.Add("    /// </summary>");
        o.Add($"    public Type? {name}TypeOf(uint id) => {types}.TryGetValue(id, out var t) ? t : null;");
        o.Add("");
    }

    public static string RenderProvider(ApiModel model, ApiStruct vtable, ClassifiedModel classified,
        string ns, string nativeNs, IReadOnlyList<string> extraUsings, Convention convention)
    {
        var typeName = Idioms.TypeName(vtable.Name, convention);
        var slots = classified.SlotsByVtable[vtable.Name];
        var plan = classified.Constructors[vtable.Name];

        var o = new List<string>
        {
            Header,
            "using System.Runtime.CompilerServices;",
            "using System.Runtime.InteropServices;",
            "using KernelEngine.Common;",
            "using KernelEngine.Common.Native;",
            $"using {nativeNs};",
        };
        if (HasVectorParams(vtable)) o.Add("using System.Numerics;");
        foreach (var u in extraUsings) o.Add($"using {u};");
        o.Add("");
        o.Add($"namespace {ns};");
        o.Add("");

        var nativeIface = "INative" + Idioms.Pascal(convention.StripPrefix(vtable.Name));
        o.Add($"/// <summary>Exposes the raw native {typeName.ToLowerInvariant()} pointer for cross-domain composition wiring.</summary>");
        o.Add($"public unsafe interface {nativeIface}");
        o.Add("{");
        o.Add($"    {vtable.Name}* Native {{ get; }}");
        o.Add("}");
        o.Add("");

        var domainIface = vtable.Has("interface") ? "I" + typeName : null;
        var decls = domainIface is null ? null : new List<MemberDecl>();

        var closures = VtableClosures(model, slots);
        var closureGroups = VtableClosureGroups(model, slots, typeName);
        foreach (var cb in closures.DistinctBy(c => c.Delegate))
            RenderClosureDelegate(model, o, cb, domainIface ?? typeName);

        o.Add(XmlDoc("", vtable.Doc).TrimEnd());
        o.Add($"public unsafe partial class {typeName} : IDisposable, {nativeIface}"
            + (domainIface is null ? "" : $", {domainIface}"));
        o.Add("{");
        o.Add($"    private {vtable.Name}* _native;");
        o.Add($"    private readonly delegate* unmanaged[Cdecl]<{vtable.Name}*, void> _destroy;");
        o.Add("    private readonly bool _borrowed;");

        var rootedKey = vtable.Slots
            .SelectMany(s => s.Params.Where(p => p.Has("rooted")).Select(p => (Slot: s, Param: p)))
            .Select(x => x.Slot.Params.FirstOrDefault(k => k.Name == x.Param.TagValue("rooted")))
            .FirstOrDefault(k => k is not null);

        if (rootedKey is not null)
        {
            o.Add("");
            o.Add("    /// <summary>");
            o.Add("    /// Keeps alive every managed object handed to the native side as an opaque");
            o.Add("    /// pointer. The engine stores the pointer and never dereferences it, so nothing");
            o.Add("    /// over there stops the collector from moving or reclaiming the object; the");
            o.Add("    /// handle is what makes the pointer mean anything by the time it comes back.");
            o.Add("    /// </summary>");
            o.Add($"    private readonly Dictionary<{CsType(model, rootedKey.Type)}, GCHandle> _rooted = new();");
        }

        foreach (var cg in closureGroups.Where(c => c.Lifetime == ClosureLifetime.Retained))
        {
            o.Add("");
            o.Add("    /// <summary>");
            o.Add(cg.Keyed
                ? "    /// Keeps every registered handler reachable, one per key the slot registers"
                    + " against."
                : cg.Shared
                    ? "    /// Keeps the registered handlers reachable, all of them through the one"
                        + " context they share."
                    : "    /// Keeps the registered handler reachable.");
            o.Add("    /// The engine holds only an opaque pointer to it, which stops nothing on this");
            o.Add("    /// side from collecting or moving the object before the engine calls back into it.");
            o.Add("    /// </summary>");
            o.Add(cg.Keyed
                ? $"    private readonly Dictionary<{cg.KeyType ?? CsType(model, cg.RetainKey!.Type)}, GCHandle>"
                    + $" {cg.Retained} = new();"
                : $"    private GCHandle {cg.Retained};");
        }

        if (closures.Any(c => c.ErrorLane is null))
        {
            o.Add("");
            o.Add("    /// <summary>");
            o.Add("    /// Where a managed exception waits out the native frames. A handler runs");
            o.Add("    /// underneath engine code that has no way to carry an exception, so throwing");
            o.Add("    /// through it would tear down the process; the trampoline parks it here and");
            o.Add("    /// the call rethrows once the native stack has unwound. Per-thread, because");
            o.Add("    /// a handler runs on whichever thread the engine called it from.");
            o.Add("    /// </summary>");
            o.Add("    [ThreadStatic]");
            o.Add("    private static Exception? s_parkedCallbackException;");
        }

        if (closureGroups.Any(c => c.Pairs.Any(c.Queues)))
        {
            o.Add("");
            o.Add("    /// <summary>");
            o.Add("    /// What retained handlers of this provider have thrown and not yet been told");
            o.Add("    /// about. A retained handler outlives the call that registered it, so there is");
            o.Add("    /// no call left to rethrow at; it reports failure through its own channel and");
            o.Add("    /// leaves the exception here for whichever call observes that failure. A handler");
            o.Add("    /// may run on any thread the engine calls it from, and may fail more than once");
            o.Add("    /// before anyone asks, so nothing here is ever discarded unread.");
            o.Add("    /// </summary>");
            o.Add("    private readonly System.Collections.Concurrent.ConcurrentQueue<Exception>"
                + " _callbackFailures = new();");
            o.Add("");
            o.Add("    /// <summary>");
            o.Add("    /// Throws what retained handlers have reported since the last drain, as they");
            o.Add("    /// threw it, or returns when none have. More than one may have failed before");
            o.Add("    /// anyone asked, so they are reported together rather than the last one winning.");
            o.Add("    /// </summary>");
            o.Add("    private void DrainCallbackFailures()");
            o.Add("    {");
            o.Add("        var collected = new List<Exception>();");
            o.Add("        while (_callbackFailures.TryDequeue(out var failure)) collected.Add(failure);");
            o.Add("        if (collected.Count == 0) return;");
            o.Add("        throw new InvalidOperationException(\"A handler registered with this"
                + " provider threw\",");
            o.Add("            collected.Count == 1 ? collected[0] : new AggregateException(collected));");
            o.Add("    }");
        }
        o.Add("");
        o.Add($"    private {vtable.Name}* Handle => _native != null ? _native");
        o.Add($"        : throw new ObjectDisposedException(nameof({typeName}));");
        o.Add("");
        o.Add($"    {vtable.Name}* {nativeIface}.Native => Handle;");
        o.Add("");

        classified.LifecycleInit.TryGetValue(vtable.Name, out var initSlot);
        classified.LifecycleShutdown.TryGetValue(vtable.Name, out var shutdownSlot);
        var initCall = initSlot is not null
            ? $"        {{ ke_error* err2 = null; KernelError.ThrowIfFailed(_native->{initSlot}(_native, &err2), err2, \"{initSlot}\"); }}"
            : null;

        if (plan.Kind == ConstructorKind.FromFactory)
        {
            var factory = plan.Factory!;
            var fparams = factory.Params.Where(p => !convention.IsErrorOutParam(p)).ToList();
            var sig = string.Join(", ", fparams.Select(p => $"{Idioms.CsForeignType(p.Type)} {Idioms.Ident(p.Name!)}"));
            var call = string.Join(", ", fparams.Select(p => Idioms.Ident(p.Name!)));
            o.Add(XmlDoc("    ", factory.Doc, fparams.Select(p => (Idioms.Ident(p.Name!), p.Doc)),
                throwsOnFail: true).TrimEnd());
            o.Add($"    {(plan.NeedsWrapper ? "internal" : "public")} {typeName}({sig})");
            o.Add("    {");
            o.Add("        ke_error* err = null;");
            o.Add($"        var handle = {nativeNs}.NativeMethods.{convention.StripPrefix(factory.Name)}({(call.Length > 0 ? call + ", " : "")}&err);");
            o.Add($"        if (handle.@ref == null) throw KernelError.FromNative(err, \"{factory.Name}\");");
            o.Add("        _native = handle.@ref;");
            o.Add("        _destroy = handle.destroy;");
            if (initCall is not null) o.Add(initCall);
            o.Add("    }");
            o.Add("");
        }
        else if (plan.Kind == ConstructorKind.FromHandle)
        {
            var handleType = plan.HandleTypeName!;
            o.Add($"    /// <summary>Wraps an owner <c>{handleType}</c> and runs {typeName.ToLowerInvariant()}'s startup lifecycle hook.</summary>");
            if (initCall is not null) o.Add("    /// <exception cref=\"KernelError\">The native call failed.</exception>");
            o.Add($"    public {typeName}({handleType} handle)");
            o.Add("    {");
            o.Add("        if (handle.@ref == null) throw new ArgumentNullException(nameof(handle));");
            o.Add("        _native = handle.@ref;");
            o.Add("        _destroy = handle.destroy;");
            if (initCall is not null) o.Add(initCall);
            o.Add("    }");
            o.Add("");
        }

        o.Add($"    /// <summary>Wraps a <c>{vtable.Name}*</c> owned elsewhere. Disposing the result does not destroy it.</summary>");
        o.Add($"    public static {typeName} Borrow({vtable.Name}* native) => new(native, borrowed: true);");
        o.Add("");
        o.Add($"    private {typeName}({vtable.Name}* native, bool borrowed)");
        o.Add("    {");
        o.Add("        _native = native;");
        o.Add("        _destroy = null;");
        o.Add("        _borrowed = borrowed;");
        o.Add("    }");
        o.Add("");

        foreach (var cs in slots)
        {
            if (cs.Slot.Has("sink") || cs.Slot.Has("lifecycle") || cs.Slot.Has("raw_callback")
                || cs.Slot.Has("idiom") || cs.PublicParams.Any(p => p.Has("raw_callback")))
                continue;
            if (cs.PublicParams.Any(p => !p.Has("closure")
                    && classified.Callbacks.Any(c => c.Name == p.Type.Trim())))
            {
                RenderCallbackMethod(o, decls, vtable, cs, classified, typeName, convention);
                continue;
            }
            RenderSlotMethod(model, o, decls, cs, convention, typeName, Drains(model, slots));
        }

        foreach (var slot in vtable.Slots.Where(s => s.Has("interns")))
            RenderInterning(o, slot, model, convention);

        var teardownParks = closureGroups.Any(g => g.Pairs.Any(p => p.Teardown && p.Parks));

        o.Add(teardownParks
            ? $"    /// <summary>Releases the native {typeName.ToLowerInvariant()}, and rethrows"
                + " whatever a teardown handler threw once the native stack has unwound.</summary>"
            : $"    /// <summary>Releases the native {typeName.ToLowerInvariant()}.</summary>");
        o.Add("    public void Dispose()");
        o.Add("    {");
        o.Add("        OnDispose();");
        o.Add("        if (_native == null) return;");
        if (rootedKey is not null)
        {
            o.Add("        foreach (var rooted in _rooted.Values) rooted.Free();");
            o.Add("        _rooted.Clear();");
        }
        var retainedGroups = closureGroups.Where(c => c.Lifetime == ClosureLifetime.Retained).ToList();
        var survivors = retainedGroups.Where(c => c.Pairs.Any(p => p.Teardown)).ToList();

        void FreeRetained(IEnumerable<ClosureGroup> gs, string ind = "        ")
        {
            foreach (var cg in gs)
            {
                if (cg.Keyed)
                {
                    o.Add($"{ind}foreach (var retained in {cg.Retained}.Values) retained.Free();");
                    o.Add($"{ind}{cg.Retained}.Clear();");
                }
                else
                    o.Add($"{ind}if ({cg.Retained}.IsAllocated) {cg.Retained}.Free();");
            }
        }

        FreeRetained(retainedGroups.Except(survivors));
        if (survivors.Count > 0)
        {
            o.Add("        if (_borrowed)");
            o.Add("        {");
            FreeRetained(survivors, "            ");
            o.Add("            _native = null;");
            o.Add("            return;");
            o.Add("        }");
        }
        else
            o.Add("        if (_borrowed) { _native = null; return; }");
        if (shutdownSlot is not null)
            o.Add($"        _native->{shutdownSlot}(_native, null);");
        if (teardownParks) o.Add("        s_parkedCallbackException = null;");
        o.Add("        _destroy(_native);");
        o.Add("        _native = null;");
        FreeRetained(survivors);
        if (teardownParks)
        {
            o.Add("        if (s_parkedCallbackException is { } parked)");
            o.Add("        {");
            o.Add("            s_parkedCallbackException = null;");
            o.Add("            throw parked;");
            o.Add("        }");
        }
        o.Add("    }");
        o.Add("");
        o.Add("    partial void OnDispose();");
        o.Add("}");
        o.Add("");

        if (domainIface is not null)
        {
            o.Add($"/// <summary>The {typeName.ToLowerInvariant()} contract game code depends on, so a caller"
                + $" names a capability rather than the <see cref=\"{typeName}\"/> that carries it.</summary>");
            o.Add($"public unsafe interface {domainIface} : IDisposable");
            o.Add("{");
            foreach (var m in decls!)
            {
                if (m.Doc.Length > 0) o.Add(m.Doc);
                o.Add($"    {m.InterfaceLine}");
            }
            o.Add("}");
            o.Add("");
        }

        return string.Join('\n', o);
    }

    /// <summary>
    /// The lane each parameter occupies in a vector a run of consecutive parameters
    /// spells out. A C ABI has no vector type, so a position arrives as two floats and
    /// every language that does have one re-groups them; doing that by hand is an
    /// overload per slot whose only content is which argument goes where.
    /// </summary>
    static Dictionary<ApiParam, (string Vector, string Lane, int Arity, bool Leads)> VectorLanes(IReadOnlyList<ApiParam> ps)
    {
        var map = new Dictionary<ApiParam, (string, string, int, bool)>();
        for (var i = 0; i < ps.Count; i++)
        {
            var arity = ps[i].Has("vector2") ? 2 : ps[i].Has("vector3") ? 3 : 0;
            if (arity == 0) continue;
            var vector = ps[i].TagValue($"vector{arity}")
                ?? throw new InvalidOperationException(
                    $"{ps[i].Name}: [vector{arity}] must name the vector, as [vector{arity}:<name>]");
            if (i + arity > ps.Count)
                throw new InvalidOperationException(
                    $"{ps[i].Name}: [vector{arity}:{vector}] needs {arity} consecutive parameters, "
                    + $"but only {ps.Count - i} follow");
            for (var lane = 0; lane < arity; lane++)
                map[ps[i + lane]] = (vector, "XYZ"[lane].ToString(), arity, lane == 0);
            i += arity - 1;
        }
        return map;
    }

    /// <summary>Whether any slot on the vtable groups parameters into a vector.</summary>
    static bool HasVectorParams(ApiStruct vtable) =>
        vtable.Slots.Any(s => s.Params.Any(p => p.Has("vector2") || p.Has("vector3")));

    /// <summary>
    /// How long the managed handler must stay reachable after the call that registered it.
    /// <see cref="Scoped"/> dies with the call; <see cref="Retained"/> lives until the
    /// object is disposed or another handler replaces it. A retained closure the slot
    /// registers against a key keeps one handler per key value rather than one in total.
    /// </summary>
    internal enum ClosureLifetime { Scoped, Retained }

    /// <summary>
    /// A function-pointer parameter and the opaque context parameter that travels with
    /// it, projected as one delegate. The pair is how a C ABI carries a closure: the
    /// context is the closure's captured state and the function pointer is its body.
    /// Every lane of the function-pointer type except the context and the outbound error
    /// channel becomes a parameter of the delegate.
    /// </summary>
    internal sealed record CallbackPair(ApiParam Fn, ApiParam Ctx, ClosureLifetime Lifetime,
        string Delegate, string Trampoline, ApiCallback Callback,
        int CtxLane, int? ErrorLane, ApiParam? RetainKey, bool RetainByReturn, bool Teardown)
    {
        /// <summary>
        /// Whether a throwing handler has to wait out the native frames in the parking
        /// field instead of reporting through a lane of its own.
        /// </summary>
        public bool Parks => ErrorLane is null;
    }

    /// <summary>
    /// The name a callback typedef projects to. The typedef is where the ABI already
    /// named the concept, so two slots taking the same one share a delegate instead of
    /// each inventing a name from the slot it appears in.
    /// </summary>
    static string DelegateName(ApiCallback callback)
    {
        var n = callback.Name;
        if (n.StartsWith("ke_", StringComparison.Ordinal)) n = n[3..];
        if (n.EndsWith("_func", StringComparison.Ordinal)) n = n[..^5];
        else if (n.EndsWith("_fn", StringComparison.Ordinal)) n = n[..^3];
        return Idioms.Pascal(n);
    }

    /// <summary>
    /// What <c>[retained:&lt;key&gt;]</c> writes when the value telling one registration from
    /// another is the slot's return rather than anything the caller passed in.
    /// </summary>
    const string ReturnKey = "return";

    /// <summary>Whether a C type spells a boolean.</summary>
    static bool IsBoolType(string type) => type.Trim() is "_Bool" or "bool" or "ke_bool";

    /// <summary>
    /// How a lane is spelled where the unmanaged entry point declares it: pointer depth
    /// preserved and typedefs resolved to what they alias, so the pointer matches the
    /// function-pointer type the vtable slot declares, depth for depth.
    /// </summary>
    static string BlittableLane(ApiModel model, string type)
    {
        var t = type.Trim().Replace("const ", "").Replace("struct ", "").Trim();
        var stars = t.Count(c => c == '*');
        var basis = model.ResolveAlias(t.TrimEnd('*', ' '));
        if (stars == 0 && IsBoolType(basis)) return "bool";
        return Idioms.CsForeignType(basis) + new string('*', stars);
    }

    /// <summary>How a lane is spelled in the delegate the caller implements.</summary>
    static string ManagedLane(ApiModel model, ApiParam lane, string selfType) =>
        lane.Has("self") ? selfType
        : lane.Has("ctx") ? "nint"
        : lane.Has("utf8") ? "string"
        : IsBoolType(lane.Type) ? "bool"
        : CsType(model, lane.Type);

    /// <summary>
    /// What a handler returns on the managed side. A callback reporting failure through
    /// an error channel says it in managed code by throwing, so the boolean it returns
    /// natively carries nothing a caller could still answer: the trampoline reports
    /// success for a handler that returned at all, and failure for one that threw.
    /// </summary>
    static string ManagedReturn(ApiModel model, ApiCallback callback, int? errorLane) =>
        errorLane is not null && IsBoolType(callback.Returns)
            ? "void"
            : ManagedLane(model, new ApiParam(null, callback.Returns, [], null), "");

    static IReadOnlyList<CallbackPair> CallbackPairs(ApiModel model, ClassifiedSlot cs)
    {
        var slot = cs.Slot;
        var scope = cs.PublicParams;
        var pairs = new List<CallbackPair>();
        foreach (var fn in scope.Where(p => p.Has("closure")))
        {
            var ctxName = fn.TagValue("closure")
                ?? throw new InvalidOperationException(
                    $"{slot.Name}.{fn.Name}: [closure] must name the context parameter, as [closure:<name>]");
            var ctx = scope.FirstOrDefault(p => p.Name == ctxName)
                ?? throw new InvalidOperationException(
                    $"{slot.Name}.{fn.Name}: [closure:{ctxName}] names no parameter of this slot");

            var callback = model.CallbackOf(fn.Type)
                ?? throw new InvalidOperationException(
                    $"{slot.Name}.{fn.Name}: [closure] needs a function-pointer typedef, but {fn.Type.Trim()} is not one");

            var ctxLane = callback.Lanes.Select((l, i) => (l, i))
                .Where(x => x.l.Has("context"))
                .Select(x => (int?)x.i).FirstOrDefault()
                ?? throw new InvalidOperationException(
                    $"{slot.Name}.{fn.Name}: [closure:{ctxName}] hands the context to {callback.Name}, "
                    + "which declares no lane to receive it — a lane's type says nothing about which one "
                    + "carries the context, so the typedef has to mark it [context]");
            if (callback.Lanes[ctxLane].Type.Replace(" ", "") != "void*")
                throw new InvalidOperationException(
                    $"{slot.Name}.{fn.Name}: {callback.Name}'s [context] lane is "
                    + $"{callback.Lanes[ctxLane].Type.Trim()}, and a context travels as void*");

            int? errorLane = callback.Lanes.Select((l, i) => (l, i))
                .Where(x => x.l.Type.Replace(" ", "") == "ke_error**")
                .Select(x => (int?)x.i).FirstOrDefault();

            var lifetime = fn.Has("retained") ? ClosureLifetime.Retained : ClosureLifetime.Scoped;
            ApiParam? retainKey = null;
            var retainByReturn = false;
            if (fn.TagValue("retained") is { } keyName)
            {
                if (keyName == ReturnKey)
                {
                    if (slot.Returns.Trim() is "void")
                        throw new InvalidOperationException(
                            $"{slot.Name}.{fn.Name}: [retained:{ReturnKey}] keys the registration on what the "
                            + "slot returns, and this one returns nothing");
                    retainByReturn = true;
                }
                else
                    retainKey = scope.FirstOrDefault(p => p.Name == keyName)
                        ?? throw new InvalidOperationException(
                            $"{slot.Name}.{fn.Name}: [retained:{keyName}] names no parameter of this slot");
            }
            var teardown = fn.Has("teardown");
            if (teardown && lifetime != ClosureLifetime.Retained)
                throw new InvalidOperationException(
                    $"{slot.Name}.{fn.Name}: [teardown] says the engine calls this handler while the "
                    + "provider is being destroyed, which only a [retained] closure survives to see");
            if (lifetime == ClosureLifetime.Retained && errorLane is null && !teardown)
                throw new InvalidOperationException(
                    $"{slot.Name}.{fn.Name}: a retained closure outlives the call that registered it, so a "
                    + $"handler that throws has nowhere to report; {callback.Name} needs a ke_error** lane, "
                    + "or [teardown] if the engine only calls it from the destroy this object drives");
            if (errorLane is not null && !IsBoolType(callback.Returns))
                throw new InvalidOperationException(
                    $"{slot.Name}.{fn.Name}: {callback.Name} has a ke_error** lane but returns "
                    + $"{callback.Returns}, so the caller cannot tell that it failed");

            pairs.Add(new CallbackPair(fn, ctx, lifetime, DelegateName(callback),
                TrampolineName(slot, fn),
                callback, ctxLane, errorLane, retainKey, retainByReturn, teardown));
        }
        return pairs;
    }

    /// <summary>
    /// Names the unmanaged entry point for one closure. Both the slot and the parameter
    /// identify it, because a slot may take more than one — but a slot whose name already
    /// ends in the parameter's would only stutter it back.
    /// </summary>
    static string TrampolineName(ApiSlot slot, ApiParam fn) =>
        slot.Name.EndsWith("_" + fn.Name, StringComparison.Ordinal) || slot.Name == fn.Name
            ? $"{Idioms.Pascal(slot.Name)}Trampoline"
            : $"{Idioms.Pascal(slot.Name)}{Idioms.Pascal(fn.Name!)}Trampoline";

    /// <summary>The field that keeps a retained closure reachable for as long as the engine holds it.</summary>
    /// <summary>
    /// Every closure reached through one context parameter. A context is a single
    /// pointer, so the closures sharing it have to share the one object it points at:
    /// allocating a handle per closure would hand each trampoline whichever handle the
    /// call happened to write last. A group of one needs no such object and keeps the
    /// delegate as the handle's target directly.
    /// </summary>
    internal sealed record ClosureGroup(ApiParam Ctx, IReadOnlyList<CallbackPair> Pairs, string StateType,
        string ReturnType, string Owner, bool OwnerDrains)
    {
        public bool Shared => Pairs.Count > 1;

        /// <summary>
        /// Whether the trampoline has to reach the provider that registered the closure.
        /// A retained handler reporting through a lane of its own outlives the call that
        /// registered it, so the exception it threw has nowhere to be rethrown at that
        /// call; it is queued on the provider instead, and the slot that observes the
        /// failure raises it. Reaching the provider means the context must point at an
        /// object holding it rather than at the bare delegate.
        /// </summary>
        public bool NeedsOwner => HandsBackProvider || Pairs.Any(Queues);

        /// <summary>
        /// Whether this handler's exception is the kind that has to wait on the provider:
        /// one that outlives the call registering it, reports failure through a channel of
        /// its own, and has a slot declared to answer for it. A handler running inside the
        /// registering call is rethrown there instead, and needs no queue.
        /// </summary>
        public bool Queues(CallbackPair pair) => OwnerDrains
            && pair.Lifetime == ClosureLifetime.Retained && pair.ErrorLane is not null;

        /// <summary>
        /// Whether a handler of this group is called with the provider that registered it.
        /// The ABI spells that lane as a pointer to the same object the call was made on,
        /// which managed code already holds a wrapper for; handing the wrapper back is the
        /// only projection that keeps the handler on the managed surface.
        /// </summary>
        public bool HandsBackProvider => Pairs.Any(p => p.Callback.Lanes.Any(l => l.Has("self")));

        /// <summary>Whether the context points at a generated state object rather than the delegate itself.</summary>
        public bool UsesState => Shared || NeedsOwner;

        string Basis => (Shared ? Ctx.Name : Pairs[0].Fn.Name)!;

        /// <summary>The local holding the one GC root this group's context points at.</summary>
        public string Handle => $"{Idioms.Ident(Basis)}Handle";

        /// <summary>The field keeping that root reachable for as long as the engine may call back.</summary>
        public string Retained => $"_retained{Idioms.Pascal(Basis)}";

        /// <summary>
        /// How long the shared object has to stay reachable: as long as its longest-lived
        /// member, since freeing it at the first member's end would leave the others
        /// pointing at collected memory.
        /// </summary>
        public ClosureLifetime Lifetime => Pairs.Any(p => p.Lifetime == ClosureLifetime.Retained)
            ? ClosureLifetime.Retained
            : ClosureLifetime.Scoped;

        /// <summary>
        /// The parameter whose value tells one registration's root from another's, when the
        /// slot registers against a key it was handed rather than replacing a single handler.
        /// </summary>
        public ApiParam? RetainKey => Pairs.Select(p => p.RetainKey).FirstOrDefault(k => k is not null);

        /// <summary>
        /// Whether the identity distinguishing one registration from another is what the
        /// slot returns, the case when nothing the caller passed names the registration.
        /// </summary>
        public bool RetainByReturn => Pairs.Any(p => p.RetainByReturn);

        /// <summary>Whether this group keeps a root per registration rather than one in total.</summary>
        public bool Keyed => RetainKey is not null || RetainByReturn;

        /// <summary>How the dictionary of roots is keyed, when the group keeps one per registration.</summary>
        public string? KeyType => RetainByReturn ? ReturnType : null;

        /// <summary>How the state object names the slot holding one of the grouped delegates.</summary>
        public static string Field(CallbackPair pair) => Idioms.Pascal(pair.Fn.Name!);
    }

    static IReadOnlyList<ClosureGroup> ClosureGroups(ApiModel model, ApiSlot slot, IReadOnlyList<CallbackPair> pairs,
        string owner, bool ownerDrains)
    {
        var groups = pairs
            .GroupBy(p => p.Ctx)
            .Select(g => new ClosureGroup(g.Key, g.ToList(), $"{Idioms.Pascal(slot.Name)}Closures",
                CsType(model, slot.Returns), owner, ownerDrains))
            .ToList();

        foreach (var g in groups.Where(x => x.Shared))
        {
            if (g.Pairs.Any(p => p.RetainKey is not null))
                throw new InvalidOperationException(
                    $"{slot.Name}: a closure sharing the context '{g.Ctx.Name}' is keyed by [retained:<key>], "
                    + "which needs a root per key while the context has exactly one");
        }
        return groups;
    }

    static IReadOnlyList<ClosureGroup> VtableClosureGroups(ApiModel model, IEnumerable<ClassifiedSlot> slots,
        string owner)
    {
        var drains = Drains(model, slots);
        return slots
            .SelectMany(s => ClosureGroups(model, s.Slot, CallbackPairs(model, s), owner, drains))
            .ToList();
    }

    /// <summary>
    /// Whether any slot of the vtable is declared as the one that answers for a retained
    /// handler's failure. Without one there is no call to raise the exception at, so the
    /// provider keeps no queue and the handler's own error channel stays its only report.
    /// </summary>
    static bool Drains(ApiModel model, IEnumerable<ClassifiedSlot> slots)
    {
        var all = slots.ToList();
        return all.Any(s => s.Slot.Has("drains"))
            && all.SelectMany(s => CallbackPairs(model, s))
                .Any(p => p.Lifetime == ClosureLifetime.Retained && p.ErrorLane is not null);
    }

    /// <summary>Every closure a vtable projects, across all its slots.</summary>
    static IReadOnlyList<CallbackPair> VtableClosures(ApiModel model, IEnumerable<ClassifiedSlot> slots) =>
        slots.SelectMany(s => CallbackPairs(model, s)).ToList();

    /// <summary>Lanes the delegate carries: everything but the context and the error channel.</summary>
    static IEnumerable<int> CarriedLanes(CallbackPair pair) =>
        Enumerable.Range(0, pair.Callback.Lanes.Count)
            .Where(i => i != pair.CtxLane && i != pair.ErrorLane);

    /// <summary>
    /// How the callback's function pointer is spelled where the vtable slot expects it.
    /// A <see langword="null"/> handler has to pass a null pointer, and a conditional
    /// has no common type between a null literal and a function pointer, so the typed
    /// branch has to say what it is.
    /// </summary>
    static string NativeFnPtr(ApiModel model, CallbackPair pair) =>
        $"delegate* unmanaged[Cdecl]<{string.Join(", ", pair.Callback.Lanes.Select(l => BlittableLane(model, l.Type)))}"
        + $", {BlittableLane(model, pair.Callback.Returns)}>";

    /// <summary>
    /// The delegate a projected closure asks the caller for. Declared beside the class
    /// rather than as an <c>Action</c>, because a lane can be a pointer and a generic
    /// type argument cannot.
    /// </summary>
    static void RenderClosureDelegate(ApiModel model, List<string> o, CallbackPair pair, string selfType)
    {
        var ps = CarriedLanes(pair).Select(i => pair.Callback.Lanes[i])
            .Select((l, n) => $"{ManagedLane(model, l, selfType)} {Idioms.Ident(l.Name ?? $"arg{n}")}");
        var doc = pair.Callback.Lanes
            .Where(l => l.Name is not null && l.Doc is not null)
            .Where(l => CarriedLanes(pair).Any(i => pair.Callback.Lanes[i] == l))
            .Select(l => (Idioms.Ident(l.Name!), l.Doc));
        o.Add(XmlDoc("", pair.Callback.Doc ?? pair.Fn.Doc, doc).TrimEnd());
        o.Add($"public unsafe delegate {ManagedReturn(model, pair.Callback, pair.ErrorLane)} "
            + $"{pair.Delegate}({string.Join(", ", ps)});");
        o.Add("");
    }

    /// <summary>
    /// The trampoline a <see cref="CallbackPair"/> needs: the unmanaged entry point the
    /// engine calls, which unwraps the handle back into the delegate. A managed exception
    /// cannot cross the native frame. Where the callback declares an error channel it is
    /// translated into one and reported as a failure; where it does not, it is parked and
    /// rethrown by the call site once the native stack has unwound, which only holds
    /// because a closure without a channel is never allowed to outlive its call.
    /// </summary>
    /// <summary>
    /// The object a shared context points at: one field per closure reached through it,
    /// so a single GC root answers for all of them.
    /// </summary>
    static void RenderClosureState(List<string> o, ClosureGroup group)
    {
        o.Add(group.Shared
            ? "    /// <summary>The handlers reached through one shared context pointer.</summary>"
            : "    /// <summary>The handler, and the provider a failure of it is reported to.</summary>");
        o.Add($"    private sealed class {group.StateType}");
        o.Add("    {");
        if (group.NeedsOwner) o.Add($"        public required {group.Owner} Owner;");
        foreach (var p in group.Pairs)
            o.Add($"        public {p.Delegate}? {ClosureGroup.Field(p)};");
        o.Add("    }");
        o.Add("");
    }

    static void RenderTrampoline(ApiModel model, List<string> o, CallbackPair pair, ClosureGroup group)
    {
        var lanes = pair.Callback.Lanes;
        var ps = lanes.Select((l, i) => i == pair.CtxLane
            ? "void* ctx"
            : $"{BlittableLane(model, l.Type)} arg{i}");
        var args = string.Join(", ", CarriedLanes(pair).Select(i => lanes[i].Has("self")
            ? "state.Owner"
            : lanes[i].Has("utf8")
            ? $"Marshal.PtrToStringUTF8((nint)arg{i}) ?? \"\""
            : ManagedLane(model, lanes[i], group.Owner) != BlittableLane(model, lanes[i].Type)
                ? $"({ManagedLane(model, lanes[i], group.Owner)})arg{i}"
            : $"arg{i}"));
        var returns = IsBoolType(pair.Callback.Returns);
        var handlerAnswers = ManagedReturn(model, pair.Callback, pair.ErrorLane) != "void";
        var nativeReturn = BlittableLane(model, pair.Callback.Returns);

        o.Add("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]");
        o.Add($"    private static {nativeReturn} {pair.Trampoline}({string.Join(", ", ps)})");
        o.Add("    {");
        o.Add("        try");
        o.Add("        {");
        o.Add(group.UsesState
            ? $"            if (GCHandle.FromIntPtr((nint)ctx).Target is {group.StateType} state"
                + $" && state.{ClosureGroup.Field(pair)} is {{ }} handler)"
            : $"            if (GCHandle.FromIntPtr((nint)ctx).Target is {pair.Delegate} handler)");
        if (returns && !handlerAnswers)
        {
            o.Add("            {");
            o.Add($"                handler({args});");
            o.Add("                return true;");
            o.Add("            }");
        }
        else
            o.Add($"                {(returns ? $"return handler({args});" : $"handler({args});")}");
        if (returns) o.Add("            return false;");
        o.Add("        }");
        o.Add("        catch (Exception ex)");
        o.Add("        {");
        if (pair.ErrorLane is { } errLane)
        {
            if (group.Queues(pair))
            {
                o.Add("            if (GCHandle.FromIntPtr((nint)ctx).Target is"
                    + $" {group.StateType} failed)");
                o.Add("                failed.Owner._callbackFailures.Enqueue(ex);");
            }
            o.Add($"            KernelError.ToNative(arg{errLane}, ex, \"{pair.Callback.Name}\");");
            if (returns) o.Add("            return false;");
        }
        else
        {
            o.Add("            s_parkedCallbackException ??= ex;");
            if (returns) o.Add("            return false;");
        }
        o.Add("        }");
        o.Add("    }");
        o.Add("");
    }

    /// <summary>
    /// One public member as the provider class declares it: the documentation block and the
    /// signature, with no <c>public</c> keyword and no body. The domain interface is rendered
    /// from these, so a signature the class emits and the signature the interface promises are
    /// the same string rather than two renderings of the same intent.
    /// </summary>
    sealed record MemberDecl(string Doc, string Decl, bool Property)
    {
        /// <summary>How the interface spells this member: a method ends the declaration, a property opens a getter.</summary>
        public string InterfaceLine => Property ? $"{Decl} {{ get; }}" : $"{Decl};";
    }

    static void Declare(List<string> o, List<MemberDecl>? decls, string doc, string decl, bool property = false)
    {
        o.Add(doc);
        o.Add($"    public {decl}");
        decls?.Add(new MemberDecl(doc, decl, property));
    }

    static void RenderSlotMethod(ApiModel model, List<string> o, List<MemberDecl>? decls,
        ClassifiedSlot cs, Convention convention, string owner, bool ownerDrains)
    {
        var slot = cs.Slot;
        var name = (slot.TagValue("name") ?? Idioms.Pascal(slot.Name))
            + (cs.Sequences.Count > 0 ? "Raw" : "");
        var lanes = VectorLanes(slot.Params);
        var callbacks = CallbackPairs(model, cs);
        var groups = ClosureGroups(model, slot, callbacks, owner, ownerDrains);

        if (callbacks.Count > 0 && cs.Shape is not SlotShape.Fallible)
            throw new InvalidOperationException(
                $"{slot.Name}: [closure] is only projected on a fallible slot so far, not {cs.Shape}");

        if (slot.Has("property"))
        {
            if (cs.PublicParams.Count > 0 || cs.Shape is not SlotShape.Plain)
                throw new InvalidOperationException(
                    $"{slot.Name}: [property] needs a slot that only answers -- no parameters and no"
                    + $" failure channel, so there is nothing for a getter to drop. Got {cs.Shape}"
                    + $" with {cs.PublicParams.Count} parameter(s).");

            var pType = slot.Returns == "ke_bool" ? "bool" : CsType(model, slot.Returns);
            Declare(o, decls, XmlDoc("    ", slot.Doc ?? slot.ReturnDoc).TrimEnd(),
                $"{pType} {name}", property: true);
            o.Add("    {");
            o.Add($"        get => Handle->{slot.Name}(Handle)"
                + (slot.Returns == "ke_bool" ? " != 0" : "") + ";");
            o.Add("    }");
            o.Add("");
            return;
        }

        string Sig(IEnumerable<ApiParam> ps) => string.Join(", ", SigParts(ps));

        IEnumerable<ApiParam> NativeParams() => cs.Slot.Params
            .Where(p => !cs.Fallible || p != cs.Slot.Params[^1]);

        IEnumerable<(string, string?)> DocParams(IEnumerable<ApiParam> ps) => ps
            .Where(p => callbacks.All(c => c.Ctx != p))
            .Select(p => (Idioms.Ident(p.Name!), p.Doc));

        IEnumerable<string> SigParts(IEnumerable<ApiParam> ps) => ps
            .Where(p => !lanes.TryGetValue(p, out var l) || l.Leads)
            .Where(p => callbacks.All(c => c.Ctx != p))
            .Select(p => lanes.TryGetValue(p, out var l)
                ? $"Vector{l.Arity} {Idioms.Ident(l.Vector)}"
                : callbacks.FirstOrDefault(c => c.Fn == p) is { } cb
                    ? $"{cb.Delegate}? {Idioms.Ident(p.Name!)}"
                : cs.Sequences.FirstOrDefault(s => s.Seq == p) is { } asSpan
                    ? $"Span<{SequenceElement(model, asSpan, convention)}> {Idioms.Ident(p.Name!)}"
                    : $"{CsParamType(model, p, convention)} {Idioms.Ident(p.Name!)}");

        switch (cs.Shape)
        {
            case SlotShape.ReturnsOutParam:
            {
                var ret = CsType(model, CTypes.Deref(cs.OutParam!.Type));
                var ins = cs.PublicParams.Where(p => p != cs.OutParam).ToList();
                var sig = Sig(ins);
                var nativeArgs = string.Concat(NativeParams().Select(p =>
                    ", " + (p == cs.OutParam ? "&result" : CallArg(p))));

                Declare(o, decls, XmlDoc("    ", slot.Doc, ins.Select(p => (Idioms.Ident(p.Name!), p.Doc)),
                    slot.ReturnDoc, cs.Fallible).TrimEnd(), $"{ret} {name}({sig})");
                o.Add("    {");
                var (roPro, roDepth) = Utf8Prologue(ins, new string(' ', 8));
                var (roSeq, roSeqDepth) = SequencePrologue(model, cs.Sequences,
                    new string(' ', 8 + roDepth * 4), convention);
                o.AddRange(roPro);
                o.AddRange(roSeq);
                roDepth += roSeqDepth;
                var roInd = new string(' ', 8 + roDepth * 4);
                o.Add($"{roInd}{ret} result;");
                if (cs.Fallible)
                {
                    o.Add($"{roInd}ke_error* err = null;");
                    o.Add($"{roInd}KernelError.ThrowIfFailed(Handle->{slot.Name}(Handle{nativeArgs}, &err), err, \"{slot.Name}\");");
                }
                else
                {
                    o.Add($"{roInd}Handle->{slot.Name}(Handle{nativeArgs});");
                }
                o.Add($"{roInd}return result;");
                for (var d = roDepth; d > 0; d--) o.Add(new string(' ', 4 + d * 4) + "}");
                o.Add("    }");
                o.Add("");
                return;
            }
            case SlotShape.TupleOutParams:
            {
                var ins = cs.PublicParams.Where(p => !cs.OutParams.Contains(p)).ToList();
                var sig = Sig(ins);
                var names = cs.OutParams.Select(p => Idioms.Pascal(p.Name!)).ToList();
                var types = cs.OutParams.Select(p => CsType(model, CTypes.Deref(p.Type))).ToList();
                var retTuple = string.Join(", ", types.Zip(names, (t, n) => $"{t} {n}"));
                var locals = cs.OutParams.Select(p => Idioms.Ident(p.Name!)).ToList();
                var nativeArgs = NativeParams()
                    .Select(p => cs.OutParams.Contains(p) ? $"&{Idioms.Ident(p.Name!)}" : CallArg(p));
                var callArgs = string.Concat(nativeArgs.Select(a => ", " + a));

                Declare(o, decls, XmlDoc("    ", slot.Doc, ins.Select(p => (Idioms.Ident(p.Name!), p.Doc)),
                    throwsOnFail: cs.Fallible).TrimEnd(), $"({retTuple}) {name}({sig})");
                o.Add("    {");
                var (tuPro, tuDepth) = Utf8Prologue(ins, new string(' ', 8));
                var (tuSeq, tuSeqDepth) = SequencePrologue(model, cs.Sequences,
                    new string(' ', 8 + tuDepth * 4), convention);
                o.AddRange(tuPro);
                o.AddRange(tuSeq);
                tuDepth += tuSeqDepth;
                var tuInd = new string(' ', 8 + tuDepth * 4);
                foreach (var (t, n) in types.Zip(locals)) o.Add($"{tuInd}{t} {n};");
                if (cs.Fallible)
                {
                    o.Add($"{tuInd}ke_error* err = null;");
                    o.Add($"{tuInd}KernelError.ThrowIfFailed(Handle->{slot.Name}(Handle{callArgs}, &err), err, \"{slot.Name}\");");
                }
                else
                {
                    o.Add($"{tuInd}Handle->{slot.Name}(Handle{callArgs});");
                }
                o.Add($"{tuInd}return ({string.Join(", ", locals)});");
                for (var d = tuDepth; d > 0; d--) o.Add(new string(' ', 4 + d * 4) + "}");
                o.Add("    }");
                o.Add("");
                return;
            }
            case SlotShape.Try:
            {
                var ins = cs.PublicParams.Where(p => !p.Has("out")).ToList();
                var outs = cs.OutParams;
                var sigParts = SigParts(ins)
                    .Concat(outs.Select(p => $"out {CsType(model, CTypes.Deref(p.Type))} {Idioms.Ident(p.Name!)}"));

                var tryName = name.StartsWith("Try") ? name : $"Try{name}";
                Declare(o, decls, XmlDoc("    ", slot.Doc,
                    cs.PublicParams.Select(p => (Idioms.Ident(p.Name!), p.Doc)), slot.ReturnDoc).TrimEnd(),
                    $"bool {tryName}({string.Join(", ", sigParts)})");
                o.Add("    {");
                foreach (var op in outs) o.Add($"        {CsType(model, CTypes.Deref(op.Type))} {Idioms.Ident(op.Name!)}Local;");
                var (tPro, tDepth) = Utf8Prologue(ins, new string(' ', 8));
                var (tSeq, tSeqDepth) = SequencePrologue(model, cs.Sequences,
                    new string(' ', 8 + tDepth * 4), convention);
                o.AddRange(tPro);
                o.AddRange(tSeq);
                tDepth += tSeqDepth;
                var tInd = new string(' ', 8 + tDepth * 4);
                var tryArgs = NativeParams()
                    .Select(p => outs.Contains(p) ? $"&{Idioms.Ident(p.Name!)}Local" : CallArg(p));
                var tryCall = $"Handle->{slot.Name}(Handle, {string.Join(", ", tryArgs)}"
                    + (cs.Fallible ? ", null)" : ")")
                    + (slot.Returns == "ke_bool" ? " != 0" : "");
                o.Add($"{tInd}var found = {tryCall};");
                foreach (var op in outs) o.Add($"{tInd}{Idioms.Ident(op.Name!)} = {Idioms.Ident(op.Name!)}Local;");
                o.Add($"{tInd}return found;");
                for (var d = tDepth; d > 0; d--) o.Add(new string(' ', 4 + d * 4) + "}");
                o.Add("    }");
                o.Add("");
                return;
            }
            case SlotShape.Fallible:
            {
                var args = cs.PublicParams;
                var byReturn = convention.SignalsFailureByReturn(slot.Returns);
                var retType = byReturn ? "void" : CsType(model, slot.Returns);
                var sig = Sig(args);
                var bagLocal = cs.ExpandedParam is null ? null : Idioms.Ident(cs.ExpandedParam.Name!);
                var call = string.Concat(NativeParams()
                    .Select(p => ", " + (p == cs.ExpandedParam ? $"&{bagLocal}" : CallArg(p))));
                Declare(o, decls, XmlDoc("    ", slot.Doc, DocParams(args),
                    byReturn ? null : slot.ReturnDoc, throwsOnFail: true).TrimEnd(),
                    $"{retType} {name}({sig})");
                o.Add("    {");
                var (fPro, fDepth) = Utf8Prologue(args, new string(' ', 8));
                var (fSeq, fSeqDepth) = SequencePrologue(model, cs.Sequences,
                    new string(' ', 8 + fDepth * 4), convention);
                o.AddRange(fPro);
                o.AddRange(fSeq);
                fDepth += fSeqDepth;
                var fInd = new string(' ', 8 + fDepth * 4);
                var rooted = args.Where(p => p.Has("rooted")).ToList();
                foreach (var rp in rooted)
                    o.Add($"{fInd}var {Idioms.Ident(rp.Name!)}Handle = System.Runtime.InteropServices.GCHandle.Alloc({Idioms.Ident(rp.Name!)});");

                void BuildBag()
                {
                    if (bagLocal is null) return;
                    o.Add($"{fInd}{cs.ExpandedStruct!.Name} {bagLocal} = default;");
                    foreach (var f in cs.ExpandedStruct.Fields)
                    {
                        var arg = args.FirstOrDefault(a => a.Name == f.Name)
                            ?? cs.Sequences.Select(s => s.Count).First(c => c.Name == f.Name);
                        o.Add($"{fInd}{bagLocal}.{f.Name} = {CallArg(arg)};");
                    }
                }

                if (callbacks.Count > 0)
                {
                    var scoped = groups.Where(g => g.Lifetime == ClosureLifetime.Scoped).ToList();
                    var parks = callbacks.Any(c => c.Parks && !c.Teardown);
                    foreach (var g in groups)
                    {
                        if (!g.UsesState)
                        {
                            var fn = Idioms.Ident(g.Pairs[0].Fn.Name!);
                            o.Add($"{fInd}var {g.Handle} = {fn} is null ? default : GCHandle.Alloc({fn});");
                            continue;
                        }
                        var inits = string.Join(", ", g.Pairs
                            .Select(p => $"{ClosureGroup.Field(p)} = {Idioms.Ident(p.Fn.Name!)}")
                            .Prepend(g.NeedsOwner ? "Owner = this" : null)
                            .Where(x => x is not null));
                        var allNull = string.Join(" && ", g.Pairs.Select(p =>
                            $"{Idioms.Ident(p.Fn.Name!)} is null"));
                        o.Add($"{fInd}var {g.Handle} = {allNull}");
                        o.Add($"{fInd}    ? default");
                        o.Add($"{fInd}    : GCHandle.Alloc(new {g.StateType} {{ {inits} }});");
                    }
                    BuildBag();
                    if (parks) o.Add($"{fInd}s_parkedCallbackException = null;");
                    var signalsOk = IsBoolType(slot.Returns);
                    var capture = signalsOk ? "ok" : retType == "void" ? null : "result";
                    var failed = signalsOk ? "!ok" : "err != null";
                    o.Add($"{fInd}ke_error* err = null;");
                    if (signalsOk) o.Add($"{fInd}bool ok;");
                    else if (capture is not null) o.Add($"{fInd}{retType} {capture};");
                    o.Add($"{fInd}try");
                    o.Add($"{fInd}{{");
                    o.Add($"{fInd}    {(capture is null ? "" : capture + " = ")}Handle->{slot.Name}(Handle{call}, &err)"
                        + (slot.Returns == "ke_bool" ? " != 0" : "") + ";");
                    o.Add($"{fInd}}}");
                    if (scoped.Count > 0)
                    {
                        o.Add($"{fInd}finally");
                        o.Add($"{fInd}{{");
                        foreach (var g in scoped)
                            o.Add($"{fInd}    if ({g.Handle}.IsAllocated) {g.Handle}.Free();");
                        o.Add($"{fInd}}}");
                    }
                    else
                    {
                        o.Add($"{fInd}catch");
                        o.Add($"{fInd}{{");
                        foreach (var g in groups)
                            o.Add($"{fInd}    if ({g.Handle}.IsAllocated) {g.Handle}.Free();");
                        o.Add($"{fInd}    throw;");
                        o.Add($"{fInd}}}");
                    }
                    if (parks)
                    {
                        o.Add($"{fInd}if (s_parkedCallbackException is {{ }} parked)");
                        o.Add($"{fInd}{{");
                        o.Add($"{fInd}    s_parkedCallbackException = null;");
                        o.Add($"{fInd}    throw parked;");
                        o.Add($"{fInd}}}");
                    }
                    var retained = groups.Where(g => g.Lifetime == ClosureLifetime.Retained).ToList();
                    if (retained.Count == 0 && signalsOk)
                        o.Add($"{fInd}KernelError.ThrowIfFailed(ok, err, \"{slot.Name}\");");
                    else if (retained.Count == 0)
                    {
                        o.Add($"{fInd}if ({failed}) throw KernelError.FromNative(err, \"{slot.Name}\");");
                    }
                    else
                    {
                        o.Add($"{fInd}if ({failed})");
                        o.Add($"{fInd}{{");
                        foreach (var g in retained)
                            o.Add($"{fInd}    if ({g.Handle}.IsAllocated) {g.Handle}.Free();");
                        o.Add($"{fInd}    throw KernelError.FromNative(err, \"{slot.Name}\");");
                        o.Add($"{fInd}}}");
                        foreach (var g in retained)
                        {
                            var field = g.Retained;
                            if (g.RetainByReturn)
                                o.Add($"{fInd}if ({g.Handle}.IsAllocated) {field}[{capture}] = {g.Handle};");
                            else if (g.RetainKey is { } key)
                            {
                                var k = Idioms.Ident(key.Name!);
                                var replaced = $"replaced{Idioms.Pascal(g.Pairs[0].Fn.Name!)}";
                                o.Add($"{fInd}if ({field}.Remove({k}, out var {replaced})) {replaced}.Free();");
                                o.Add($"{fInd}{field}[{k}] = {g.Handle};");
                            }
                            else
                            {
                                o.Add($"{fInd}if ({field}.IsAllocated) {field}.Free();");
                                o.Add($"{fInd}{field} = {g.Handle};");
                            }
                        }
                    }
                    if (capture == "result") o.Add($"{fInd}return result;");
                    for (var d = fDepth; d > 0; d--) o.Add(new string(' ', 4 + d * 4) + "}");
                    o.Add("    }");
                    o.Add("");
                    foreach (var g in groups.Where(x => x.UsesState)) RenderClosureState(o, g);
                    foreach (var g in groups)
                        foreach (var cb in g.Pairs)
                            RenderTrampoline(model, o, cb, g);
                    return;
                }
                BuildBag();
                o.Add($"{fInd}ke_error* err = null;");
                if (byReturn && rooted.Count > 0)
                {
                    var boolCall = $"Handle->{slot.Name}(Handle{call}, &err)"
                        + (slot.Returns == "ke_bool" ? " != 0" : "");
                    o.Add($"{fInd}if (!{boolCall})");
                    o.Add($"{fInd}{{");
                    foreach (var rp in rooted)
                        o.Add($"{fInd}    {Idioms.Ident(rp.Name!)}Handle.Free();");
                    o.Add($"{fInd}    throw KernelError.FromNative(err, \"{slot.Name}\");");
                    o.Add($"{fInd}}}");
                    foreach (var rp in rooted)
                        o.Add($"{fInd}_rooted[{Idioms.Ident(rp.TagValue("rooted")!)}] = {Idioms.Ident(rp.Name!)}Handle;");
                }
                else if (byReturn && ownerDrains && slot.Has("drains"))
                {
                    var boolCall = $"Handle->{slot.Name}(Handle{call}, &err)"
                        + (slot.Returns == "ke_bool" ? " != 0" : "");
                    o.Add($"{fInd}if (!{boolCall} && _callbackFailures.IsEmpty)");
                    o.Add($"{fInd}    throw KernelError.FromNative(err, \"{slot.Name}\");");
                    o.Add($"{fInd}DrainCallbackFailures();");
                }
                else if (byReturn)
                {
                    var boolCall = $"Handle->{slot.Name}(Handle{call}, &err)"
                        + (slot.Returns == "ke_bool" ? " != 0" : "");
                    o.Add($"{fInd}KernelError.ThrowIfFailed({boolCall}, err, \"{slot.Name}\");");
                }
                else
                {
                    o.Add($"{fInd}var result = Handle->{slot.Name}(Handle{call}, &err);");
                    if (CTypes.IsPointer(slot.Returns))
                        o.Add($"{fInd}if (result == null) throw KernelError.FromNative(err, \"{slot.Name}\");");
                    else
                        o.Add($"{fInd}if (err != null) throw KernelError.FromNative(err, \"{slot.Name}\");");
                    o.Add($"{fInd}return result;");
                }
                for (var d = fDepth; d > 0; d--) o.Add(new string(' ', 4 + d * 4) + "}");
                o.Add("    }");
                o.Add("");
                return;
            }
            default:
            {
                var args = cs.PublicParams;
                var sig = Sig(args);
                var call = string.Concat(NativeParams().Select(p => ", " + CallArg(p)));
                var retType = slot.Returns == "ke_bool" ? "bool" : CsType(model, slot.Returns);
                var needsCast = retType == "nint";
                Declare(o, decls,
                    XmlDoc("    ", slot.Doc, args.Select(p => (Idioms.Ident(p.Name!), p.Doc)), slot.ReturnDoc).TrimEnd(),
                    $"{retType} {name}({sig})");
                o.Add("    {");
                var (pPro, pDepth) = Utf8Prologue(args, new string(' ', 8));
                var (pSeq, pSeqDepth) = SequencePrologue(model, cs.Sequences,
                    new string(' ', 8 + pDepth * 4), convention);
                o.AddRange(pPro);
                o.AddRange(pSeq);
                pDepth += pSeqDepth;
                var pInd = new string(' ', 8 + pDepth * 4);
                if (slot.Returns == "ke_bool")
                    o.Add($"{pInd}return Handle->{slot.Name}(Handle{call}) != 0;");
                else if (retType == "void")
                {
                    o.Add($"{pInd}Handle->{slot.Name}(Handle{call});");
                    if (slot.TagValue("unroots") is string freedKey)
                    {
                        o.Add($"{pInd}if (_rooted.Remove({Idioms.Ident(freedKey)}, out var freed)) freed.Free();");
                    }
                }
                else if (needsCast)
                    o.Add($"{pInd}return (nint)Handle->{slot.Name}(Handle{call});");
                else
                    o.Add($"{pInd}return Handle->{slot.Name}(Handle{call});");
                for (var d = pDepth; d > 0; d--) o.Add(new string(' ', 4 + d * 4) + "}");
                o.Add("    }");
                o.Add("");
                return;
            }
        }

        string CallArg(ApiParam p) =>
            callbacks.FirstOrDefault(c => c.Fn == p) is { } fnOf
                ? $"{Idioms.Ident(p.Name!)} is null ? null : ({NativeFnPtr(model, fnOf)})&{fnOf.Trampoline}"
            : groups.FirstOrDefault(g => g.Ctx == p) is { } ctxOf
                ? $"(void*)GCHandle.ToIntPtr({ctxOf.Handle})"
            : cs.Sequences.FirstOrDefault(s => s.Seq == p) is { } asSeq
                ? SequenceArg(model, asSeq, convention)
            : cs.Sequences.FirstOrDefault(s => s.Count == p) is { } asCount
                ? $"({CsType(model, asCount.Count.Type)}){Idioms.Ident(asCount.Seq.Name!)}.Length"
            : lanes.TryGetValue(p, out var lane) ? $"{Idioms.Ident(lane.Vector)}.{lane.Lane}"
            : p.Has("rooted") ? $"(void*)System.Runtime.InteropServices.GCHandle.ToIntPtr({Idioms.Ident(p.Name!)}Handle)"
            : p.Has("ctx") ? $"({CTypes.Normalize(p.Type)}){Idioms.Ident(p.Name!)}"
            : p.Has("utf8") ? $"(sbyte*){Idioms.Ident(p.Name!)}Ptr"
            : p.Type.Trim() == "ke_bool" ? $"{Idioms.Ident(p.Name!)} ? (byte)1 : (byte)0"
            : model.Enums.Any(e => e.Name == p.Type.Trim()) ? $"({p.Type.Trim()}){Idioms.Ident(p.Name!)}"
            : p.Has("enum") && CTypes.IsPointer(p.Type) ? $"({p.Type.Trim()}){Idioms.Ident(p.Name!)}"
            : p.Has("enum") ? $"({Idioms.CsPrimitive(p.Type)}){Idioms.Ident(p.Name!)}"
            : UntypedPointer(p.Type) is string cast ? $"({cast}){Idioms.Ident(p.Name!)}"
            : Idioms.Ident(p.Name!);
    }

    /// <summary>
    /// The native spelling an untyped pointer parameter has to be cast back to at the
    /// call. The public surface takes <c>nint</c>, which is the idiomatic way for a
    /// caller to hold a pointer the engine never dereferences, but the vtable slot is
    /// still declared in the ABI's own terms — a return value already makes this trip
    /// in the other direction.
    /// </summary>
    static string? UntypedPointer(string type)
    {
        var t = type.Replace(" ", "");
        return t switch
        {
            "void*" => "void*",
            "void**" => "void**",
            _ => null,
        };
    }

    static void RenderCallbackMethod(List<string> o, List<MemberDecl>? decls, ApiStruct vtable,
        ClassifiedSlot cs, ClassifiedModel classified, string ownerType, Convention convention)
    {
        var slot = cs.Slot;
        var cbParam = cs.PublicParams.First(p => classified.Callbacks.Any(c => c.Name == p.Type.Trim()));
        var cbType = classified.Callbacks.First(c => c.Name == cbParam.Type.Trim());
        var ifaceName = "I" + Idioms.TypeName(cbType.Name, convention) + "Native";
        var hasLevel = classified.CallbackHasLevel.GetValueOrDefault(cbType.Name);
        var handlesField = $"_{Idioms.Camel(slot.Name)}Handles";
        var otherParams = cs.PublicParams.Where(p => p != cbParam).ToList();

        o.Add($"    private readonly List<GCHandle> {handlesField} = [];");
        o.Add("");
        var lvlArg = hasLevel ? ", int minLevel = 0" : "";
        var otherArgs = string.Concat(otherParams.Select(p => $", {CsParamType2(p)} {Idioms.Ident(p.Name!)}"));
        Declare(o, decls,
            XmlDoc("    ", slot.Doc, [(Idioms.Ident(cbParam.Name!), cbParam.Doc)], throwsOnFail: true).TrimEnd(),
            $"void {Idioms.Pascal(slot.Name)}({ifaceName} {Idioms.Ident(cbParam.Name!)}{otherArgs}{lvlArg})");
        o.Add("    {");
        o.Add($"        var gch = GCHandle.Alloc({Idioms.Ident(cbParam.Name!)});");
        o.Add($"        {handlesField}.Add(gch);");
        o.Add($"        var native = new {cbType.Name}");
        o.Add("        {");
        o.Add("            handle = GCHandle.ToIntPtr(gch).ToPointer(),");
        if (hasLevel) o.Add("            min_level = minLevel,");
        foreach (var s in cbType.Slots)
            o.Add($"            {s.Name} = &{Idioms.Pascal(s.Name)}Trampoline,");
        o.Add("        };");
        o.Add("        ke_error* err = null;");
        var extraCall = string.Concat(otherParams.Select(p => ", " + Idioms.Ident(p.Name!)));
        o.Add($"        KernelError.ThrowIfFailed(Handle->{slot.Name}(Handle, native{extraCall}, &err), err, \"{slot.Name}\");");
        o.Add("    }");
        o.Add("");

        var cbParamCsType = CTypes.Deref(cbParam.Type);
        Declare(o, decls,
            $"    /// <summary>{slot.Doc} Takes an already-built <c>{cbType.Name}</c> value directly — for one produced by a native factory, not a managed <see cref=\"{ifaceName}\"/>.</summary>\n"
            + XmlDoc("    ", null, otherParams.Select(p => (Idioms.Ident(p.Name!), p.Doc)), throwsOnFail: true).TrimEnd(),
            $"void {Idioms.Pascal(slot.Name)}Raw({cbParamCsType} {Idioms.Ident(cbParam.Name!)}{otherArgs})");
        o.Add("    {");
        o.Add("        ke_error* err = null;");
        o.Add($"        KernelError.ThrowIfFailed(Handle->{slot.Name}(Handle, {Idioms.Ident(cbParam.Name!)}{extraCall}, &err), err, \"{slot.Name}\");");
        o.Add("    }");
        o.Add("");

        foreach (var s in cbType.Slots)
        {
            var trampParams = s.Params.Select(p =>
                (CTypes.IsPointer(p.Type) ? $"{CTypes.Deref(p.Type)}*" : Idioms.CsPrimitive(p.Type)) + " " + Idioms.Ident(p.Name!));
            var sig = string.Join(", ", new[] { $"{cbType.Name}* self" }.Concat(trampParams));
            o.Add("    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]");
            o.Add($"    private static {Idioms.CsPrimitive(s.Returns)} {Idioms.Pascal(s.Name)}Trampoline({sig})");
            o.Add("    {");
            if (s.Name == "destroy")
            {
                o.Add("        GCHandle.FromIntPtr((nint)self->handle).Free();");
            }
            else
            {
                var callArgs = string.Concat(s.Params.Select(p =>
                    ", " + (CTypes.IsPointer(p.Type) ? $"in *{Idioms.Ident(p.Name!)}" : Idioms.Ident(p.Name!))));
                o.Add($"        var target = ({ifaceName})GCHandle.FromIntPtr((nint)self->handle).Target!;");
                o.Add($"        target.{Idioms.Pascal(s.Name)}({callArgs.TrimStart(',', ' ')});");
            }
            o.Add("    }");
            o.Add("");
        }

        string CsParamType2(ApiParam p) => p.Has("enum") ? Idioms.TypeName(p.TagValue("enum")!, convention) : Idioms.CsPrimitive(p.Type);
    }

    public static string RenderCallbackInterface(ApiStruct cbType, string ns, string nativeNs, Convention convention)
    {
        var ifaceName = "I" + Idioms.TypeName(cbType.Name, convention) + "Native";
        var owned = cbType.Slots.Where(s => s.Name != "destroy").ToList();

        var o = new List<string>
        {
            Header,
            $"using {nativeNs};",
            "",
            $"namespace {ns};",
            "",
        };
        o.Add(XmlDoc("", cbType.Doc).TrimEnd());
        o.Add($"public unsafe interface {ifaceName}");
        o.Add("{");
        foreach (var s in owned)
        {
            o.Add(XmlDoc("    ", s.Doc).TrimEnd());
            var ps = string.Join(", ", s.Params.Select(p =>
                (CTypes.IsPointer(p.Type) ? $"in {CTypes.Deref(p.Type)}" : Idioms.CsPrimitive(p.Type)) + " " + Idioms.Ident(p.Name!)));
            o.Add($"    {Idioms.CsPrimitive(s.Returns)} {Idioms.Pascal(s.Name)}({ps});");
        }
        o.Add("}");
        o.Add("");
        return string.Join('\n', o);
    }

    public static string RenderFreeFunctions(ApiModel model, string owner, List<GroupedFunction> fns, string ns, string nativeNs,
        IReadOnlyList<string> extraUsings, string libraryName, Convention convention)
    {
        var ownerCs = Idioms.TypeName(owner, convention);
        var prefix = owner + "_";

        var o = new List<string>
        {
            Header,
            "using System.Runtime.InteropServices;",
            "using KernelEngine.Common.Native;",
            $"using {nativeNs};",
        };
        foreach (var u in extraUsings) o.Add($"using {u};");
        o.AddRange([
            "",
            $"namespace {ns};",
            "",
            $"/// <summary>Free-function operations on <see cref=\"{owner}\"/>.</summary>",
            $"public unsafe partial class {ownerCs}",
            "{",
        ]);

        foreach (var g in fns)
        {
            var f = g.Fn;
            var self = g.SelfParam;
            var rest = self is not null ? f.Params.Skip(1).ToList() : f.Params;
            var strippedName = f.Name.StartsWith(prefix) ? f.Name[prefix.Length..]
                : convention.StripPrefix(f.Name);
            var methodName = Idioms.Pascal(strippedName);
            var sig = string.Join(", ", rest.Select(p =>
                CsParamType(model, p, convention) + " " + Idioms.Ident(p.Name!)));
            var call = string.Concat(rest.Select(p => ", " + (p.Has("enum") ? $"(int){Idioms.Ident(p.Name!)}" : Idioms.Ident(p.Name!))));
            var retType = f.Returns == "ke_bool" ? "bool" : CsType(model, f.Returns);
            var selfSig = self is not null ? $"in {CsType(model, CTypes.Deref(self.Type))} {Idioms.Ident(self.Name!)}" : null;
            var fullSig = string.Join(", ", new[] { selfSig }.Where(s => s is not null).Append(sig).Where(s => s!.Length > 0));

            o.Add(XmlDoc("    ", f.Doc, rest.Select(p => (Idioms.Ident(p.Name!), p.Doc))).TrimEnd());
            o.Add($"    public static {retType} {methodName}({fullSig})");
            o.Add("    {");
            var ret = retType == "void" ? "" : "return ";
            var coerce = f.Returns == "ke_bool" ? " != 0" : "";
            if (self is not null)
            {
                o.Add($"        fixed ({CsType(model, CTypes.Deref(self.Type))}* p = &{Idioms.Ident(self.Name!)})");
                o.Add($"            {ret}Native.{f.Name}(p{call}){coerce};");
            }
            else
            {
                var call2 = string.Join(", ", rest.Select(p => p.Has("enum") ? $"(int){Idioms.Ident(p.Name!)}" : Idioms.Ident(p.Name!)));
                o.Add($"        {ret}Native.{f.Name}({call2}){coerce};");
            }
            o.Add("    }");
            o.Add("");
        }

        o.Add("    private static unsafe class Native");
        o.Add("    {");
        foreach (var g in fns)
        {
            var f = g.Fn;
            var rest = (g.SelfParam is not null ? f.Params.Skip(1) : f.Params)
                .Select(p => $"{(p.Has("enum") ? "int" : CsType(model, p.Type))} {Idioms.Ident(p.Name!)}").ToList();
            var selfParamSig = g.SelfParam is not null ? $"{CsType(model, CTypes.Deref(f.Params[0].Type))}* {Idioms.Ident(f.Params[0].Name!)}" : null;
            var nativeSig = string.Join(", ", (selfParamSig is not null ? [selfParamSig] : Array.Empty<string>()).Concat(rest));
            o.Add($"        [DllImport(\"{libraryName}\", CallingConvention = CallingConvention.Cdecl,");
            o.Add($"                   EntryPoint = \"{f.Name}\", ExactSpelling = true)]");
            o.Add($"        public static extern {(f.Returns == "ke_bool" ? "byte" : CsType(model, f.Returns))} {f.Name}({nativeSig});");
            o.Add("");
        }
        o.Add("    }");
        o.Add("}");
        o.Add("");
        return string.Join('\n', o);
    }

}
