<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KernelEngine.Kernel.Native\KernelEngine.Kernel.Native.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <NativeTarget>ke_asset_loader_assimp</NativeTarget>
  </PropertyGroup>

  <Import Project="../NativeDependencies.targets" />

</Project>
