// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using System.Runtime.InteropServices;
using KernelEngine.Physics;

namespace KernelEngine.Framework;

/// <summary>A 2D rigid body. Pose and motion are stored here because the simulation owns them between ticks; the node's own transform2d is written back from this component each tick by the physics plugin's own system, so what a script reads and what the hierarchy composes are the same two dimensions the body moves in. The same system creates and destroys the underlying body by reconciling this component against the world, so the entity is the identity and a script never acquires, threads, or releases a handle.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct Body2dComponent
{
    /// <summary>The name this component is registered under, which is its only identity across languages. Derived from the struct the ABI declares, so a caller naming the component and the storage holding it cannot come to disagree.</summary>
    public const string Name = "body2d";

    public BodyType2D Type;
    public Vector2 Position;
    /// <summary>Radians, CCW positive.</summary>
    public float Angle;
    public Vector2 Velocity;
    /// <summary>Radians per second, CCW positive.</summary>
    public float AngularVelocity;
    public float GravityScale;
    /// <summary>Keeps the body's angle fixed against every torque, including contacts. What anything that must stay upright sets — characters, projectiles.</summary>
    public bool FixedRotation;
    /// <summary>The plugin's body for this entity, assigned when it reconciles the component. Authoring it would name a body the world does not own.</summary>
    public uint Body;

    /// <summary>The value every <c>[default:]</c> field of <c>ke_body2d_component</c> declares. A zero-initialized instance is not the same thing: zero is a value the ABI reads as itself, so a field whose neutral value is not zero has to be seeded.</summary>
    public static Body2dComponent Default => new()
    {
        GravityScale = 1f,
    };
}
