// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Common.Native;
using KernelEngine.Physics.Native;
using KernelEngine.Physics;

namespace KernelEngine.Framework;

/// <summary>A 2D rigid body. Pose and motion are stored here in two dimensions because that is what the simulation owns; the composed transform is derived output, written from this component each tick by the physics plugin's own system. The same system creates and destroys the underlying body by reconciling this component against the world, so the entity is the identity and a script never acquires, threads, or releases a handle.</summary>
[GeneratedNodeComponent(typeof(ke_transform_component), "transform")]
[GeneratedNodeComponent(typeof(ke_body2d_component), "body2d")]
public partial class Body2D : Node
{
    public Body2D()
    {
        _generatedState0 = global::System.Runtime.CompilerServices.Unsafe.BitCast<KernelEngine.Ecs.TransformComponent, ke_transform_component>(KernelEngine.Ecs.TransformComponent.Identity);
        _generatedState1.gravity_scale = 1f;
    }

    [NativeWhole(Component = typeof(ke_transform_component))]
    public partial KernelEngine.Ecs.TransformComponent LocalTransform { get; set; }

    [NativeField("type", Component = typeof(ke_body2d_component))]
    public partial BodyType2D Type { get; set; }

    [NativeField("position", Component = typeof(ke_body2d_component))]
    public partial Vector2 Position { get; set; }

    /// <summary>Radians, CCW positive.</summary>
    [NativeField("angle", Component = typeof(ke_body2d_component))]
    public partial float Angle { get; set; }

    [NativeField("velocity", Component = typeof(ke_body2d_component))]
    public partial Vector2 Velocity { get; set; }

    /// <summary>Radians per second, CCW positive.</summary>
    [NativeField("angular_velocity", Component = typeof(ke_body2d_component))]
    public partial float AngularVelocity { get; set; }

    [NativeField("gravity_scale", Component = typeof(ke_body2d_component))]
    public partial float GravityScale { get; set; }

    /// <summary>Keeps the body's angle fixed against every torque, including contacts. What anything that must stay upright sets — characters, projectiles.</summary>
    [NativeField("fixed_rotation", Component = typeof(ke_body2d_component))]
    public partial bool FixedRotation { get; set; }
}