// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Physics;

namespace KernelEngine.Framework;

/// <summary>A 2D rigid body. Pose and motion are stored here because the simulation owns them between ticks; the node's own transform2d is written back from this component each tick by the physics plugin's own system, so what a script reads and what the hierarchy composes are the same two dimensions the body moves in. The same system creates and destroys the underlying body by reconciling this component against the world, so the entity is the identity and a script never acquires, threads, or releases a handle.</summary>
[GeneratedNodeComponent(typeof(Body2dComponent), "body2d")]
public partial class Body2D : Node2D
{
    public Body2D()
    {
        _generatedState0 = Body2dComponent.Default;
    }

    [NativeField("Type", Component = typeof(Body2dComponent))]
    public partial BodyType2D Type { get; set; }

    [NativeField("Position", Component = typeof(Body2dComponent))]
    public partial Vector2 Position { get; set; }

    /// <summary>Radians, CCW positive.</summary>
    [NativeField("Angle", Component = typeof(Body2dComponent))]
    public partial float Angle { get; set; }

    [NativeField("Velocity", Component = typeof(Body2dComponent))]
    public partial Vector2 Velocity { get; set; }

    /// <summary>Radians per second, CCW positive.</summary>
    [NativeField("AngularVelocity", Component = typeof(Body2dComponent))]
    public partial float AngularVelocity { get; set; }

    [NativeField("GravityScale", Component = typeof(Body2dComponent))]
    public partial float GravityScale { get; set; }

    /// <summary>Keeps the body's angle fixed against every torque, including contacts. What anything that must stay upright sets — characters, projectiles.</summary>
    [NativeField("FixedRotation", Component = typeof(Body2dComponent))]
    public partial bool FixedRotation { get; set; }
}