// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Physics;

namespace KernelEngine.Framework;

/// <summary>One collision fixture, attached to the nearest ancestor that carries a ke_body2d_component. Named for what it holds — a kind, extents, density, friction, restitution — rather than for a shape it is not. It is a node of its own rather than a field on the body because it has an offset the body does not, and because a body may carry several. The physics plugin's own system attaches the fixture by reconciling this component against the hierarchy, so a script never names a body.</summary>
[GeneratedNodeComponent(typeof(Collider2dComponent), "collider2d")]
public partial class Collider2D : Node2D
{
    public Collider2D()
    {
        _generatedState0 = Collider2dComponent.Default;
    }

    [NativeField("Kind", Component = typeof(Collider2dComponent))]
    public partial ShapeKind2d Kind { get; set; }

    [NativeField("HalfExtents", Component = typeof(Collider2dComponent))]
    public partial Vector2 HalfExtents { get; set; }

    [NativeField("Radius", Component = typeof(Collider2dComponent))]
    public partial float Radius { get; set; }

    [NativeField("Density", Component = typeof(Collider2dComponent))]
    public partial float Density { get; set; }

    [NativeField("Friction", Component = typeof(Collider2dComponent))]
    public partial float Friction { get; set; }

    /// <summary>Bounciness. 0 absorbs the impact, 1 returns all of it.</summary>
    [NativeField("Restitution", Component = typeof(Collider2dComponent))]
    public partial float Restitution { get; set; }

    [NativeField("Layer", Component = typeof(Collider2dComponent))]
    public partial uint Layer { get; set; }

    [NativeField("Mask", Component = typeof(Collider2dComponent))]
    public partial uint Mask { get; set; }
}