// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using KernelEngine.Common.Native;
using KernelEngine.Physics.Native;
using KernelEngine.Physics;

namespace KernelEngine.Framework;

/// <summary>One collision fixture, attached to the nearest ancestor that carries a ke_body2d_component. A shape is a node of its own rather than a field on the body because it has an offset the body does not, and because a body may carry several. The physics plugin's own system attaches the fixture by reconciling this component against the hierarchy, so a script never names a body.</summary>
[GeneratedNodeComponent(typeof(ke_collider2d_component), "collider2d")]
public partial class CollisionShape2D : Node2D
{
    public CollisionShape2D()
    {
        _generatedState0.half_extents = new ke_vec2 { x = 0.5f, y = 0.5f };
        _generatedState0.radius = 0.5f;
        _generatedState0.density = 1f;
        _generatedState0.friction = 0.3f;
    }

    [NativeField("kind", Component = typeof(ke_collider2d_component))]
    public partial ShapeKind2d Kind { get; set; }

    [NativeField("half_extents", Component = typeof(ke_collider2d_component))]
    public partial Vector2 HalfExtents { get; set; }

    [NativeField("radius", Component = typeof(ke_collider2d_component))]
    public partial float Radius { get; set; }

    [NativeField("density", Component = typeof(ke_collider2d_component))]
    public partial float Density { get; set; }

    [NativeField("friction", Component = typeof(ke_collider2d_component))]
    public partial float Friction { get; set; }

    /// <summary>Bounciness. 0 absorbs the impact, 1 returns all of it.</summary>
    [NativeField("restitution", Component = typeof(ke_collider2d_component))]
    public partial float Restitution { get; set; }
}