// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Numerics;
using System.Runtime.InteropServices;

namespace KernelEngine.Framework;

/// <summary>One collision fixture, attached to the nearest ancestor that carries a ke_body2d_component. Named for what it holds — a kind, extents, density, friction, restitution — rather than for a shape it is not. It is a node of its own rather than a field on the body because it has an offset the body does not, and because a body may carry several. The physics plugin's own system attaches the fixture by reconciling this component against the hierarchy, so a script never names a body.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct Collider2dComponent
{
    /// <summary>The name this component is registered under, which is its only identity across languages. Derived from the struct the ABI declares, so a caller naming the component and the storage holding it cannot come to disagree.</summary>
    public const string Name = "collider2d";

    public ShapeKind2d Kind;
    public Vector2 HalfExtents;
    public float Radius;
    public float Density;
    public float Friction;
    /// <summary>Bounciness. 0 absorbs the impact, 1 returns all of it.</summary>
    public float Restitution;
    public uint Layer;
    public uint Mask;
    /// <summary>Whether the fixture has been attached to its body. Set by the plugin once the ancestor body exists; authoring it would claim a fixture the world does not have.</summary>
    public bool Attached;

    /// <summary>The value every <c>[default:]</c> field of <c>ke_collider2d_component</c> declares. A zero-initialized instance is not the same thing: zero is a value the ABI reads as itself, so a field whose neutral value is not zero has to be seeded.</summary>
    public static Collider2dComponent Default => new()
    {
        HalfExtents = new Vector2(0.5f, 0.5f),
        Radius = 0.5f,
        Density = 1f,
        Friction = 0.3f,
        Layer = 1,
        Mask = 4294967295,
    };
}
