// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

namespace KernelEngine.Framework;

/// <summary>Mirrors <c>ke_shape_kind_2d</c>.</summary>
public enum ShapeKind2d
{
    /// <summary>Axis-aligned box, sized by half_extents.</summary>
    Box = 0,
    /// <summary>Circle centered on the node, sized by radius.</summary>
    Circle = 1,
}
