#!/usr/bin/env dotnet run

// Compile a Slang shader to a backend language and embed it as a C header (a
// NUL-terminated string array), or write the raw compiled source (--raw).
//
// Why a wrapper instead of slangc's own -o / -source-embed: slangc 2025.17.2
// emits a DIFFERENT (invalid) WGSL module when writing to a file via -o or
// -source-embed-style than when writing to stdout — the file path drops the
// @location on inter-stage vertex outputs, which WGSL rejects. Capturing
// stdout is the only path that produces a valid module, so this compiles via
// stdout capture and does the C-string embedding here.
//
// slangc is located via PATH or the Vulkan SDK ($VULKAN_SDK/Bin or /bin).

using System.Diagnostics;

string? input = null, output = null, name = null, target = "wgsl", entry = null, stage = null;
var includes = new List<string>();
var raw = false;

for (var i = 0; i < args.Length; i++)
{
    switch (args[i])
    {
        case "--input": input = args[++i]; break;
        case "--output": output = args[++i]; break;
        case "--name": name = args[++i]; break;
        case "--target": target = args[++i]; break;
        case "--entry": entry = args[++i]; break;
        case "--stage": stage = args[++i]; break;
        case "--include": includes.Add(args[++i]); break;
        case "--raw": raw = true; break;
        default:
            Console.Error.WriteLine($"Unknown argument: {args[i]}");
            return 1;
    }
}

if (input is null || output is null)
{
    Console.Error.WriteLine("Error: --input and --output are required.");
    return 1;
}
if (!raw && name is null)
{
    Console.Error.WriteLine("Error: --name is required unless --raw is set.");
    return 1;
}

var slangc = FindSlangc();
if (slangc is null)
{
    Console.Error.WriteLine("Error: slangc not found on PATH or under $VULKAN_SDK.");
    return 1;
}

var slangcArgs = new List<string> { input, "-target", target };
foreach (var inc in includes) slangcArgs.AddRange(["-I", inc]);
if (entry is not null) slangcArgs.AddRange(["-entry", entry]);
if (stage is not null) slangcArgs.AddRange(["-stage", stage]);

using var process = new Process
{
    StartInfo = new ProcessStartInfo(slangc)
    {
        RedirectStandardOutput = true,
        RedirectStandardError = true,
    },
};
foreach (var a in slangcArgs) process.StartInfo.ArgumentList.Add(a);
process.Start();
var stdout = process.StandardOutput.ReadToEnd();
var stderr = process.StandardError.ReadToEnd();
process.WaitForExit();

if (process.ExitCode != 0)
{
    Console.Error.WriteLine($"slangc failed for {input}:\n{stderr.Trim()}");
    return 1;
}

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);
await File.WriteAllTextAsync(output, raw ? stdout : EmbedCString(name!, stdout));
return 0;

static string? FindSlangc()
{
    var pathVar = Environment.GetEnvironmentVariable("PATH") ?? "";
    var exeNames = OperatingSystem.IsWindows() ? new[] { "slangc.exe" } : ["slangc"];
    foreach (var dir in pathVar.Split(Path.PathSeparator))
    foreach (var exe in exeNames)
    {
        var candidate = Path.Combine(dir, exe);
        if (File.Exists(candidate)) return candidate;
    }

    var sdk = Environment.GetEnvironmentVariable("VULKAN_SDK");
    if (sdk is null) return null;
    foreach (var sub in new[] { "Bin", "bin" })
    foreach (var ext in new[] { "", ".exe" })
    {
        var candidate = Path.Combine(sdk, sub, "slangc" + ext);
        if (File.Exists(candidate)) return candidate;
    }
    return null;
}

// Render WGSL/text source as a NUL-terminated C string literal array.
static string EmbedCString(string name, string text)
{
    var lines = new List<string> { "// Generated by compile_slang.cs — do not edit.", "#pragma once", "" };
    lines.Add($"static const char {name}[] =");
    foreach (var line in SplitLines(text))
    {
        var escaped = line.Replace("\\", "\\\\").Replace("\"", "\\\"");
        lines.Add($"    \"{escaped}\\n\"");
    }
    lines.Add("    ;");
    lines.Add("");
    return string.Join('\n', lines);
}

// Matches Python's str.splitlines(): no trailing empty entry for a final
// line terminator, and an empty input yields zero lines.
static IEnumerable<string> SplitLines(string text)
{
    if (text.Length == 0) yield break;
    var normalized = text.Replace("\r\n", "\n").Replace("\r", "\n");
    var trailingNewline = normalized.EndsWith('\n');
    var parts = normalized.Split('\n');
    var count = trailingNewline ? parts.Length - 1 : parts.Length;
    for (var i = 0; i < count; i++) yield return parts[i];
}
