#!/usr/bin/env dotnet run

using System.Diagnostics;

string? input = null, output = null, name = null, target = "wgsl", entry = null, stage = null, slangcOverride = null;
var includes = new List<string>();

for (var i = 0; i < args.Length; i++)
{
    switch (args[i])
    {
        case "--input": input = args[++i]; break;
        case "--output": output = args[++i]; break;
        case "--name": name = args[++i]; break;
        case "--target": target = args[++i]; break;
        case "--entry": entry = args[++i]; break;
        case "--stage": stage = args[++i]; break;
        case "--include": includes.Add(args[++i]); break;
        case "--slangc": slangcOverride = args[++i]; break;
        default:
            Console.Error.WriteLine($"Unknown argument: {args[i]}");
            return 1;
    }
}

if (input is null || output is null)
{
    Console.Error.WriteLine("Error: --input and --output are required.");
    return 1;
}
if (name is null)
{
    Console.Error.WriteLine("Error: --name is required.");
    return 1;
}

var slangc = slangcOverride ?? FindSlangc();
if (slangc is null)
{
    Console.Error.WriteLine("Error: slangc not found (pass --slangc, or place it on PATH / $VULKAN_SDK).");
    return 1;
}

var slangcArgs = new List<string> { input, "-target", target };
foreach (var inc in includes) slangcArgs.AddRange(["-I", inc]);
if (entry is not null) slangcArgs.AddRange(["-entry", entry]);
if (stage is not null) slangcArgs.AddRange(["-stage", stage]);

using var process = new Process
{
    StartInfo = new ProcessStartInfo(slangc)
    {
        RedirectStandardOutput = true,
        RedirectStandardError = true,
    },
};
foreach (var a in slangcArgs) process.StartInfo.ArgumentList.Add(a);
process.Start();
var stdout = process.StandardOutput.ReadToEnd();
var stderr = process.StandardError.ReadToEnd();
process.WaitForExit();

if (process.ExitCode != 0)
{
    Console.Error.WriteLine($"slangc failed for {input}:\n{stderr.Trim()}");
    return 1;
}

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);
await File.WriteAllTextAsync(output, EmbedCString(name, stdout));
return 0;

static string? FindSlangc()
{
    var pathVar = Environment.GetEnvironmentVariable("PATH") ?? "";
    var exeNames = OperatingSystem.IsWindows() ? new[] { "slangc.exe" } : ["slangc"];
    foreach (var dir in pathVar.Split(Path.PathSeparator))
    foreach (var exe in exeNames)
    {
        var candidate = Path.Combine(dir, exe);
        if (File.Exists(candidate)) return candidate;
    }

    var sdk = Environment.GetEnvironmentVariable("VULKAN_SDK");
    if (sdk is null) return null;
    foreach (var sub in new[] { "Bin", "bin" })
    foreach (var ext in new[] { "", ".exe" })
    {
        var candidate = Path.Combine(sdk, sub, "slangc" + ext);
        if (File.Exists(candidate)) return candidate;
    }
    return null;
}

static string EmbedCString(string name, string text)
{
    var lines = new List<string> { "// Generated by compile_slang.cs — do not edit.", "#pragma once", "" };
    lines.Add($"static const char {name}[] =");
    foreach (var line in SplitLines(text))
    {
        var escaped = line.Replace("\\", "\\\\").Replace("\"", "\\\"");
        lines.Add($"    \"{escaped}\\n\"");
    }
    lines.Add("    ;");
    lines.Add("");
    return string.Join('\n', lines);
}

static IEnumerable<string> SplitLines(string text)
{
    if (text.Length == 0) yield break;
    var normalized = text.Replace("\r\n", "\n").Replace("\r", "\n");
    var trailingNewline = normalized.EndsWith('\n');
    var parts = normalized.Split('\n');
    var count = trailingNewline ? parts.Length - 1 : parts.Length;
    for (var i = 0; i < count; i++) yield return parts[i];
}
