<Project>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <NativeOS>linux</NativeOS>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <NativeOS>osx</NativeOS>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
      <NativeOS>win</NativeOS>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration) == 'Debug'">
    <NativeConfig>debug</NativeConfig>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration) == 'Release'">
    <NativeConfig>release</NativeConfig>
  </PropertyGroup>

  <PropertyGroup>
    <NativeArch>x64</NativeArch>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)' == 'arm64'">
    <NativeArch>arm64</NativeArch>
  </PropertyGroup>

  <!-- Construct the RID for the NuGet package -->
  <PropertyGroup>
    <NativeRID>$(NativeOS)-$(NativeArch)</NativeRID>
    <NativePreset>$(NativeRID)-$(NativeConfig)</NativePreset>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <NativeExt>so</NativeExt>
    <NativePre>lib</NativePre>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <NativeExt>dylib</NativeExt>
    <NativePre>lib</NativePre>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <NativeExt>dll</NativeExt>
    <NativePre></NativePre>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <NativeTypeDir>bin</NativeTypeDir>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <NativeTypeDir>lib</NativeTypeDir>
  </PropertyGroup>


  <PropertyGroup>
    <!-- Relative to src/csharp/Native/NativeDependencies.targets -->
    <RepoRoot>$(MSBuildThisFileDirectory)..\..\..\</RepoRoot>
    <NativeFinalDir>$(RepoRoot)build\native\$(NativeTypeDir)</NativeFinalDir>
    <NativeTargetBinary>$(NativeFinalDir)\$(NativePre)$(NativeTarget).$(NativeExt)</NativeTargetBinary>
  </PropertyGroup>

  <ItemGroup>
    <!-- 
      For Local Project References: 
      We use 'None' to copy the file to the output directory.
    -->
    <None Include="$(NativeTargetBinary)" Condition="Exists('$(NativeTargetBinary)')">
      <Link>$(NativePre)$(NativeTarget).$(NativeExt)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <!-- 
        For NuGet Packaging:
        This places the DLL in the standard 'runtimes' folder inside the .nupkg.
        When external users install the package, the .NET SDK automatically 
        handles the native file for the target RID.
      -->
      <Visible>false</Visible>
      <Pack>true</Pack>
      <PackagePath>runtimes/$(NativeRID)/native</PackagePath>
    </None>
  </ItemGroup>

</Project>
