// <auto-generated/>
// Derived from ke_api.json. Do not edit; edit the C header instead.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace KernelEngine.Framework;

/// <summary>A single audio clip, loaded from the path the scene declares and played on demand. The clip is one node's, not one system's: two AudioPlayer children under the same parent are two clips, told apart by node name.</summary>
[StructLayout(LayoutKind.Sequential)]
public partial struct AudioPlayerComponent
{
    /// <summary>The name this component is registered under, which is its only identity across languages. Derived from the struct the ABI declares, so a caller naming the component and the storage holding it cannot come to disagree.</summary>
    public const string Name = "audio_player";

    /// <summary>Elements <c>Path</c> has room for, as the ABI fixes it. A caller composing the field from a set it does not control checks this first -- there is no element past it to write.</summary>
    public const int PathCapacity = 256;

    /// <summary>Path to the audio file, resolved against the project's base directory.</summary>
    public PathBuffer Path;
    /// <summary>Linear gain, 0..1.</summary>
    public float Volume;

    /// <summary>The value every <c>[default:]</c> field of <c>ke_audio_player_component</c> declares. A zero-initialized instance is not the same thing: zero is a value the ABI reads as itself, so a field whose neutral value is not zero has to be seeded.</summary>
    public static AudioPlayerComponent Default => new()
    {
        Volume = 1f,
    };

    /// <summary>The <c>char[256]</c> of <c>Path</c> laid out inline, so the field occupies the bytes the ABI reads it from.</summary>
    [InlineArray(PathCapacity)]
    public partial struct PathBuffer
    {
        public sbyte Element;
    }
}
