<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KernelEngine.Ecs.Abstractions\KernelEngine.Ecs.Abstractions.csproj" />
    <ProjectReference Include="..\..\common\KernelEngine.Common\KernelEngine.Common.csproj" />
  </ItemGroup>

</Project>
