<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <NativeDep Include="ke_configuration" />
    <NativeDep Include="ke_configuration_toml" />
  </ItemGroup>

  <Import Project="../../NativeDependencies.targets" />

  <ItemGroup>
    <ProjectReference Include="..\..\common\KernelEngine.Common\KernelEngine.Common.csproj" />
    <ProjectReference Include="..\..\logger\KernelEngine.Logger.Abstractions\KernelEngine.Logger.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
  </ItemGroup>

</Project>
